### ISSUE TITLE
Bug: App crash while navigating to folders faster than usual

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10140]
### Description

The app is crashing whenever I navigate too fast.
I usually navigate to folders using a combination of arrow keys and the <kbd>Enter</kbd> key.

### Steps To Reproduce

1. Open Files app
2. Navigate to some folders fast enough that it would crash.

### Steps to fix

- Fix the crash to improve stability even when the user is navigating fast 

### Files Version

2.3.45.0 

### Windows Version

10.0.22623.730

### Relevant Assets/Logs

```py
2022-10-06 15:05:13.5383|ERROR|AppUnhandledException|Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
	System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
2022-10-06 15:05:13.7304|ERROR|AppUnhandledException|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IFrameMethods.Navigate(IObjectReference _obj, Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride)
   at Microsoft.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride)
   at Files.App.Views.ModernShellPage.NavigateToPath(String navigationPath, Type sourcePageType, NavigationArguments navArgs)
   at Files.App.Views.ModernShellPage.NavigateWithArguments(Type sourcePageType, NavigationArguments navArgs)
   at Files.App.Helpers.NavigationHelpers.OpenDirectory(String path, IShellPage associatedInstance, IEnumerable`1 selectItems, ShellLinkItem shortcutInfo, Boolean forceOpenInNewTab)
   at Files.App.Helpers.NavigationHelpers.OpenPath(String path, IShellPage associatedInstance, Nullable`1 itemType, Boolean openSilent, Boolean openViaApplicationPicker, IEnumerable`1 selectItems, String args, Boolean forceOpenInNewTab)
   at Files.App.Helpers.NavigationHelpers.OpenSelectedItems(IShellPage associatedInstance, Boolean openViaApplicationPicker)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at WinRT.EventSource__EventHandler`1.EventState.<GetEventInvoke>b__1_0(Object obj, T e)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
   
   ```

**Comment by verdaderoken** [comment]
I would also sometimes get this log when navigating

```
2022-10-06 15:10:39.5169|ERROR|AppUnhandledException|Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
	System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
```

**Comment by Josh-65** [comment]
Merging with #9921
