### ISSUE TITLE
Bug: Renaming a shortcut that has a blank name crashes the app

### ISSUE THREAD

**Issue by Himankan** [files-community/Files#10157]
### Description

I had a URL shortcut which I tried to rename. I deleted the existing name to nothing and then tried adding a name later and found out that renaming web shortcuts crashes the app.

### Steps To Reproduce

1. Create a shortcut using windows explorer (for any URL)
2. Open files and go to the directory containing the shortcut file
3. Delete existing name
4. Press enter
5. Try renaming to add a name again

### Steps to fix

- Fix crash that occurs

### Files Version

Version: 2.3.47.0 OS Version: 10.0.19044.2075

### Windows Version

Edition	Windows 10 Home Single Language Version	21H2 Installed on	‎31-‎03-‎2021 OS build	19044.2075 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9739150/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9739151/debug.log)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
I think we need to do some more investigation to see what the actual issue is.

**Comment by Josh-65** [comment]
This is what the log says.
```2022-10-08 17:05:00.9608|ERROR|AppUnhandledException|String cannot be of zero length. (Parameter 'oldValue')
	System.ArgumentException: String cannot be of zero length. (Parameter 'oldValue')
   at System.String.Replace(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue, StringComparison comparisonType)
   at Files.App.Helpers.UIFilesystemHelpers.RenameFileItemAsync(ListedItem item, String newName, IShellPage associatedInstance)
   at Files.App.Views.LayoutModes.DetailsLayoutBrowser.CommitRename(TextBox textBox)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at WinRT.EventSource__EventHandler`1.EventState.<GetEventInvoke>b__1_0(Object obj, T e)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)```
