### ISSUE TITLE
Bug: App crashes while drag and dropping files 

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10151]
### Description

The app crashed while I'm trying to drag and drop multiple files into a software.

### Steps To Reproduce

1. Select multiple files
2. Drag and drop to other software

### Steps to fix

- Implement an error handler for this (if possible)
- Prevent app crash 

### Files Version

2.3.46.0

### Windows Version

10.0.22623.730

### Relevant Assets/Logs

From debug_fultrust.log

```
2022-10-07 17:46:10.6369|INFO|IgnoreExceptions|The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
	System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Files.FullTrust.MessageHandlers.FileOperationsHandler.<>c__DisplayClass5_3.<ParseFileOperationAsync>b__5()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger)
2022-10-07 17:46:28.8458|INFO|OnConnectionRequestReceived|Argument: FileOperation
2022-10-07 17:50:28.3952|INFO|OnConnectionRequestReceived|Argument: FileOperation
2022-10-07 17:50:28.4009|INFO|IgnoreExceptions|The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
	System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Files.FullTrust.MessageHandlers.FileOperationsHandler.<>c__DisplayClass5_3.<ParseFileOperationAsync>b__5()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger)
```

**Comment by yaichenbaum** [comment]
Is this specific to the details layout?

**Comment by yaichenbaum** [comment]
We made some changes to the file handlers in v2.3.50, while they weren't specific to this issue, it might have solved them. Can you  check if it's still an issue?

**Comment by verdaderoken** [comment]
> We made some changes to the file handlers in v2.3.50, while they weren't specific to this issue, it might have solved them. Can you check if it's still an issue?

Dragging looks fine so far. I'll reopen this if it happens again :) Thank you!
