### ISSUE TITLE
Crash when using back button on mouse

### ISSUE THREAD

**Issue by SimonL888** [files-community/Files#10311]
### Description

If one uses the back-button on the mouse and (mostly when more tabs are open) the app crashes completely. 

### Steps To Reproduce

1. open app
2. open some taps
3. press back button on your mouse 
4. app crashes

### Files Version

Version: 2.3.12.0

### Windows Version

Windows 11 10.0.22000.1165

### Relevant Assets/Logs

```2022-10-27 15:11:00.7419|ERROR|AppUnhandledException|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.Uwp.Views.ColumnShellPage.Back_Click() + 0x1f2
   at Files.Uwp.Views.ColumnShellPage.CoreWindow_PointerPressed(CoreWindow, PointerEventArgs) + 0x7b
   at Microsoft.Toolkit.Uwp.UI.Controls.InAppNotificationOpeningEventHandler.Invoke(Object, InAppNotificationOpeningEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__22[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at Files!<BaseAddress>+0x1465943
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8
   at __Interop.ForwardComStubs.Stub_10[TThis](__ComObject, Int32) + 0x24
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x3d
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x75
   at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__22[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at Files!<BaseAddress>+0x1454480```

**Comment by Josh-65** [comment]
Can you see if this is an issue in the preview version? https://files.community/download/preview

**Comment by SimonL888** [comment]
Yes the problem is still there see logs from preview Version:

2022-10-28 09:36:14.2585|ERROR|AppUnhandledException|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IFrameMethods.Navigate(IObjectReference _obj, Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride)
   at Files.App.Views.ModernShellPage.NavigateToPath(String navigationPath, Type sourcePageType, NavigationArguments navArgs)
   at Files.App.Helpers.NavigationHelpers.OpenDirectory(String path, IShellPage associatedInstance, IEnumerable`1 selectItems, ShellLinkItem shortcutInfo, Boolean forceOpenInNewTab)
   at Files.App.Helpers.NavigationHelpers.OpenPath(String path, IShellPage associatedInstance, Nullable`1 itemType, Boolean openSilent, Boolean openViaApplicationPicker, IEnumerable`1 selectItems, String args, Boolean forceOpenInNewTab)
   at Files.App.Helpers.NavigationHelpers.OpenSelectedItems(IShellPage associatedInstance, Boolean openViaApplicationPicker)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by ThePython10110** [comment]
Works perfectly for me (Version: 2.3.12.0, OS Version: 10.0.19044.2192)
Then again, it might be specific to Windows 11.

**Comment by yaichenbaum** [comment]
Is this specific to the details layout?

**Comment by shapiromh** [comment]
I have the same error, and only run into it when using the "column" view. This applies if any tab is in column view, not necessarily the active tab.

**Comment by yaichenbaum** [comment]
Merging with #10109
