### ISSUE TITLE
Bug: Frequent app crash

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10337]
### Description

Details are provided below.
I noticed the app crashes more often than usual since the WinUI 3.

### Steps To Reproduce

I don't know in particular but it occurs mostly when navigating.
Also happens randomly when the app is in the background but not minimized.

Some scenarios include:
- Copying a file from a folder and navigating to a destination folder
- While using dual-pane view and navigating back and forth for a few minutes
- When switching tabs

Sometimes, after the error notification, the app would not actually crash yet until few more errors

### Steps to fix

- Prevent the crash

### Files Version

2.3.54.0 

### Windows Version

10.0.22623.875

### Relevant Assets/Logs

The `0x8000FFFF` exception
```Csharp
2022-10-29 21:56:21.3182|ERROR|AppUnhandledException|Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
	System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
2022-10-29 21:56:21.4374|ERROR|AppUnhandledException|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IFrameMethods.Navigate(IObjectReference _obj, Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride)
   at Files.App.Views.ModernShellPage.NavigateToPath(String navigationPath, Type sourcePageType, NavigationArguments navArgs)
   at Files.App.Helpers.NavigationHelpers.OpenDirectory(String path, IShellPage associatedInstance, IEnumerable`1 selectItems, ShellLinkItem shortcutInfo, Boolean forceOpenInNewTab)
   at Files.App.Helpers.NavigationHelpers.OpenPath(String path, IShellPage associatedInstance, Nullable`1 itemType, Boolean openSilent, Boolean openViaApplicationPicker, IEnumerable`1 selectItems, String args, Boolean forceOpenInNewTab)
   at Files.App.Helpers.NavigationHelpers.OpenSelectedItems(IShellPage associatedInstance, Boolean openViaApplicationPicker)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
```

The `0x8001010E` exception
```Csharp
2022-10-30 23:53:06.7866|ERROR|AppUnhandledException|A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD)))
	System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD)))
 ---> System.Runtime.InteropServices.COMException (0x8001010E): The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IWindowMethods.get_Content(IObjectReference _obj)
   at Files.App.MainWindow.EnsureWindowIsInitialized()
   at Files.App.MainWindow.InitializeApplication(AppActivationArguments activatedEventArgs)
   --- End of inner exception stack trace ---
   ```

**Comment by Josh-65** [comment]
Merging with #9921

**Comment by yaichenbaum** [comment]
This looks like a different issue

**Comment by verdaderoken** [comment]
> Merging with #9921

I think the `0x8001010E` exception is different from [#9921](https://github.com/files-community/Files/issues/9921) because the app does not actually crash and only sends a notification

**Comment by Josh-65** [comment]
Ah, just saw the COM (0x8000FFFF). Didnt think there was another one

**Comment by yaichenbaum** [comment]
The `0x8001010E` crash was resolved in `main`.
