### ISSUE TITLE
Bug: App crashing when spamming Alt+I

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10406]
### Description

I'm just messing around with alt key combinations when I found out that spamming Alt+I to open Settings would cause the app to crash with a COMException `0x80000019`. 

### Steps To Reproduce

1. Open Files
2. Spam Alt+I

### Steps to fix

- Prevent crash

### Files Version

2.3.58.0

### Windows Version

10.0.22623.875

### Relevant Assets/Logs

```cs
2022-11-05 07:08:20.3237|ERROR|AppUnhandledException|An async operation was not properly started. (0x80000019)
	System.Runtime.InteropServices.COMException (0x80000019): An async operation was not properly started. (0x80000019)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IContentDialogMethods.ShowAsync(IObjectReference _obj)
   at Files.App.Dialogs.SettingsDialog.ShowAsync()
   at Files.App.ViewModels.MainPageViewModel.OpenSettings()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
```

**Comment by yaichenbaum** [comment]
This appears to be a WinAppSdk issue, the alt shortcut should be disable when a content dialog is open.
