### ISSUE TITLE
Crash while moving iteams

### ISSUE THREAD

**Issue by newyork2003** [files-community/Files#10517]
### Description

The software crashes when I try to move items

### Steps To Reproduce

1- select several items
2- mve them to another folder or to a software
3-Files crash and close

### Steps to fix

- fix crash when moving several items

### Files Version

2.3.12

### Windows Version

Windows 10 Pro Version	21H2 Installed on	‎25/‎08/‎2022 OS build	19044.2251 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/10047511/debug_fulltrust.log)

```
2022-11-19 17:45:59.8002|WARN|HandleShellRecentItemsMessage|
	System.ComponentModel.Win32Exception (15): The system cannot find the drive specified.
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at Vanara.Windows.Shell.ShellLink.get_Target()
   at Files.FullTrust.MessageHandlers.RecentItemsHandler.<>c__DisplayClass11_0.<HandleShellRecentItemsMessage>b__0()
```

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by newyork2003** [comment]
It is on all versions
