### ISSUE TITLE
Files and folders click behaviour different between Home and any other view

### ISSUE THREAD

**Issue by ak5613** [files-community/Files#10603]
### Description

In Home view, a single click on any file or folder directly opens it, even though one click interaction is disabled in settings.
On the other hand, in any other view explored, files and folders do open on a double click, as intented.
This settings override only happens in Home view.

### Steps To Reproduce

1. Go to settings>Preferences tab>Files and folders
2. Make sure "open files on one click" and "open folders on one click" is disabled
3. Close settings
4. go to Home view
5. do a single click on any file or folder listed on this view

### Steps to fix

- Faulty behaviour happens when, in Home view, one click opens the file/folder instead of selecting it
- Correct action happens when, in Home view, one click on a file/folder selects it without opening it

### Files Version

Version : 2.3.12.0

### Windows Version

Windows 10 21H2

### Relevant Assets/Logs

debug.txt:

2022-11-29 23:18:34.0854|INFO|OnLaunched|App launched. Prelaunch: False
2022-11-29 23:18:35.4369|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-11-29 23:18:35.5311|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2022-11-29 23:18:35.8360|INFO|GetDrivesAsync|Drive added: E:\, CDRom
2022-11-29 23:18:35.9023|INFO|UpdateDrivesAsync|Adding cloud provider "Nextcloud" mapped to C:\Users\Martin\Nextcloud
2022-11-29 23:18:36.2052|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\Martin\OneDrive
2022-11-29 23:18:38.9570|INFO|CheckForUpdates|STORE: Checking for updates...
2022-11-29 23:18:39.5594|INFO|IsRunningOnArm|Running on ARM: False
2022-11-29 23:20:40.3952|INFO|IgnoreExceptions|Accès refusé.

	System.UnauthorizedAccessException: Accès refusé.

   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32, Void*) + 0xbe
   at __Interop.ForwardComStubs.Stub_3[TThis, TResult](__ComObject, Int32) + 0x37
   at Files.Uwp.App.<>c.<OnSuspending>b__94_1() + 0x2e
   at System.Action.Invoke() + 0x25
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action, ILogger) + 0x22

2022-11-29 23:20:50.1587|INFO|OnLaunched|App launched. Prelaunch: False
2022-11-29 23:20:50.9025|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-11-29 23:20:51.0969|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2022-11-29 23:20:51.1650|INFO|GetDrivesAsync|Drive added: E:\, CDRom
2022-11-29 23:20:51.3431|INFO|UpdateDrivesAsync|Adding cloud provider "Nextcloud" mapped to C:\Users\Martin\Nextcloud
2022-11-29 23:20:51.5131|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\Martin\OneDrive
2022-11-29 23:20:54.1403|INFO|CheckForUpdates|STORE: Checking for updates...
2022-11-29 23:20:54.1868|INFO|IsRunningOnArm|Running on ARM: False

debug_fulltrust.txt

2022-11-29 23:18:35.6385|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-11-29 23:18:35.6631|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-11-29 23:18:35.6642|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-11-29 23:18:35.6658|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-11-29 23:18:35.6883|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:18:35.9071|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-11-29 23:18:35.9852|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-11-29 23:18:36.2060|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-11-29 23:18:36.2915|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:18:36.3082|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-11-29 23:18:36.3549|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-11-29 23:18:36.7685|INFO|OnConnectionRequestReceived|Argument: GetNewContextMenuEntries
2022-11-29 23:18:36.8568|INFO|CheckQuickLookAvailability|QuickLook detected: False
2022-11-29 23:18:39.7823|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:42.1492|INFO|OnConnectionRequestReceived|Argument: GetFileAssociation
2022-11-29 23:18:43.0122|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:43.0264|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:43.0270|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:43.0358|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:43.0363|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:43.0720|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:43.0818|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:43.0824|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:43.1150|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:43.1178|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:43.1199|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:43.1207|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:43.1692|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:48.1355|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:18:52.8509|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:52.8733|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:52.8986|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:52.9001|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:52.9014|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:18:52.9024|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:09.6833|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:19:16.6783|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:16.6818|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:16.6851|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:16.6879|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:16.6922|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:16.6955|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:16.6969|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:16.7336|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:16.7360|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:16.8934|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:16.8956|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:16.8976|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:16.9001|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:19:19.1017|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:20:04.8453|INFO|OnConnectionRequestReceived|Argument: ShellRecentItems
2022-11-29 23:20:08.9922|WARN|HandleShellRecentItemsMessage|
	System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Vanara.PInvoke.Shell32.IShellLinkW.Resolve(HWND hwnd, SLR_FLAGS fFlags)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.FullTrust.MessageHandlers.RecentItemsHandler.<>c__DisplayClass11_0.<HandleShellRecentItemsMessage>b__0()
2022-11-29 23:20:40.4017|INFO|OnConnectionRequestReceived|Argument: Terminate
2022-11-29 23:20:51.0930|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-11-29 23:20:51.1232|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-11-29 23:20:51.1240|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-11-29 23:20:51.1246|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-11-29 23:20:51.1251|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:20:51.3467|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-11-29 23:20:51.3599|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-11-29 23:20:51.5134|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-11-29 23:20:51.7058|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:20:51.7121|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-11-29 23:20:51.7670|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-11-29 23:20:52.2579|INFO|CheckQuickLookAvailability|QuickLook detected: False
2022-11-29 23:20:52.3959|INFO|OnConnectionRequestReceived|Argument: GetNewContextMenuEntries
2022-11-29 23:20:54.8206|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.8679|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.8784|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.8797|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.8808|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.8814|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.8845|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.8858|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.8867|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.8872|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.8886|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.8954|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.9527|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.9552|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.9560|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.9597|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:54.9639|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:55.9156|INFO|OnConnectionRequestReceived|Argument: ShellRecentItems
2022-11-29 23:20:56.8414|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:56.8427|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:56.8446|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.1523|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.1533|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.2616|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.2641|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.2650|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.2657|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.2870|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.2891|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.2904|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.2911|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.2965|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.3011|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.4219|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.4228|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.4236|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.4243|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:20:59.4277|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:01.1484|INFO|OnConnectionRequestReceived|Argument: ShellRecentItems
2022-11-29 23:21:02.2118|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2126|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2132|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2147|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2159|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2166|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2174|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2181|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2194|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2199|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2869|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2924|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2935|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2942|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2949|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2956|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2963|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.2970|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.3701|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.3812|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.3861|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.3880|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:02.4333|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:04.6374|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:21:10.3115|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3131|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3145|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3156|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3170|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3184|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3207|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3246|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3277|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3294|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3329|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3364|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3393|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3412|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3427|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3439|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:10.3454|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-11-29 23:21:11.9691|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:21:30.1928|INFO|OnConnectionRequestReceived|Argument: ShellRecentItems
2022-11-29 23:21:32.0668|WARN|HandleShellRecentItemsMessage|
	System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Vanara.PInvoke.Shell32.IShellLinkW.Resolve(HWND hwnd, SLR_FLAGS fFlags)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.FullTrust.MessageHandlers.RecentItemsHandler.<>c__DisplayClass11_0.<HandleShellRecentItemsMessage>b__0()
2022-11-29 23:23:36.7909|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:30:07.8759|INFO|OnConnectionRequestReceived|Argument: ShellRecentItems
2022-11-29 23:30:09.5530|WARN|HandleShellRecentItemsMessage|
	System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Vanara.PInvoke.Shell32.IShellLinkW.Resolve(HWND hwnd, SLR_FLAGS fFlags)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.FullTrust.MessageHandlers.RecentItemsHandler.<>c__DisplayClass11_0.<HandleShellRecentItemsMessage>b__0()
2022-11-29 23:30:52.8603|INFO|OnConnectionRequestReceived|Argument: ShellRecentItems
2022-11-29 23:30:54.6132|WARN|HandleShellRecentItemsMessage|
	System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Vanara.PInvoke.Shell32.IShellLinkW.Resolve(HWND hwnd, SLR_FLAGS fFlags)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.FullTrust.MessageHandlers.RecentItemsHandler.<>c__DisplayClass11_0.<HandleShellRecentItemsMessage>b__0()
2022-11-29 23:39:27.4036|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:39:27.4047|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:39:27.4056|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:39:52.6914|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:39:52.6931|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-11-29 23:39:52.6957|INFO|OnConnectionRequestReceived|Argument: ShellFolder

**Comment by Josh-65** [comment]
Merging with #6074
