### ISSUE TITLE
Bundles are broken

### ISSUE THREAD

**Issue by DevanshR1123** [files-community/Files#10711]
### Description

The app crashes when clicking on any item in a bundle.

### Steps To Reproduce

1. Create a bundle
2. Add item/folders to the bundle
3. click on the items in the bundle

### Steps to fix

- eg. Fix crash that occurs when...
- eg. Correct action happens when clicking...

### Files Version

2.4.0.0

### Windows Version

Windows 10 22H2 19045.2311

### Relevant Assets/Logs

2022-12-14 22:50:13.9151|ERROR|AppUnhandledException|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.NavigationHelpers.OpenPath(String path, IShellPage associatedInstance, Nullable`1 itemType, Boolean openSilent, Boolean openViaApplicationPicker, IEnumerable`1 selectItems, String args, Boolean forceOpenInNewTab)
   at Files.App.ViewModels.Pages.YourHomeViewModel.BundlesViewModel_OpenPathEvent(Object sender, BundlesOpenPathEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)

**Comment by Josh-65** [comment]
2.4.1 is currently releasing which might fix this.

**Comment by yaira2** [comment]
This should be resolved in v2.4.1
