### ISSUE TITLE
Application crashed when entering WSL folder

### ISSUE THREAD

**Issue by vertigobo** [files-community/Files#10765]
### Description

The application crashed while I was browsing a Docker Desktop WSL folder.

### Steps To Reproduce

Unable to reproduce this behaviour every time. 

### Steps to fix

Stop the application from crashing.

### Files Version

Version: 2.4.2.0 OS Version: 10.0.19045.2364

### Windows Version

Windows 10 Pro 22H2

### Relevant Assets/Logs

2022-12-19 11:07:35.3463|ERROR|AppUnhandledException|Value cannot be null. (Parameter 'idList')
	System.ArgumentNullException: Value cannot be null. (Parameter 'idList')
   at Vanara.Windows.Shell.ShellItem.Open(PIDL idList)
   at Files.App.Shell.ShellFolderExtensions.GetShellItemFromPathOrPidl(String pathOrPidl)
   at Files.App.Filesystem.StorageItems.ShellStorageFile.GetFile(String path)
   at Files.App.Filesystem.StorageItems.ShellStorageFile.GetBasicProperties()
   at Files.App.Filesystem.StorageItems.ShellStorageFile.GetBasicPropertiesAsync()
   at Files.App.Filesystem.StorageEnumerators.UniversalStorageEnumerator.AddFileAsync(BaseStorageFile file, StorageFolderWithPath currentStorageFolder, CancellationToken cancellationToken)
   at Files.App.Filesystem.StorageEnumerators.UniversalStorageEnumerator.ListEntries(BaseStorageFolder rootFolder, StorageFolderWithPath currentStorageFolder, CancellationToken cancellationToken, Int32 countLimit, Func`2 intermediateAction, Dictionary`2 defaultIconPairs)
   at Files.App.ViewModels.ItemViewModel.<>c__DisplayClass150_0.<<EnumFromStorageFolderAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Files.App.ViewModels.ItemViewModel.EnumFromStorageFolderAsync(String path, ListedItem currentFolder, BaseStorageFolder rootFolder, StorageFolderWithPath currentStorageFolder, CancellationToken cancellationToken)
   at Files.App.ViewModels.ItemViewModel.EnumerateItemsFromStandardFolderAsync(String path, CancellationToken cancellationToken, LibraryItem library)
   at Files.App.ViewModels.ItemViewModel.RapidAddItemsToCollection(String path, LibraryItem library)
   at Files.App.ViewModels.ItemViewModel.RapidAddItemsToCollectionAsync(String path, String previousDir, Action postLoadCallback)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)

**Comment by QuaintMako** [comment]
Is this still an issue in v2.4.3 @vertigobo ?

**Comment by vertigobo** [comment]
I will be able to verify this issue on the new release as soon as it will be available in the microsoft store.

**Comment by yaira2** [comment]
@vertigobo I think this is fixed in v2.4.21, can you confirm?

**Comment by vertigobo** [comment]
Hi @yair100. Yes, it's fixed.
