### ISSUE TITLE
Bug: Files crashes when clicking the in-app update button

### ISSUE THREAD

**Issue by BlackbirdL** [files-community/Files#10789]
### Description

Files crashed after I click on "update", that's not the first time. 

My parameters : 
[Files_2.4.3.0.zip](https://github.com/files-community/Files/files/10276589/Files_2.4.3.0.zip)

### Steps To Reproduce

1. Open "Files"
2. Click on the button "Update"
![image](https://user-images.githubusercontent.com/121161350/208876471-ec8f893a-2f5e-4b71-99d5-c61dbc67998a.png)

### Steps to fix

- eg. Fix crash that occurs when clicking on "Update"

### Files Version

Version : 2.4.3.0

### Windows Version

Windows 11 22H2 22621.963

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10276671/debug.log)

**Comment by SOLIJA** [comment]
I am having the exact same issue.

Version: 2.4.2.0
Windows 11 22H2 22623.1037

<details>
  <summary>debug.log</summary>
  <p>
    2022-12-21 07:09:26.1970|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2022-12-21 07:09:26.9172|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-12-21 07:09:27.0338|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\joshu\OneDrive
2022-12-21 07:09:28.8067|INFO|CheckForUpdates|STORE: Checking for updates...
2022-12-21 07:09:29.5409|INFO|IsRunningOnArm|Running on ARM: False
2022-12-21 07:09:39.2736|INFO|CheckForUpdates|STORE: Update found.
2022-12-21 07:10:28.0294|ERROR|AppUnhandledException|Invalid window handle. (0x80070578)
Consider WindowNative, InitializeWithWindow
See https://aka.ms/cswinrt/interop#windows-sdk
	System.Runtime.InteropServices.COMException (0x80070578): Invalid window handle. (0x80070578)
Consider WindowNative, InitializeWithWindow
See https://aka.ms/cswinrt/interop#windows-sdk
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.Services.Store.IStoreContextMethods.RequestDownloadAndInstallStorePackageUpdatesAsync(IObjectReference _obj, IEnumerable`1 storePackageUpdates)
   at Files.App.ServicesImplementation.UpdateService.DownloadAndInstall()
   at Files.App.ServicesImplementation.UpdateService.DownloadUpdates()
   at Files.App.Views.ModernShellPage.<InitToolbarCommands>b__61_30()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
2022-12-21 07:10:31.3063|INFO|OnLaunched|App launched. Launch args type: ToastNotificationActivatedEventArgs
2022-12-21 07:10:31.6631|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\joshu\OneDrive
2022-12-21 07:10:31.6877|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-12-21 07:10:33.5325|INFO|CheckForUpdates|STORE: Checking for updates...
2022-12-21 07:10:33.9674|INFO|CheckForUpdates|STORE: Update found.
2022-12-21 07:10:48.1473|ERROR|AppUnhandledException|Invalid window handle. (0x80070578)
Consider WindowNative, InitializeWithWindow
See https://aka.ms/cswinrt/interop#windows-sdk
	System.Runtime.InteropServices.COMException (0x80070578): Invalid window handle. (0x80070578)
Consider WindowNative, InitializeWithWindow
See https://aka.ms/cswinrt/interop#windows-sdk
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.Services.Store.IStoreContextMethods.RequestDownloadAndInstallStorePackageUpdatesAsync(IObjectReference _obj, IEnumerable`1 storePackageUpdates)
   at Files.App.ServicesImplementation.UpdateService.DownloadAndInstall()
   at Files.App.ServicesImplementation.UpdateService.DownloadUpdates()
   at Files.App.Views.ModernShellPage.<InitToolbarCommands>b__61_30()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
2022-12-21 07:10:51.6746|INFO|OnLaunched|App launched. Launch args type: ToastNotificationActivatedEventArgs
2022-12-21 07:10:52.0266|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\joshu\OneDrive
2022-12-21 07:10:52.0636|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-12-21 07:10:53.7724|INFO|CheckForUpdates|STORE: Checking for updates...
2022-12-21 07:10:54.2264|INFO|CheckForUpdates|STORE: Update found.
2022-12-21 07:12:38.2739|INFO|OnActivated|App activated. Activated args type: ProtocolActivatedEventArgs
2022-12-21 07:12:39.0345|INFO|IsRunningOnArm|Running on ARM: False
2022-12-21 07:13:34.5680|INFO|OnActivated|App activated. Activated args type: ProtocolActivatedEventArgs
  </p>
</details>

**Comment by yaira2** [comment]
What happens if you update through the store?

**Comment by SOLIJA** [comment]
> What happens if you update through the store?

I updated, and the button is gone.

**Comment by yaira2** [comment]
The Store apis aren't the most reliable, it works most of the time, but there will be random issues like this. You can try switching to the sideload version which seems to have more reliable updates or you can update manually through the Store if this happens again.

**Comment by BlackbirdL** [comment]
I juste have forger to notice that I am on a preview version.Sent from Android deviceLe 21 déc. 2022 15:59, yair100 ***@***.***> a écrit :
The Store apis aren't the most reliable, it works most of the time, but there will be random issues like this. You can try switching to the sideload version has more reliable updates or you can update manually through the Store if this happens again.

**Comment by yaira2** [comment]
Thank you for the report, we identified the issue and we're working on a fix. Please note that the next update will still have this issue, but the following update should work as expected.

**Comment by BlackbirdL** [comment]
‌Ok thank you.
 

De : "yair100"
A : "files-community/Files" ,"BlackbirdL" ,"Author"
Envoyé: mercredi 21 Décembre 2022 21:20
Objet : Re: [files-community/Files] Bug: Files crashes when clicking the in-app update button (Issue #10789)
 

 

Thank you for the report, we identified the issue and we're working on a fix. Please note that the next update will still have this issue, but the following update should work as expected.
