### ISSUE TITLE
Bug: Changing file permission for multiple files simultaneously crashes app

### ISSUE THREAD

**Issue by jh961202** [files-community/Files#10870]
### Description

When setting permission ( readonly, etc. ) with Files' built-in properties dialog, Files will crash and exit after clicking OK button to apply settings.
This only happens when multiple items were chosen ( >= 2 items ), but no problems when dealing with single one item.

However, permissions of selected items will still be set properly even though Files crashes.

### Steps To Reproduce

1. Go to any path that contains multiple items.
2. Select multiple items ( >=2 items ), and click "Properties" on the menu bar or context menu to bring out properties dialog
3. Modify any kind of permission ( noo matter the type ) and click OK.
4. See the error

### Steps to fix

Looks like this is a standalone issue, no prerequisites should be accomplished before dealing with this one.
Log file is able to collect relevant error ( see the following )

### Files Version

Version： 2.4.8.0 OS Version: 10.0.22621.963

### Windows Version

Windows 11 22H2 22621.963

### Relevant Assets/Logs

2022-12-29 10:48:46.8620|INFO|CheckForUpdates|STORE: Checking for updates...
2022-12-29 10:48:48.2666|INFO|IsRunningOnArm|Running on ARM: False
2022-12-29 10:49:10.3062|ERROR|AppUnhandledException|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Views.PropertiesGeneral.SaveChangesAsync(ListedItem item)
   at Files.App.Views.Properties.OKButton_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)

**Comment by hecksmosis** [comment]
Can confirm this is an issue

**Comment by hecksmosis** [comment]
I'll look into it

**Comment by hecksmosis** [comment]
@yair100 can you approve this? (I've already resolved it)
