### ISSUE TITLE
Pasting files in some folders

### ISSUE THREAD

**Issue by Sibelius58** [files-community/Files#11000]
### Description

I was unable to check whether the problem is already known, so I submit it here. Files fails to paste files (after copying or cutting them) into certain folders, specifically, as far as I have verified, Start Menu folders in the locations 

C:\ProgramData\Microsoft\Windows\Start Menu
C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu

Pasting is possible only if you launch the programme as administrator (right-clickng the icon)

### Steps To Reproduce

Copy or cut an existing shortcut in one of the two folders above and then try pasting it in a subfolder

### Steps to fix

Start Files as administrator

### Files Version

2.4.21.0

### Windows Version

Windows 11  22H2

### Relevant Assets/Logs

2023-01-13 15:03:37.3289|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 15:03:37.9924|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 15:03:38.0273|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 15:03:38.1029|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 15:03:38.1336|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 15:03:39.7098|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 15:04:15.4329|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 15:04:15.8026|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 15:04:15.8346|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 15:04:15.8718|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 15:04:15.8970|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 15:04:17.0764|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 15:04:39.4104|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 15:05:17.2796|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 15:05:17.6193|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 15:05:17.6502|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 15:05:17.6917|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 15:05:17.7144|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 15:05:18.8861|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 15:05:24.0943|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 15:06:13.8583|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 15:06:14.1788|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 15:06:14.2099|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 15:06:14.2500|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 15:06:14.2684|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 15:06:15.4458|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 15:21:25.3054|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 15:21:25.8087|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 15:21:25.8429|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 15:21:25.9019|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 15:21:25.9203|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 15:21:28.4246|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 15:40:02.2047|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 15:40:02.5385|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 15:40:02.5704|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 15:40:02.6146|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 15:40:02.6352|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 15:40:04.1141|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 15:40:06.7776|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 15:44:02.9689|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 15:44:03.2859|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 15:44:03.3178|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 15:44:03.3831|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 15:44:03.4134|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 15:44:04.4709|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 15:44:11.8682|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 15:45:06.8059|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 15:45:07.1305|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 15:45:07.1594|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 15:45:07.2020|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 15:45:07.2232|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 15:45:08.2467|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 15:46:29.3205|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 15:46:29.6881|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 15:46:29.7255|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 15:46:29.7881|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 15:46:29.8060|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 15:46:30.9393|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 15:46:32.9292|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 15:47:37.1664|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 15:47:37.5081|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 15:47:37.5354|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 15:47:37.5994|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 15:47:37.6224|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 15:47:40.4240|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 15:47:46.8186|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 15:49:07.7783|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 15:49:08.1061|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 15:49:08.1356|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 15:49:08.1946|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 15:49:08.2131|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 15:49:09.3670|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 15:49:10.5019|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 15:50:47.5604|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 15:50:47.8832|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 15:50:47.9140|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 15:50:47.9550|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 15:50:47.9748|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 15:50:49.3120|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 15:50:50.1972|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 16:08:21.6423|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:08:22.2041|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:08:22.2364|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:08:22.2863|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:08:22.3065|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:08:23.5841|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:09:01.2959|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 16:13:06.3840|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:13:06.7143|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:13:06.7516|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:13:06.7965|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:13:06.8194|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:13:09.5467|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:13:14.9931|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 16:15:44.3751|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:15:44.7078|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:15:44.7394|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:15:44.8040|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:15:44.8249|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:15:53.2193|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:15:55.0218|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 16:17:33.8919|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:17:34.4341|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:17:34.4605|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:17:34.5073|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:17:34.5243|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:17:37.5717|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:17:55.5832|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 16:20:20.0092|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:20:20.6018|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:20:20.6146|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:20:20.7015|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:20:20.7206|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:20:22.1698|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:20:24.9234|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 16:22:34.0997|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:22:34.4793|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:22:34.4880|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:22:34.5583|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:22:34.5774|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:22:37.3732|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:22:38.2842|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 16:32:26.8022|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:32:27.3242|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:32:27.3535|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:32:27.3967|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:32:27.4138|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:33:55.5788|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:33:55.9135|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:33:55.9456|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:33:55.9895|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:33:56.0101|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:34:04.6422|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:41:37.6917|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:41:38.0574|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:41:38.0875|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:41:38.1286|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:41:38.1469|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:41:47.6374|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:41:55.8784|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 16:42:57.5011|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:42:57.8641|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:42:57.8962|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:42:57.9322|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:42:57.9495|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:42:59.1120|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:43:07.2423|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 16:45:21.4359|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:45:21.7775|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:45:21.8060|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:45:21.8524|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:45:21.8700|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:45:24.7406|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:53:26.5048|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:53:27.0014|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:53:27.0331|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:53:27.0826|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:53:27.0999|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:53:29.5506|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:53:32.1156|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 16:56:01.0901|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:56:01.4360|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:56:01.4693|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:56:01.5285|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:56:01.5494|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:56:02.9650|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:56:04.3751|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 16:56:37.7633|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 16:56:38.0910|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:56:38.1214|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:56:38.1672|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:56:38.1876|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:56:39.4014|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:56:40.9785|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 16:57:51.8534|INFO|OnLaunched|App launched. Launch args type: ProtocolActivatedEventArgs
2023-01-13 16:57:52.1746|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 16:57:52.2137|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 16:57:52.2513|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 16:57:52.2721|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 16:57:54.7896|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 16:57:56.8524|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 17:01:36.2736|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 17:01:36.5858|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 17:01:36.6210|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 17:01:36.6573|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 17:01:36.6753|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 17:01:39.1469|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 17:10:09.7758|INFO|IsRunningOnArm|Running on ARM: False
2023-01-13 17:13:43.6468|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 17:13:44.2156|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 17:13:44.2627|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 17:13:44.2980|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 17:13:44.3157|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 17:13:45.6920|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-13 17:17:09.8939|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-13 17:17:10.2362|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-01-13 17:17:10.2639|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-13 17:17:10.3242|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-13 17:17:10.3422|INFO|GetDrivesAsync|Drive added: I:\, Removable
2023-01-13 17:17:12.9056|INFO|CheckForUpdates|STORE: Checking for updates...

**Comment by Josh-65** [comment]
Merging with #10422
These folder require admin to do.

**Comment by yaira2** [comment]
@Sibelius58 at the moment we don't have a prompt when an action requires admin privileges but in the meantime, you can work around this by running Files as admin.

**Comment by yaira2** [comment]
This issue is resolved in our dev branch and will be included in the next release.
