### ISSUE TITLE
Crash when HTML file is selected

### ISSUE THREAD

**Issue by ArtexJay** [files-community/Files#11042]
### Description

It's practically impossible to manage HTML files that I have downloaded on my device. Every time I select an HTML file it causes the Files app to crash. A way to avoid this is to disable or turn off the preview pane.

### Steps To Reproduce

1. Enable Preview Pane
2. Get an HTML file
3. Select the HTML file
4. Files App crashes

### Steps to fix

Disable Preview Pane, then it doesn't crash.

### Files Version

Version: 2.4.21.0 OS Version: 10.0.25276.1000

### Windows Version

Windows 11 22h2

### Relevant Assets/Logs

```
2023-01-19 17:03:44.1860|ERROR|AppUnhandledException|Value does not fall within the expected range.
	System.ArgumentException: Value does not fall within the expected range.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IWebView2Methods.NavigateToString(IObjectReference _obj, String htmlContent)
   at Files.App.UserControls.FilePreviews.HtmlPreview.WebViewControl_Loaded(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
```

**Comment by ferrariofilippo** [comment]
Already known bug #10280
