### ISSUE TITLE
Dual Pane Mode Frozen

### ISSUE THREAD

**Issue by bewitchingraven** [files-community/Files#11070]
### Description

I prefer dual pane mode and set it as soon as Files opened. It continues to freeze despite forcing end process. And now it told me 3 times that something went wrong before it completely crashed. 

### Steps To Reproduce

1. Open Files
2. Open external drive
3. Open graphic file
4. Select graphics to move
5. Files crashed

### Steps to fix

Turned off dual pane mode, seemed to be working, crashed when I tried to rename files. I will reset defaults and see what happens. 
e.g.

### Files Version

Version: 2.4.21.0 OS Version: 10.0.19045.2546

### Windows Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎1/‎12/‎2023 OS build	19045.2546 Experience	Windows Feature Experience Pack 120.2212.4190.0

### Relevant Assets/Logs

2023-01-24 22:02:48.0946|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-24 22:02:49.3234|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\allen\Creative Cloud Files
2023-01-24 22:02:49.4152|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-24 22:02:49.6634|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-24 22:02:49.7445|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2023-01-24 22:02:51.6888|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\allen\OneDrive
2023-01-24 22:02:53.8781|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-24 22:03:11.4451|INFO|IsRunningOnArm|Running on ARM: False
2023-01-24 22:10:35.6380|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-24 22:10:36.5514|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\allen\Creative Cloud Files
2023-01-24 22:10:36.8014|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-24 22:10:36.9521|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-24 22:10:37.1075|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2023-01-24 22:10:38.8824|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\allen\OneDrive
2023-01-24 22:10:42.3039|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-24 22:10:45.4461|INFO|IsRunningOnArm|Running on ARM: False
2023-01-24 22:11:05.2054|INFO|IgnoreExceptions|Error HRESULT E_FAIL has been returned from a call to a COM component.
	System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.DataTransfer.IClipboardStaticsMethods.Flush(IObjectReference _obj)
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger)
2023-01-24 22:11:09.7382|ERROR|AppUnhandledException|Value does not fall within the expected range.
	System.ArgumentException: Value does not fall within the expected range.
   at ABI.Microsoft.UI.Xaml.Input.IFocusManagerStaticsMethods.GetFocusedElement(IObjectReference _obj, XamlRoot xamlRoot)
   at Files.App.Views.LayoutModes.DetailsLayoutBrowser.ItemManipulationModel_FocusFileListInvoked(Object sender, EventArgs e)
   at Files.App.Views.ModernShellPage.set_IsCurrentInstance(Boolean value)
   at Files.App.Views.PaneHolderPage.set_ActivePane(IShellPage value)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
2023-01-24 22:11:14.0430|INFO|OnLaunched|App launched. Launch args type: ToastNotificationActivatedEventArgs
2023-01-24 22:11:14.9498|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\allen\Creative Cloud Files
2023-01-24 22:11:14.9809|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-24 22:11:15.2972|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\allen\OneDrive
2023-01-24 22:11:15.3233|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-24 22:11:15.5328|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2023-01-24 22:11:23.8087|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-24 22:15:15.6314|INFO|IgnoreExceptions|Error HRESULT E_FAIL has been returned from a call to a COM component.
	System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.DataTransfer.IClipboardStaticsMethods.Flush(IObjectReference _obj)
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger)
2023-01-24 22:17:46.3427|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-24 22:17:47.0616|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\allen\Creative Cloud Files
2023-01-24 22:17:47.2338|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-24 22:17:47.3882|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-24 22:17:47.4532|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2023-01-24 22:17:48.8130|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\allen\OneDrive
2023-01-24 22:17:51.4903|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-24 22:17:59.4926|INFO|IsRunningOnArm|Running on ARM: False
2023-01-24 22:20:14.6555|ERROR|AppUnhandledException|The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
	System.Runtime.InteropServices.COMException (0x80010105): The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
2023-01-24 22:20:14.8139|ERROR|AppUnhandledException|The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
	System.Runtime.InteropServices.COMException (0x80010105): The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
2023-01-24 22:20:14.9414|ERROR|AppUnhandledException|The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
	System.Runtime.InteropServices.COMException (0x80010105): The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
2023-01-24 22:20:31.1705|ERROR|AppUnhandledException|The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
	System.Runtime.InteropServices.COMException (0x80010105): The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
2023-01-24 22:20:31.2787|ERROR|AppUnhandledException|The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
	System.Runtime.InteropServices.COMException (0x80010105): The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
2023-01-24 22:20:34.6216|ERROR|AppUnhandledException|The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
	System.Runtime.InteropServices.COMException (0x80010105): The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
2023-01-24 22:23:15.8036|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-24 22:23:16.5168|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\allen\Creative Cloud Files
2023-01-24 22:23:16.7331|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-24 22:23:16.9254|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-24 22:23:17.0141|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2023-01-24 22:23:18.5142|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\allen\OneDrive
2023-01-24 22:23:21.3063|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-24 22:24:49.7018|INFO|IsRunningOnArm|Running on ARM: False
2023-01-24 22:26:06.4302|ERROR|AppUnhandledException|The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
	System.Runtime.InteropServices.COMException (0x80010105): The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
2023-01-24 22:26:06.5956|ERROR|AppUnhandledException|The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
	System.Runtime.InteropServices.COMException (0x80010105): The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
2023-01-24 22:26:08.4031|ERROR|AppUnhandledException|The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
	System.Runtime.InteropServices.COMException (0x80010105): The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
2023-01-24 22:27:19.9409|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-24 22:27:20.6790|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\allen\Creative Cloud Files
2023-01-24 22:27:20.8990|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-24 22:27:21.2012|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-24 22:27:21.2870|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2023-01-24 22:27:22.0993|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\allen\OneDrive
2023-01-24 22:27:23.1087|INFO|IsRunningOnArm|Running on ARM: False
2023-01-24 22:27:30.0071|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-24 22:28:40.8533|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-24 22:28:41.5623|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\allen\Creative Cloud Files
2023-01-24 22:28:41.6104|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-24 22:28:41.8767|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-24 22:28:41.9449|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2023-01-24 22:28:43.2420|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\allen\OneDrive
2023-01-24 22:28:46.0690|INFO|CheckForUpdates|STORE: Checking for updates...

**Comment by Josh-65** [comment]
Can you see if this is an issue in the preview version? https://files.community/download
