### ISSUE TITLE
Whenever I try to right click an image, I get an error and Files crashes.

### ISSUE THREAD

**Issue by thernus** [files-community/Files#11104]
### Description

When I try to right click an image or video (any media file), I get the following error: `Excepting processing message 0xc0000005 - Unexpected parameters`.

When I press Ok, Files closes.

### Steps To Reproduce

1. Right click on any media file (video, photo)

https://user-images.githubusercontent.com/55776911/215304775-d266bacf-4e21-49d3-93dd-2b10ab2a253a.mp4

### Steps to fix

- Fix crash that occurs when right clicking on media (Windows 10)

### Files Version

Version 2.4.25.0

### Windows Version

Windows 10 Home 21H2 19044.2486

### Log file

2023-01-28 00:52:16.9935|INFO|OnLaunched|App launched. Launch args type: ProtocolActivatedEventArgs
2023-01-28 00:52:17.2846|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 00:52:17.3109|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 00:52:17.3311|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 00:52:18.3467|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 00:52:18.8902|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 17:16:49.8331|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-28 17:16:50.1858|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 17:16:50.2027|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 17:16:50.2260|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 17:16:51.6520|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 17:16:54.4808|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 17:17:42.8307|INFO|OnActivated|App activated. Activated args type: ProtocolActivatedEventArgs
2023-01-28 20:34:29.3569|INFO|OnLaunched|App launched. Launch args type: ProtocolActivatedEventArgs
2023-01-28 20:34:29.8680|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 20:34:29.8990|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 20:34:29.9213|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 20:34:29.4062|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-28 20:34:29.9577|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 20:34:29.9043|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 20:34:29.9769|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 20:34:31.1165|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 20:34:31.3500|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 20:34:31.6138|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 20:34:34.6215|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 20:38:19.3744|INFO|OnActivated|App activated. Activated args type: ProtocolActivatedEventArgs
2023-01-28 21:20:17.1983|INFO|OnActivated|App activated. Activated args type: ProtocolActivatedEventArgs
2023-01-28 21:22:07.0648|INFO|OnActivated|App activated. Activated args type: ProtocolActivatedEventArgs
2023-01-28 21:23:04.5694|INFO|OnActivated|App activated. Activated args type: ProtocolActivatedEventArgs
2023-01-28 21:40:08.6680|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-28 21:40:08.9950|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 21:40:09.0153|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 21:40:09.0501|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 21:40:10.4068|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 21:40:19.5896|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 22:06:45.2213|INFO|OnActivated|App activated. Activated args type: ProtocolActivatedEventArgs
2023-01-28 22:10:30.9908|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-28 22:10:31.3138|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 22:10:31.3420|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 22:10:31.3618|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 22:10:32.6458|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 22:10:34.0426|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 22:10:43.0568|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-28 22:10:43.3529|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 22:10:43.3829|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 22:10:43.4046|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 22:10:44.7911|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 22:10:45.9113|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 22:13:30.1626|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-28 22:13:30.4930|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 22:13:30.5037|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 22:13:30.5410|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 22:13:31.8026|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 22:13:33.5529|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 22:14:02.8461|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-28 22:14:03.1622|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 22:14:03.1848|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 22:14:03.2058|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 22:14:04.4637|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 22:14:05.2390|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 22:14:56.0783|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-28 22:14:56.3560|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 22:14:56.3811|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 22:14:56.4022|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 22:14:57.6228|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 22:14:58.5984|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 22:16:44.1007|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-28 22:16:44.3661|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 22:16:44.3947|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 22:16:44.4162|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 22:16:45.8354|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 22:16:47.1840|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 22:16:52.8564|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-28 22:16:53.1325|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 22:16:53.1654|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 22:16:53.1856|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 22:16:54.5217|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 22:16:54.6349|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 22:17:40.5661|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-28 22:17:40.8840|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 22:17:40.9109|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 22:17:40.9287|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 22:17:42.4244|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 22:17:42.9697|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 22:22:35.4574|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-28 22:22:35.7354|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 22:22:35.7641|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 22:22:35.7843|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 22:22:37.2160|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 22:22:37.6640|INFO|IsRunningOnArm|Running on ARM: False
2023-01-28 22:24:07.4136|INFO|OnActivated|App activated. Activated args type: ProtocolActivatedEventArgs
2023-01-28 22:25:42.9912|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-01-28 22:25:43.3323|INFO|UpdateDrivesAsync|Adding cloud provider "Creative Cloud Files" mapped to C:\Users\Josh\Creative Cloud Files
2023-01-28 22:25:43.3592|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-01-28 22:25:43.3802|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-01-28 22:25:45.2170|INFO|CheckForUpdates|STORE: Checking for updates...
2023-01-28 22:25:48.8130|WARN|ListRecentFolders|Error HRESULT E_FAIL has been returned from a call to a COM component.
	System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Load(String pszFileName, Int32 dwMode)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Vanara.Windows.Shell.ShellLink..ctor(String linkFile, LinkResolution resolveFlags, HWND window, TimeSpan timeOut)
   at Files.App.Filesystem.RecentItems.ListRecentFolders()
2023-01-28 22:25:54.6333|INFO|OnActivated|App activated. Activated args type: ProtocolActivatedEventArgs
2023-01-28 22:25:57.1967|INFO|IsRunningOnArm|Running on ARM: False

**Comment by Josh-65** [comment]
For future issue UPLOAD the log file. Do not copy and paste the contents.

**Comment by SteveWorkshop** [comment]
same problem

**Comment by xIUPITERx** [comment]
> However, using ShellExView I was able to find the culprit. A Microsoft Context Menu Shell Extension called "Play to menu".
> By disabling said extension (again via ShellExView), the issue is resolved. I hope this helps.

Do you know what the "play to menu" entry does?

**Comment by Josh-65** [comment]
I think it shows devices that media files can be sent/played too in the cast sub menu
