### ISSUE TITLE
Crash when trying to create a new tag in new tags UI

### ISSUE THREAD

**Issue by MalteTasler** [files-community/Files#11321]
### Description

Files Preview (4.35) crashes when trying to create a new tag, as soon as I start typing the name for the new tag.

debug:

2023-02-16 10:29:16.0409|ERROR|AppUnhandledException|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.SettingsPages.Advanced.IsNameValid(String name)
   at Files.App.SettingsPages.Advanced.NewTagTextBox_TextChanged(Object sender, TextChangedEventArgs e)
   at ABI.Microsoft.UI.Xaml.Controls.TextChangedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)

### Steps To Reproduce

1. Go to the tags  UI in settings
2. Click "new"
3. Start typing the name

### Steps to fix

not been able to fix yet

### Files Version

2.4.35.0

### Windows Version

Windows 11 22H2 Build 22621.1194

### Log file

2023-02-16 10:29:16.0409|ERROR|AppUnhandledException|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.SettingsPages.Advanced.IsNameValid(String name)
   at Files.App.SettingsPages.Advanced.NewTagTextBox_TextChanged(Object sender, TextChangedEventArgs e)
   at ABI.Microsoft.UI.Xaml.Controls.TextChangedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
[filetags.db.txt](https://github.com/files-community/Files/files/10754339/filetags.db.txt)

   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)

**Comment by MalteTasler** [comment]
added the filetagsdb if that might help

**Comment by ferrariofilippo** [comment]
Will be fixed with #11320. There was a missing null-check

**Comment by ferrariofilippo** [comment]
FYI @yair100 ~I can open a separate PR to fix that (just need to add a `?`)~ I think it would be better if you could hotfix that:
at `Files.App.SettingsPage.Advanced.IsNameValid()`

                    return !(
				string.IsNullOrWhiteSpace(name) ||
				name.StartsWith('.') ||
				name.EndsWith('.') ||
				(name != editingTag?.Tag.Name && ViewModel.Tags.Any(tag => name == tag.Tag.Name))
			);

`name != editingTag?TagName.Name`

**Comment by ferrariofilippo** [comment]
@MalteTasler here's a workaround you can use in the meantime:
- Start editing a tag
- Cancel edit
- Now you should be able to create a tag

**Comment by yaira2** [comment]
@ferrariofilippo thanks for the fix!

**Comment by MalteTasler** [comment]
Thankyou!
