### ISSUE TITLE
Bug: Renaming a file caused it to disappear and Files to hang

### ISSUE THREAD

**Issue by rafaskb** [files-community/Files#11779]
### Description

I'm recording videos and saving them into a folder (which is currently open in Files), both in .mkv and .mp4 formats.
I then delete the .mkv files and rename the .mp4 ones to the appropriate name.

Not always, but sometimes, the file disappears from the listing, and Files becomes unresponsive.
Closing Files shows the popup "something went wrong with Files, click here to report the issue".

### Steps To Reproduce

The bug is inconsistent, as it doesn't happen all the time, but here it goes.
I'm not sure which of these steps are relevant, but this is what I did to cause the bug.

1. Open a folder in Files.
2. Create a new file in this folder externally.
3. Rename such file in Files.
4. The file **might** disappear, causing Files to hang.

### Requirements

- eg. Fix file disappearing after being renamed.

### Files Version

Files version 2.4.40.0, OS version 2.4.40.0

### Windows Version

Windows 10 Pro Version, 21H2, OS build 19044.2728

### Log file

[debug.log](https://github.com/files-community/Files/files/11019406/debug.log)

The error being reported here happened at "2023-03-20 11:33:34.2133"
```
2023-03-20 11:33:34.2133|ERROR|AppUnhandledException|The operation identifier is not valid. (0x800710DD)
	System.Runtime.InteropServices.COMException (0x800710DD): The operation identifier is not valid. (0x800710DD)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IWindowMethods.get_Bounds(IObjectReference _obj)
   at Files.App.Views.PaneHolderPage.get_IsMultiPaneEnabled()
   at Files.App.Views.MainPage.UpdateNavToolbarProperties()
   at Files.App.Views.MainPage.PaneHolder_PropertyChanged(Object sender, PropertyChangedEventArgs e)
   at Files.App.Views.PaneHolderPage.set_ActivePane(IShellPage value)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
   ```

**Comment by yaira2** [comment]
I can't reproduce this in the latest preview build, can you see if it fixed the issue for you? https://files.community/download/preview

**Comment by yaira2** [comment]
@rafaskb

**Comment by rafaskb** [comment]
Tested it on 2.4.66.0, seems to be fixed 😁
