### ISSUE TITLE
Recycle Bin not showing 

### ISSUE THREAD

**Issue by lico9182** [files-community/Files#12384]
### Description

Hi Developer/Josh65, i don't know if i'm just missing a setting in Files, or if it that the Recycle Bin can't be accessed via the app, great file manager software thanks for creating it, best regards L

### Steps To Reproduce

To add the Recycle Bin for Windows 11 os

### Requirements

There's are no crashes or errors, i just don't see how to access the Windows Recycle Bin from inside the Files app

### Files Version

Windows 11 Pro 22H2 22621.1702

### Windows Version

2.4.71.0

### Log file

2023-05-17 15:52:19.8412|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-05-17 15:52:20.7423|Information|Adding cloud provider "OneDrive" mapped to C:\Users\livio\OneDrive
2023-05-17 15:52:26.6916|Information|Drive added: C:\, Fixed
2023-05-17 15:52:26.9013|Information|Drive added: D:\, Removable
2023-05-17 15:52:27.4800|Information|Drive added: D:\
2023-05-17 15:52:34.4423|Information|SIDELOAD: Checking for updates...
2023-05-17 15:52:35.3232|Information|SIDELOAD: Current Package Name: Files
2023-05-17 15:52:35.3355|Information|SIDELOAD: Remote Package Name: Files
2023-05-17 15:52:35.3543|Information|SIDELOAD: Current Version: 2.4.71.0
2023-05-17 15:52:35.3673|Information|SIDELOAD: Remote Version: 2.4.71.0
2023-05-17 15:52:35.3933|Warning|SIDELOAD: Update not found.
2023-05-17 15:52:50.9169|Warning|System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Load(String pszFileName, Int32 dwMode)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Filesystem.RecentItems.<>c__DisplayClass14_1.<ListRecentFoldersAsync>b__2()
2023-05-17 15:53:13.4819|Warning|System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Load(String pszFileName, Int32 dwMode)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Filesystem.RecentItems.<>c__DisplayClass14_1.<ListRecentFoldersAsync>b__2()
2023-05-17 15:54:54.7848|Warning|System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Load(String pszFileName, Int32 dwMode)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Filesystem.RecentItems.<>c__DisplayClass14_1.<ListRecentFoldersAsync>b__2()
2023-05-17 15:55:11.9424|Information|Running on ARM: False
2023-05-17 15:57:15.7184|Warning|System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Load(String pszFileName, Int32 dwMode)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Filesystem.RecentItems.<>c__DisplayClass14_1.<ListRecentFoldersAsync>b__2()
2023-05-17 15:59:21.0381|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-05-17 15:59:21.5003|Information|Adding cloud provider "OneDrive" mapped to C:\Users\livio\OneDrive
2023-05-17 15:59:24.2513|Information|Drive added: C:\, Fixed
2023-05-17 15:59:24.3845|Information|Drive added: D:\, Removable
2023-05-17 15:59:24.8954|Information|Drive added: D:\
2023-05-17 15:59:31.0948|Information|SIDELOAD: Checking for updates...
2023-05-17 15:59:31.8113|Information|SIDELOAD: Current Package Name: Files
2023-05-17 15:59:31.8238|Information|SIDELOAD: Remote Package Name: Files
2023-05-17 15:59:31.8403|Information|SIDELOAD: Current Version: 2.4.71.0
2023-05-17 15:59:31.8584|Information|SIDELOAD: Remote Version: 2.4.71.0
2023-05-17 15:59:31.8784|Warning|SIDELOAD: Update not found.
2023-05-17 15:59:36.8245|Information|Running on ARM: False
2023-05-17 16:03:15.5546|Warning|System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Load(String pszFileName, Int32 dwMode)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Filesystem.RecentItems.<>c__DisplayClass14_1.<ListRecentFoldersAsync>b__2()
2023-05-17 16:06:05.7486|Warning|System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Load(String pszFileName, Int32 dwMode)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Filesystem.RecentItems.<>c__DisplayClass14_1.<ListRecentFoldersAsync>b__2()
2023-05-17 16:10:53.7340|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-05-17 16:10:54.1942|Information|Adding cloud provider "OneDrive" mapped to C:\Users\livio\OneDrive
2023-05-17 16:10:57.4368|Information|Drive added: C:\, Fixed
2023-05-17 16:10:57.5674|Information|Drive added: D:\, Removable
2023-05-17 16:10:58.0180|Information|Drive added: D:\
2023-05-17 16:11:04.4398|Information|SIDELOAD: Checking for updates...
2023-05-17 16:11:05.2860|Information|SIDELOAD: Current Package Name: Files
2023-05-17 16:11:05.2952|Information|SIDELOAD: Remote Package Name: Files
2023-05-17 16:11:05.3039|Information|SIDELOAD: Current Version: 2.4.71.0
2023-05-17 16:11:05.3138|Information|SIDELOAD: Remote Version: 2.4.71.0
2023-05-17 16:11:05.3272|Warning|SIDELOAD: Update not found.
2023-05-17 16:17:48.0805|Information|Running on ARM: False
2023-05-17 16:20:34.9443|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-05-17 16:20:35.5739|Information|Adding cloud provider "OneDrive" mapped to C:\Users\livio\OneDrive
2023-05-17 16:20:39.1263|Information|Drive added: C:\, Fixed
2023-05-17 16:20:39.2902|Information|Drive added: D:\, Removable
2023-05-17 16:20:39.6308|Information|Drive added: D:\
2023-05-17 16:20:45.5651|Information|SIDELOAD: Checking for updates...
2023-05-17 16:20:47.0315|Information|SIDELOAD: Current Package Name: Files
2023-05-17 16:20:47.0324|Information|SIDELOAD: Remote Package Name: Files
2023-05-17 16:20:47.0330|Information|SIDELOAD: Current Version: 2.4.71.0
2023-05-17 16:20:47.0335|Information|SIDELOAD: Remote Version: 2.4.71.0
2023-05-17 16:20:47.0396|Warning|SIDELOAD: Update not found.
2023-05-17 16:20:51.5409|Information|Running on ARM: False
2023-05-17 16:22:16.2021|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-05-17 16:22:16.7038|Information|Adding cloud provider "OneDrive" mapped to C:\Users\livio\OneDrive
2023-05-17 16:22:20.4430|Information|Drive added: C:\, Fixed
2023-05-17 16:22:20.5808|Information|Drive added: D:\, Removable
2023-05-17 16:22:21.1947|Information|Drive added: D:\
2023-05-17 16:22:28.4608|Information|SIDELOAD: Checking for updates...
2023-05-17 16:22:28.9726|Information|SIDELOAD: Current Package Name: Files
2023-05-17 16:22:28.9737|Information|SIDELOAD: Remote Package Name: Files
2023-05-17 16:22:28.9750|Information|SIDELOAD: Current Version: 2.4.71.0
2023-05-17 16:22:28.9759|Information|SIDELOAD: Remote Version: 2.4.71.0
2023-05-17 16:22:28.9843|Warning|SIDELOAD: Update not found.
2023-05-17 17:10:09.5018|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-05-17 17:10:10.0719|Information|Adding cloud provider "OneDrive" mapped to C:\Users\livio\OneDrive
2023-05-17 17:10:14.1357|Information|Drive added: C:\, Fixed
2023-05-17 17:10:14.2427|Information|Drive added: D:\, Removable
2023-05-17 17:10:14.7406|Information|Drive added: D:\
2023-05-17 17:10:22.1756|Information|SIDELOAD: Checking for updates...
2023-05-17 17:10:22.6857|Information|SIDELOAD: Current Package Name: Files
2023-05-17 17:10:22.7023|Information|SIDELOAD: Remote Package Name: Files
2023-05-17 17:10:22.7185|Information|SIDELOAD: Current Version: 2.4.71.0
2023-05-17 17:10:22.7331|Information|SIDELOAD: Remote Version: 2.4.71.0
2023-05-17 17:10:22.7558|Warning|SIDELOAD: Update not found.
2023-05-17 17:10:23.9844|Information|Running on ARM: False
2023-05-17 18:20:09.1724|Error|System.ArgumentOutOfRangeException: This collection cannot work with indices larger than Int32.MaxValue - 1 (0x7FFFFFFF - 1). (Parameter 'index')
   at ABI.System.Collections.IList.ToAbiHelper.EnsureIndexInt32(UInt32 index, Int32 listCapacity)
   at ABI.System.Collections.IList.ToAbiHelper.GetAt(UInt32 index)
   at ABI.System.Collections.IList.Vftbl.Do_Abi_GetAt_0(IntPtr thisPtr, UInt32 index, IntPtr* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
2023-05-17 18:20:34.5233|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-05-17 18:20:35.1937|Information|Adding cloud provider "OneDrive" mapped to C:\Users\livio\OneDrive
2023-05-17 18:20:38.4503|Information|Drive added: C:\, Fixed
2023-05-17 18:20:38.6025|Information|Drive added: D:\, Removable
2023-05-17 18:20:39.1141|Information|Drive added: D:\
2023-05-17 18:20:41.7398|Information|Running on ARM: False
2023-05-17 18:20:46.0556|Information|SIDELOAD: Checking for updates...
2023-05-17 18:20:46.5161|Information|SIDELOAD: Current Package Name: Files
2023-05-17 18:20:46.5840|Information|SIDELOAD: Remote Package Name: Files
2023-05-17 18:20:46.6072|Information|SIDELOAD: Current Version: 2.4.71.0
2023-05-17 18:20:46.6224|Information|SIDELOAD: Remote Version: 2.4.71.0
2023-05-17 18:20:46.6445|Warning|SIDELOAD: Update not found.
2023-05-17 18:24:50.1376|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-05-17 18:24:50.6205|Information|Adding cloud provider "OneDrive" mapped to C:\Users\livio\OneDrive
2023-05-17 18:24:53.6621|Information|Drive added: C:\, Fixed
2023-05-17 18:24:53.7927|Information|Drive added: D:\, Removable
2023-05-17 18:24:54.4176|Information|Drive added: D:\
2023-05-17 18:25:01.7255|Information|SIDELOAD: Checking for updates...
2023-05-17 18:25:02.2234|Information|SIDELOAD: Current Package Name: Files
2023-05-17 18:25:02.2333|Information|SIDELOAD: Remote Package Name: Files
2023-05-17 18:25:02.2456|Information|SIDELOAD: Current Version: 2.4.71.0
2023-05-17 18:25:02.2558|Information|SIDELOAD: Remote Version: 2.4.71.0
2023-05-17 18:25:02.2748|Warning|SIDELOAD: Update not found.
2023-05-17 18:25:58.9051|Information|Running on ARM: False
2023-05-17 18:35:08.0683|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-05-17 18:35:08.4865|Information|Adding cloud provider "OneDrive" mapped to C:\Users\livio\OneDrive
2023-05-17 18:35:12.2108|Information|Drive added: C:\, Fixed
2023-05-17 18:35:12.3992|Information|Drive added: D:\, Removable
2023-05-17 18:35:12.9709|Information|Drive added: D:\
2023-05-17 18:35:32.3742|Information|SIDELOAD: Checking for updates...
2023-05-17 18:35:33.4397|Warning|System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Load(String pszFileName, Int32 dwMode)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Filesystem.RecentItems.<>c__DisplayClass14_1.<ListRecentFoldersAsync>b__2()
2023-05-17 18:35:34.5009|Information|SIDELOAD: Current Package Name: Files
2023-05-17 18:35:34.5703|Information|SIDELOAD: Remote Package Name: Files
2023-05-17 18:35:34.6180|Information|SIDELOAD: Current Version: 2.4.71.0
2023-05-17 18:35:34.6641|Information|SIDELOAD: Remote Version: 2.4.71.0
2023-05-17 18:35:34.7112|Warning|SIDELOAD: Update not found.
2023-05-17 18:39:44.5010|Information|Running on ARM: False
2023-05-17 18:45:32.3908|Warning|System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Load(String pszFileName, Int32 dwMode)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Filesystem.RecentItems.<>c__DisplayClass14_1.<ListRecentFoldersAsync>b__2()
2023-05-17 18:47:27.7906|Warning|System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Load(String pszFileName, Int32 dwMode)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Filesystem.RecentItems.<>c__DisplayClass14_1.<ListRecentFoldersAsync>b__2()

**Comment by Josh65-2201** [comment]
Can you clarify if you open the recycle bin and have no contents showing or you don't have a button to access it. If it's the second one you can try putting `Shell:RecycleBinFolder` into the path bar > right clicking the empty space > pin it to favorites.

**Comment by lico9182** [comment]
Thanks, i don't have a button displaying down the left pane under any location headings , but if i put in the Shell:RecycleBinFolder command into the Files address bar i do get to the Recycle bin location, so i've now pinned it to the 'Favourites' location .....thanks for your help and instructions Josh

**Comment by Josh65-2201** [comment]
No problem, The favorites is the official ways right now and is usually there by default.
