### ISSUE TITLE
Bug: Freeze when right clicking

### ISSUE THREAD

**Issue by ccyykkcyk** [files-community/Files#12598]
### Description

When I right-click a file or folder in driver page, Files freezed, but it works well in homepage and sidebar.
This problem existed before version 2.5.0.0

### Steps To Reproduce

1. open a driver
2. right-click on a file

https://github.com/files-community/Files/assets/91893497/c84da085-8bdb-4b22-b90b-5a0396b77c7b

### Requirements

Files should not freeze

### Files Version

Version: 2.5.0.0

### Windows Version

Windows 10 (22H2): 19045

### Log File

[debug.log](https://github.com/files-community/Files/files/11737525/debug.log)

**Comment by anuti** [comment]
I have the same error
Files 2.5.0.0
Windows 11 (22H2)

**Comment by yaira2** [comment]
Is this specific to drives or is it in other folders too?

**Comment by ccyykkcyk** [comment]
> Is this specific to drives or is it in other folders too?

same error for all folders

**Comment by yaira2** [comment]
```
2023-06-14 01:10:45.2275|Information|System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalSubKeyCountCore()
   at Microsoft.Win32.RegistryKey.GetSubKeyNames()
   at Files.App.Shell.ShellNewMenuHelper.GetShellNewRegistryEntries(RegistryKey current, RegistryKey root)
```
@hishitetsu have you seen this before? Looks like a new one...

**Comment by hishitetsu** [comment]
I have never seen it. The exception occurs in a different place than before.

**Comment by yaira2** [comment]
@ccyykkcyk a potential fix will be in the next update.

**Comment by Hawksprey420** [comment]
Upon checking on Event Viewer:
Category: Files.App.App
EventId: 0

This operation returned because the timeout period expired. (0x800705B4)

Exception: 
System.Runtime.InteropServices.COMException (0x800705B4): This operation returned because the timeout period expired. (0x800705B4)
   at Vanara.PInvoke.Shell32.IShellLinkW.Resolve(HWND hwnd, SLR_FLAGS fFlags)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Filesystem.RecentItems.<>c__DisplayClass14_1.<ListRecentFoldersAsync>b__2()
   
   
  This behavior still exists on Files version 2.5.10.0
