### ISSUE TITLE
Unable to unpin Favourites - Nothing happens

### ISSUE THREAD

**Issue by cardin** [files-community/Files#12785]
### Description

When I right click on a Favourites entry and try to Unpin it, nothing happens. The entry is not unpinned.

I've attached a video illustrating the problem.

https://github.com/files-community/Files/assets/553816/1e3611f7-1986-4079-becf-6340cf1dbe78

### Steps To Reproduce

See the video
1. Have a folder that is in the Favourites entries
2. Right-click left sidebar, Unpin from Favourites

PS: I can replicate the issue without having to navigate to within that pinned folder

### Requirements

- the entry should get unpinned
- If there is a problem stopping it from getting unpinned, user should be notified via a UI popup

### Files Version

2.5.10.0

### Windows Version

10.0.22621.1928

### Log File

[debug.log](https://github.com/files-community/Files/files/11902969/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, 
- Can you try waiting for all the context items to load then see if it works.

**Comment by cardin** [comment]
> * Can you try waiting for all the context items to load then see if it works.

Nope, the issue still exists. It's not a context menu issue because there's error logs being generated consistently everytime I try to unpin it:

```
2023-06-29 20:41:35.1933|Error|System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Services.QuickAccessService.UnpinFromSidebar(String[] folderPaths)
   --- End of inner exception stack trace ---
2023-06-29 20:41:45.4655|Error|System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Services.QuickAccessService.UnpinFromSidebar(String[] folderPaths)
   --- End of inner exception stack trace ---
2023-06-29 20:41:54.6150|Error|System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Services.QuickAccessService.UnpinFromSidebar(String[] folderPaths)
   --- End of inner exception stack trace ---
2023-06-29 20:43:26.4822|Error|System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Services.QuickAccessService.UnpinFromSidebar(String[] folderPaths)
   --- End of inner exception stack trace ---
2023-06-29 20:43:33.2626|Error|System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Services.QuickAccessService.UnpinFromSidebar(String[] folderPaths)
   --- End of inner exception stack trace ---
```

**Comment by Josh65-2201** [comment]
Thanks for the update, I've added this to the project board.

**Comment by Lukiluc29** [comment]
Perhaps this issue has been resolved because many things related to the Favorites section have been modified. Besides, I can't reproduce this problem.

**Comment by cardin** [comment]
Yes the issue has been resolved now, thanks!
