### ISSUE TITLE
UI Gets Struck on Renaming

### ISSUE THREAD

**Issue by sirinath** [files-community/Files#13273]
### Description

![image](https://github.com/files-community/Files/assets/637415/1088d260-fb94-460c-a687-0b8cda43d60d)

### Steps To Reproduce

Rename

### Requirements

Responsive UI

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12461377/debug.log)

**Comment by sirinath** [comment]
I am adding this here so I don't have to open another issue. On one occasion when deleting a file, it did not get deleted. In the Ongoing Task list it said Recycle failed. When I tried again it got deleted.

**Comment by yaira2** [comment]
I can't repro this issue in the latest preview build, can you confirm if it's fixed on your side as well? https://files.community/download

**Comment by sirinath** [comment]
Cannot say for sure as instability does not happen often. It is very rare.

**Comment by yaira2** [comment]
Okay, please let us know if it happens again and we'll continue debugging this.

**Comment by jobukkit** [comment]
For me the app now crashes if I rename or delete a file. Version 2.5.21.0

```
2023-09-21 12:07:07.9206|Error|System.NotImplementedException: The method or operation is not implemented.
   at Vanara.PInvoke.Shell32.ITaskbarList2.HrInit()
   at Files.App.Utils.Shell.Win32API.CreateTaskbarObject()
   at Files.App.Utils.Storage.FileOperationsHelpers.ProgressHandler..ctor()
   at Files.App.Utils.Storage.FileOperationsHelpers.RenameItemAsync(String fileToRenamePath, String newName, Boolean overwriteOnRename, String operationID)
   at Files.App.Utils.Storage.ShellFilesystemOperations.RenameAsync(IStorageItemWithPath source, String newName, NameCollisionOption collision, IProgress`1 progress, CancellationToken cancellationToken)
   at Files.App.Utils.Storage.FilesystemHelpers.RenameAsync(IStorageItemWithPath source, String newName, NameCollisionOption collision, Boolean registerHistory, Boolean showExtensionDialog)
   at Files.App.Helpers.UIFilesystemHelpers.RenameFileItemAsync(ListedItem item, String newName, IShellPage associatedInstance, Boolean showExtensionDialog)
   at Files.App.Views.LayoutModes.StandardViewBase.CommitRename(TextBox textBox)
   at Files.App.Views.LayoutModes.StandardViewBase.RenameTextBox_KeyDown(Object sender, KeyRoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
```

**Comment by Josh65-2201** [comment]
Plese make a new bug report
