### ISSUE TITLE
Bug: App crash on drag & drop from a browser

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#13590]
### Description

App crashes when attempting to drag an image from the browser to Files.

### Steps To Reproduce

1. Drag an image from the browser
2. Drop to Files app

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.31.0

### Windows Version

10.0.23570.1000

### Log File

```cs
2023-10-28 03:54:53.4255|Error|System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.App.Utils.StatusCenter.StatusCenterHelper.UpdateCardStrings(StatusCenterItem card)
   at Files.App.Utils.StatusCenter.StatusCenterItem..ctor(String headerResource, String subHeaderResource, ReturnResult status, FileOperationType operation, IEnumerable`1 source, IEnumerable`1 destination, Boolean canProvideProgress, Int64 itemsCount, Int64 totalSize, CancellationTokenSource operationCancellationToken)
   at Files.App.ViewModels.UserControls.StatusCenterViewModel.AddItem(String headerResource, String subHeaderResource, ReturnResult status, FileOperationType operation, IEnumerable`1 source, IEnumerable`1 destination, Boolean canProvideProgress, Int64 itemsCount, Int64 totalSize, CancellationTokenSource cancellationTokenSource)
   at Files.App.Utils.StatusCenter.StatusCenterHelper.AddCard_Copy(ReturnResult returnStatus, IEnumerable`1 source, IEnumerable`1 destination, Int64 itemsCount, Int64 totalSize)
   at Files.App.Utils.Storage.FilesystemHelpers.CopyItemsAsync(IEnumerable`1 source, IEnumerable`1 destination, Boolean showDialog, Boolean registerHistory)
   at Files.App.Utils.Storage.FilesystemHelpers.CopyItemsFromClipboard(DataPackageView packageView, String destination, Boolean showDialog, Boolean registerHistory)
   at Files.App.Utils.Storage.FilesystemHelpers.PerformOperationTypeAsync(DataPackageOperation operation, DataPackageView packageView, String destination, Boolean showDialog, Boolean registerHistory, Boolean isTargetExecutable)
   at Files.App.ViewModels.LayoutModes.BaseLayoutViewModel.DropAsync(DragEventArgs e)
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
```

**Comment by yaira2** [comment]
Thank you for the report.

**Comment by yaira2** [comment]
This doesn't appear to be an issue in stable.

**Comment by yaira2** [comment]
Thanks again for reporting this issue. We have a fix in the works and will make sure it's included before releasing v3.
