### ISSUE TITLE
Bug: COMException (0x8000FFFF) from Files.App.Data.Models.SelectedItemsPropertiesViewModel.set_ItemCreatedTimestampReal

### ISSUE THREAD

**Issue by skst** [files-community/Files#13725]
### Description

````
Application: Files.exe
CoreCLR Version: 7.0.1323.51816
.NET Version: 7.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x8000FFFF)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.ITextBlockMethods.set_Text(IObjectReference _obj, String value)
   at Files.App.Views.Properties.GeneralPage.GeneralPage_obj1_Bindings.GeneralPage_obj1_BindingsTracking.PropertyChanged_ViewModel(Object sender, PropertyChangedEventArgs e)
   at Files.App.Data.Models.SelectedItemsPropertiesViewModel.set_ItemCreatedTimestampReal(DateTimeOffset value)
   at Files.App.Views.Properties.GeneralPage.UpdateDateDisplayTimer_Tick(Object sender, Object e)
   at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args)
--- End of stack trace from previous location ---
````

### Steps To Reproduce

Sadly, I do not know what I was doing when this occurred. If I reproduce it again, I will update this report.

### Requirements

Exception should be caught and handled (or the cause of the exception corrected).

### Files Version

3.0.0.0

### Windows Version

10.0.22621.2428

### Log File

[debug.log](https://github.com/files-community/Files/files/13289710/debug.log)

**Comment by yaira2** [comment]
Thanks for the feedback, I see a number of these reports in AppCenter but I haven't been able to repro it.

**Comment by hishitetsu** [comment]
I'd like to work on this.
