### ISSUE TITLE
Bug: WhoIsLocking Could not list processes

### ISSUE THREAD

**Issue by Yabino** [files-community/Files#13857]
### Description

When I tried to cut/paste files from a folder to another, files shows a message saying it's already in use by another app. Which obviously is not the case.

### Steps To Reproduce

Cut and paste from a folder to another.

### Requirements

Fix the bug

### Files Version

3.0.3

### Windows Version

Windows 11 Pro 23H2 22635.2700

### Log File

023-11-13 21:11:34.5172|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-11-13 21:11:34.6378|Information|Adding cloud provider "OneDrive" mapped to C:\Users\yabin\OneDrive
2023-11-13 21:11:35.4996|Information|Running on ARM: False
2023-11-13 21:11:37.1354|Information|Drive added: C:\, Fixed
2023-11-13 21:11:37.2823|Information|Drive added: D:\, CDRom
2023-11-13 21:11:37.3431|Information|Drive added: D:\
2023-11-13 21:11:38.2448|Information|STORE: Checking for updates...
2023-11-13 21:11:55.7719|Information|System.Exception: Could not list processes locking resource. Failed to get size of result.
   at Files.App.Helpers.FileUtils.WhoIsLocking(String[] resources)
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-11-13 21:35:04.2455|Information|STORE: Checking for updates...
2023-11-13 21:35:04.2948|Information|App activated. Activated args type: LaunchActivatedEventArgs
2023-11-13 21:35:28.9604|Information|System.Exception: Could not list processes locking resource. Failed to get size of result.
   at Files.App.Helpers.FileUtils.WhoIsLocking(String[] resources)
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-11-13 21:35:37.8572|Information|System.Exception: Could not list processes locking resource. Failed to get size of result.
   at Files.App.Helpers.FileUtils.WhoIsLocking(String[] resources)
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2023-11-13 21:39:03.0765|Information|App activated. Activated args type: ProtocolActivatedEventArgs

**Comment by Yabino** [comment]
I cut/paste from a folder in my "Downloads" folder. Let's call it "Folder A".

 There are subfolders inside and I wanted to move them to the root of "Folder A". And yes with Windows Explorer it does work.

**Comment by Josh65-2201** [comment]
Thanks for checking

**Comment by Yabino** [comment]
What's strange, is that copying/pasting works, and deleting the folder
works.

Il lun 13 nov 2023, 23:06 Yair ***@***.***> ha scritto:

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
