### ISSUE TITLE
Bug: Crash when moving a bunch of files

### ISSUE THREAD

**Issue by KloWhrhyde** [files-community/Files#13915]
### Description

When i do a lot of cutting / copying / paste of large files / high number of files, the CPU Usage is going up crazily, At least 50 to 100 %, when it reach 100 % the app usally is stuck or crash.

CPU : AMD RYZEN 3900X

image : Simulating the Issue in moving 12 MKV Files from a folder to another on the same disk.
![FILESHIGHUSAGE](https://github.com/files-community/Files/assets/151076187/236ba173-0c56-4389-9a67-9520116227c1)

### Steps To Reproduce

1 Try to move or copy 10+ large folders/files (500 mb+) on the same drive
2  the issue is worse if there is errors in the queue
3 App stuck then Crash or 100 % CPU Usage

### Requirements

- Fix crash that occurs when copying large amount of files
- Fix high CPU Usage in this usecase

### Files Version

3.0.5.0

### Windows Version

10.0.22621.2428

### Log File

[debug.log](https://github.com/files-community/Files/files/13382459/debug.log)

**Comment by yaira2** [comment]
Thanks for the report. We're tracking performance issues in #4180, but let's keep this open as well until the crash is fixed.

**Comment by yaira2** [comment]
```
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)```

**Comment by yaira2** [comment]
In general, you can work around some of these issues by disabling the option to keep Files in the background.

**Comment by yaira2** [comment]
We're also actively working on performance improvements for file operations. Fyi @hez2010

**Comment by Josh65-2201** [comment]
Can you see if this is still an issue in the current preview version. https://files.community/download
