### ISSUE TITLE
Copy Error through TeamViewer

### ISSUE THREAD

**Issue by CarlosGonzalo0** [files-community/Files#13998]
### Description

Using TeamViewer, With windows explorer  copy and paste a folder  from remote to a local disk work without a problem.
with Files the copy of files or folder interrupts without a warning.

### Steps To Reproduce

open Teamviewer
Open explorer on remote pc
Select a folder and copy it.
Open explorer on local pc 
select a folder  and paste

### Requirements

- e.g. Fix crash that occurs when...
Copy an Paste folder or files from remote pc connected through TeamViewer
 

### Files Version

3.0.8.0

### Windows Version

Windows 11 - 10.0.22621.2428

### Log File

2023-11-21 09:56:13.9447|Information|SIDELOAD: Current Package Name: Files
2023-11-21 09:56:13.9450|Information|SIDELOAD: Remote Package Name: Files
2023-11-21 09:56:13.9452|Information|SIDELOAD: Current Version: 3.0.8.0
2023-11-21 09:56:13.9454|Information|SIDELOAD: Remote Version: 3.0.8.0
2023-11-21 09:56:13.9459|Warning|SIDELOAD: Update not found.
2023-11-21 10:08:44.7054|Warning|SevenZip.ExtractionFailedException: File is corrupted. Data error has occured.
   at SevenZip.SevenZipBase.ThrowException(CallbackBase handler, Exception[] e)
   at SevenZip.SevenZipBase.CheckedExecute(Int32 hresult, String message, CallbackBase handler)
   at SevenZip.SevenZipExtractor.ExtractArchive(String directory)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at SevenZip.SevenZipExtractor.ExtractArchiveAsync(String directory)
   at Files.App.Utils.Archives.DecompressHelper.DecompressArchiveAsync(BaseStorageFile archive, BaseStorageFolder destinationFolder, String password, IProgress`1 progress, CancellationToken cancellationToken)
2023-11-21 10:10:34.5166|Warning|System.Runtime.InteropServices.COMException (0x80040064): Estructura FORMATETC no válida (0x80040064 (DV_E_FORMATETC))
   at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
   at Vanara.PInvoke.Shell32.GetData(IDataObject dataObj, UInt32 formatId, DVASPECT aspect, Int32 index)
   at Files.App.Utils.Storage.FilesystemHelpers.GetDraggedStorageItems(DataPackageView packageView)
2023-11-21 10:11:19.4570|Warning|System.Runtime.InteropServices.COMException (0x80040064): Estructura FORMATETC no válida (0x80040064 (DV_E_FORMATETC))
   at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
   at Vanara.PInvoke.Shell32.GetData(IDataObject dataObj, UInt32 formatId, DVASPECT aspect, Int32 index)
   at Files.App.Utils.Storage.FilesystemHelpers.GetDraggedStorageItems(DataPackageView packageView)
2023-11-21 10:14:23.9063|Warning|System.Runtime.InteropServices.COMException (0x80040064): Estructura FORMATETC no válida (0x80040064 (DV_E_FORMATETC))
   at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
   at Vanara.PInvoke.Shell32.GetData(IDataObject dataObj, UInt32 formatId, DVASPECT aspect, Int32 index)
   at Files.App.Utils.Storage.FilesystemHelpers.GetDraggedStorageItems(DataPackageView packageView)
2023-11-21 10:17:22.8222|Information|SIDELOAD: Checking for updates...
2023-11-21 10:17:22.8899|Information|App activated. Activated args type: ProtocolActivatedEventArgs
2023-11-21 10:17:23.6152|Information|SIDELOAD: Current Package Name: Files
2023-11-21 10:17:23.6154|Information|SIDELOAD: Remote Package Name: Files
2023-11-21 10:17:23.6155|Information|SIDELOAD: Current Version: 3.0.8.0
2023-11-21 10:17:23.6157|Information|SIDELOAD: Remote Version: 3.0.8.0
2023-11-21 10:17:23.6160|Warning|SIDELOAD: Update not found.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Merging with #12788. You can check there or click subscribe in the right sidebar for updates.

For future issue please UPLOAD the file not copy and paste
