### ISSUE TITLE
Bug: Unable to extract files

### ISSUE THREAD

**Issue by Saransh719** [files-community/Files#14001]
### Description

Whenever I try to extract files using extract here or extract files in the context menu, nothing happens.
Note: 7zip or windows explorer are able to extract thus there is no issue with the zip/rar file itself

### Steps To Reproduce

Right click on rar/zip file and click extract-->Extract Here/Files

### Requirements

Files should be extracted from zip/rar file

### Files Version

3.0.8.0

### Windows Version

19045.3693

### Log File

[debug.log](https://github.com/files-community/Files/files/13429403/debug.log)

**Comment by yaira2** [comment]
> 2023-11-21 00.22.13.8065|Warning|SevenZip.SevenZipOpenFailedException: Invalid archive: open/read error! Is it encrypted and a wrong password was provided?
If your archive is an exotic one, it is possible that SevenZipSharp has no signature for its format and thus decided it is TAR by mistake.
   at SevenZip.SevenZipExtractor.OpenArchive(IInStream archiveStream, ArchiveOpenCallback openCallback)
   at SevenZip.SevenZipExtractor.GetArchiveInfo()
   at Files.App.Utils.Storage.ZipStorageFolder.<GetItemsAsync>b__49_1()
   at Files.App.Utils.Storage.IPasswordProtectedItem.RetryWithCredentialsAsync[TOut](Func`1 func, Exception exception)
   at Files.Shared.Extensions.SafetyExtensions.Wrap[TOut](Func`1 inputTask, Func`3 onFailed)
   at Files.App.Utils.Storage.ZipStorageFolder.<>c__DisplayClass50_0.<<GetItemsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Files.App.Utils.Storage.UniversalStorageEnumerator.ListEntries(BaseStorageFolder rootFolder, StorageFolderWithPath currentStorageFolder, CancellationToken cancellationToken, Int32 countLimit, Func`2 intermediateAction, Dictionary`2 defaultIconPairs)

**Comment by yaira2** [comment]
It takes around 20 minutes for the sideload version to deploy, and depending on the day, the Store version usually passes certification in a couple hours.

**Comment by Saransh719** [comment]
> It takes around 20 minutes for the sideload version to deploy, and depending on the day, the Store version usually passes certification in a couple hours.

ok thanks

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by yaira2** [comment]
Closing for now but please let us know if you're still experiencing this issue in the latest preview build.
