### ISSUE TITLE
Bug: App crashing on launch

### ISSUE THREAD

**Issue by pdmaclellan** [files-community/Files#14053]
### Description

I have been using this product for 2+ years with no issues. Recently upgraded to  ver 3.0.8.0.  When opening the app the first time in the day it takes between 30-60 seconds to open. Sometimes longer. Once opened  I can close the app and reopen it and it opens as expected very quickly. At times it randomly freezes.

![image](https://github.com/files-community/Files/assets/49559220/e3720723-4afa-4865-a288-35610afe4d9b)

![image](https://github.com/files-community/Files/assets/49559220/4fdd7b64-d1a2-479d-9545-cb2a9460f77b)

### Steps To Reproduce

Open the Files App
Wait

### Requirements

See above description

### Files Version

3.0.8.0

### Windows Version

Windows 11 Pro 22621.2428

### Log File

[debug.log](https://github.com/files-community/Files/files/13459724/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, 
- The slow initial startup is expected as it has to start the processes and will hopefully improved over time. #4180 is tracking these improvements.
- Can you see if the crashing is an issue in the preview version. https://files.community/download

**Comment by pdmaclellan** [comment]
Thanks Josh,

That would be a concern if this is expected behavior. Much too long a wait and the app freezing makes it unreliable. It hasn't been in the past and as mentioned have been using this product for years.

I will uninstall current version and install the preview version and be sure to provide some feedback.

**Comment by yaira2** [comment]
> That would be a concern if this is expected behavior. Much too long a wait and the app freezing makes it unreliable. It hasn't been in the past and as mentioned have been using this product for years.

With which version did this issue first start occurring?

**Comment by pdmaclellan** [comment]
I first noticed this on 3.0.8.0. I have since uninstall that version an installed the “Preview”. Error screen on launch stating possibly not enough permissions. Hit launch a second time and app opened. Same slowness opening the app. It also froze.  Had to move in onto other things. So back to File explorer for now. I will try this on another device later today.  I also noticed exporting settings seems to work and produces the zip file but importing the settings does not. That was with both versions, 3.0.8.0 and the Preview.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pdmaclellan** [comment]
[debug.log](https://github.com/files-community/Files/files/13460687/debug.log)

Version 3.0.11.0 debug

**Comment by yaira2** [comment]
I see two crashes in the log file
```
2023-11-24 09:20:20.1345|Warning|System.InvalidCastException: Unable to cast object of type 'System.Text.Json.JsonElement' to type 'Files.Core.Data.Enums.BackdropMaterialType'.
   at Files.App.Helpers.AppSystemBackdrop.OnSettingChanged(Object sender, SettingChangedEventArgs e)
   at Files.App.Utils.Serialization.BaseJsonSettings.RaiseOnSettingChangedEvent(Object sender, SettingChangedEventArgs e)
   at Files.App.Services.Settings.UserSettingsService.ImportSettings(Object import)
   at Files.App.ViewModels.Settings.AdvancedViewModel.ImportSettingsAsync()
2023-11-24 09:20:20.7547|Error|System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The object has been closed.

The given object has already been closed / disposed and may no longer be used.)
 ---> System.ObjectDisposedException: The object has been closed.

The given object has already been closed / disposed and may no longer be used.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Composition.SystemBackdrops.ISystemBackdropControllerWithTargetsMethods.RemoveSystemBackdropTarget(IObjectReference _obj, ICompositionSupportsSystemBackdrop systemBackdropTarget)
   at Files.App.Helpers.AppSystemBackdrop.OnTargetDisconnected(ICompositionSupportsSystemBackdrop disconnectedTarget)
   at ABI.Microsoft.UI.Xaml.Media.ISystemBackdropOverrides.Do_Abi_OnTargetDisconnected_1(IntPtr thisPtr, IntPtr disconnectedTarget)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IWindow2Methods.set_SystemBackdrop(IObjectReference _obj, SystemBackdrop value)
   at Files.App.MainWindow.InitializeApplicationAsync(Object activatedEventArgs)
   at CommunityToolkit.WinUI.DispatcherQueueExtensions.<>c__DisplayClass2_0.<<EnqueueAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
```

**Comment by NoxArt** [comment]
I also had a crash today, but there is no error or warning in debug.log

This is in Event viewer

> Faulting application name: Files.exe, version: 1.0.0.0, time stamp: 0x6531c3a8
Faulting module name: Microsoft.UI.Input.dll, version: 10.0.22624.1051, time stamp: 0xb0e6654a
Exception code: 0xc0000005
Fault offset: 0x00000000000137cd
Faulting process id: 0x0x7EE0
Faulting application start time: 0x0x1DA1F0FBD84FCCE
Faulting application path: C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_3.0.8.0_x64__et10x9a9vyk8t\Files.App\Files.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1049.117.0_x64__8wekyb3d8bbwe\Microsoft.UI.Input.dll
Report Id: eff55426-9a7c-48df-a056-f16180225276
Faulting package full name: 49306atecsolution.FilesUWP_3.0.8.0_x64__et10x9a9vyk8t
Faulting package-relative application ID: App

**Comment by pdmaclellan** [comment]
Dark Theme, Mica Alt, Default Background

**Comment by yaira2** [comment]
Can you try changing the backdrop to none?

**Comment by yaira2** [comment]
@pdmaclellan can you check the latest preview build to see if this is resolved? https://files.community/download/preview

**Comment by yaira2** [comment]
Did it work?

**Comment by yair100** [comment]
@pdmaclellan we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller
