### ISSUE TITLE
Can get tabs into "stuck/disabled" state, reproduceable

### ISSUE THREAD

**Issue by coinzdude** [files-community/Files#14726]
### Description

1. Open Files, one tab
![image](https://github.com/files-community/Files/assets/58857646/69a0cb1c-26eb-4d5a-8998-69864b51391e)

2. Duplicate tab
![image](https://github.com/files-community/Files/assets/58857646/fe159db1-d65a-47b3-8fcb-bc9f9ef4ddf4)

3. Drag left tab over right tab and drop. 

The 2nd tab is now in a "disabled" state.
![image](https://github.com/files-community/Files/assets/58857646/3b6c88cf-18c4-4453-8879-797f7a173a89)

At this point, the 2nd tab is not draggable

### Steps To Reproduce

See Description

There are similar/related drag and drop issues with tabs that can be induced.

For example once induced like above, try dragging a new tab into the tab set and this happens

![image](https://github.com/files-community/Files/assets/58857646/b35f9a04-be28-46c9-a24a-5c346bc59bbf)

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.2.0.0

### Windows Version

22631.3085

### Log File

[debug.log](https://github.com/files-community/Files/files/14290568/debug.log)

**Comment by yaira2** [comment]
I'm able to repro this every so often, but only with multiple tries and only if I purposely hover over the other tab for some time.

**Comment by verdaderoken** [comment]
Mine crashes with this error:

```
2024-02-28 16:08:19.3110|Error|System.Runtime.InteropServices.COMException (0x80004005)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementMethods.FindName(IObjectReference _obj, String name)
   at Files.App.UserControls.InnerNavigationToolbar.InnerNavigationToolbar_obj1_Bindings.Update_ViewModel_IsDetailsLayout(Boolean obj, Int32 phase)
   at Files.App.UserControls.InnerNavigationToolbar.InnerNavigationToolbar_obj1_Bindings.Update_ViewModel(AddressToolbarViewModel obj, Int32 phase)
   at Files.App.UserControls.InnerNavigationToolbar.InnerNavigationToolbar_obj1_Bindings.InnerNavigationToolbar_obj1_BindingsTracking.DependencyPropertyChanged_ViewModel(DependencyObject sender, DependencyProperty prop)
   at ABI.Microsoft.UI.Xaml.DependencyPropertyChangedCallback.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr dp)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IDependencyObjectMethods.SetValue(IObjectReference _obj, DependencyProperty dp, Object value)
   at Files.App.Views.MainPage.MultitaskingControl_CurrentInstanceChanged(Object sender, CurrentInstanceChangedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
   ```

**Comment by yaira2** [comment]
> Mine crashes with this error:
> 
> ```
> 2024-02-28 16:08:19.3110|Error|System.Runtime.InteropServices.COMException (0x80004005)
>    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
>    at ABI.Microsoft.UI.Xaml.IFrameworkElementMethods.FindName(IObjectReference _obj, String name)
>    at Files.App.UserControls.InnerNavigationToolbar.InnerNavigationToolbar_obj1_Bindings.Update_ViewModel_IsDetailsLayout(Boolean obj, Int32 phase)
>    at Files.App.UserControls.InnerNavigationToolbar.InnerNavigationToolbar_obj1_Bindings.Update_ViewModel(AddressToolbarViewModel obj, Int32 phase)
>    at Files.App.UserControls.InnerNavigationToolbar.InnerNavigationToolbar_obj1_Bindings.InnerNavigationToolbar_obj1_BindingsTracking.DependencyPropertyChanged_ViewModel(DependencyObject sender, DependencyProperty prop)
>    at ABI.Microsoft.UI.Xaml.DependencyPropertyChangedCallback.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr dp)
> --- End of stack trace from previous location ---
>    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
>    at ABI.Microsoft.UI.Xaml.IDependencyObjectMethods.SetValue(IObjectReference _obj, DependencyProperty dp, Object value)
>    at Files.App.Views.MainPage.MultitaskingControl_CurrentInstanceChanged(Object sender, CurrentInstanceChangedEventArgs e)
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
>    at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
> --- End of stack trace from previous location ---
>    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
>    at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
>    at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
> --- End of stack trace from previous location ---
>    at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
>    at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
> ```

I don't think that's related to this

**Comment by NMBSdtayloe** [comment]
This is happening to me as well. After the tabs get into this disabled state, clicking the new tab button causes some strange behavior.
![image_318](https://github.com/files-community/Files/assets/113055594/b358901e-8fde-4476-b97e-e941e9a47ace)

**Comment by coinzdude** [comment]
Hi, @yaira2 yes, it's still an issue. I will try to send a video

**Comment by Josh65-2201** [comment]
@coinzdude Is this still an issue on v4.0.11 https://files.community/download

**Comment by Rowdster** [comment]
@Josh65-2201 Here is 4011

<img width="1226" height="241" alt="Image" src="https://github.com/user-attachments/assets/b35e5b5e-7d27-4b6d-b40a-d7b55687ee77" />

I did get it to hang once, first run, as initially reported but I did not capture the video. At this point, I'm not able to recreate it that specific hang, but I am getting different behaviors.  Maybe these are expected, or are entirely separate issues. There's a chance that the initial startup folder could impact this. I seemed to get different results from Home vs C:\temp for example.

The first unexpected behavior is the "opened new window" instead of swapping tab position. This is possibly interesting, you can see the "Move tab here" shows twice, then no longer shows. then finally, a new window opens instead.
![Image](https://github.com/user-attachments/assets/bc2fb0b2-37ea-4008-b16e-812a622b3877)


The second unexpected behavior I think is more related to this original issue is the greyed out tab text.  Once in this mode, I cannot swap these tabs
![Image](https://github.com/user-attachments/assets/4327e7e7-afc5-4029-a582-7995e56f1c47)

and when I duplicate the 2nd tab, from this greyed out state, I get this interesting layout where the first disappears, and I see the 2nd with the ghosted text.

<img width="1444" height="535" alt="Image" src="https://github.com/user-attachments/assets/1a969bd3-2cc4-41c7-bfcf-1841b4f018f4" />

I captured a bit more on that here:

![Image](https://github.com/user-attachments/assets/89c4db74-95ff-46b6-b3aa-6f2d9731bb12)

If I close and reopen, I get the 4 tabs back, as expected, but dragging them back and forth quickly breaks down like this

<img width="1678" height="567" alt="Image" src="https://github.com/user-attachments/assets/c3d19d15-5336-4539-b220-03b378ced958" />


Happy to test more or share any diagnostics.  I'm a dev, I could try recreating from within VS if there were particular breakpoints of interest. I would not be sure where to start there.

**Comment by Josh65-2201** [comment]
Thanks for checking, if you can fix this that would be great. You can see https://files.community/docs/contributing/building-from-source on how to build Files and the code style guidelines that are used
