### ISSUE TITLE
Bug: Copy/Pasting From TeamViewer Remote PC Doesn't Work

### ISSUE THREAD

**Issue by thompatry** [files-community/Files#14945]
### Description

I will reopen this case. I am having this issue. The Files app does not crash. I can copy files from my PC to the Teamviewer Remote PC. Where is fails is when I want to copy from the Teamviewer Remote PC to my PC. I have upload the debug log here. I copied from my computer at 7:28:30 and it works. When I copy back at 7:30:30, it appears to not work and hang. It acts like it is copying but does nothing. The Files app does not crash I have included the log file from that time. 

### Steps To Reproduce

1. From a TeamViewer remote session select files in File Explorer, Ctrl+C to copy them
2. Paste into Files on controlling PC fails.

### Requirements

- Files should copy as happens when pasting into File Explorer

### Files Version

3.2.2.0

### Windows Version

Windows 11 Pro Version	23H2 OS build	22631.3155 Experience	Windows Feature Experience Pack 1000.22684.1000.0

### Log File

[debug.log](https://github.com/files-community/Files/files/14572308/debug.log)

I commented on this case [12788 ](https://github.com/files-community/Files/issues/12788) but is appears to considered done.

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

**Comment by 0x5bfa** [comment]
Maybe we should continue in #12788.

**Comment by 0x5bfa** [comment]
Thanks for the feedback. This looks like a COM exception.

```
System.Runtime.InteropServices.COMException (0x80040064): Invalid FORMATETC structure (0x80040064 (DV_E_FORMATETC))
   at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
   at Vanara.PInvoke.Shell32.GetData(IDataObject dataObj, UInt32 formatId, DVASPECT aspect, Int32 index)
   at Files.App.Utils.Storage.FilesystemHelpers.GetDraggedStorageItems(DataPackageView packageView)
```

```
System.Runtime.InteropServices.COMException (0x80040064): Invalid FORMATETC structure (0x80040064 (DV_E_FORMATETC))
   at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
   at Vanara.PInvoke.Shell32.GetData(IDataObject dataObj, UInt32 formatId, DVASPECT aspect, Int32 index)
   at Files.App.Filesystem.FilesystemHelpers.GetDraggedStorageItems(DataPackageView packageView)
   at Files.App.Filesystem.FilesystemHelpers.CopyItemsFromClipboard(DataPackageView packageView, String destination, Boolean showDialog, Boolean registerHistory)
   at Files.App.Filesystem.FilesystemHelpers.PerformOperationTypeAsync(DataPackageOperation operation, DataPackageView packageView, String destination, Boolean showDialog, Boolean registerHistory, Boolean isTargetExecutable)
   at Files.App.Helpers.UIFilesystemHelpers.PasteItemAsync(String destinationPath, IShellPage associatedInstance)
   at Files.App.Views.Shells.ModernShellPage.KeyboardAccelerator_Invoked(KeyboardAccelerator sender, KeyboardAcceleratorInvokedEventArgs args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
```

**Comment by Josh65-2201** [comment]
@thompatry Is this still an issue on v4.0.11 https://files.community/download

**Comment by Josh65-2201** [comment]
@thompatry Can you answer the above question
