### ISSUE TITLE
Bug: Not a folder error when opening shell addresses

### ISSUE THREAD

**Issue by ElCunq** [files-community/Files#15083]
> [!important]
> Current workarounds 
> 1. Close Files from the system tray and reopen
> 2. Use the same language option for Files and Windows.
> 3. If the above doesn't work backup your settings in `Files settings > Advanced > Export`, then reinstall Files.

### Description

I can't use the app after the last updates. It says "NotAFolder" when I try to open trash bin or ThisPC. 
![resim](https://github.com/files-community/Files/assets/112334725/0e48f1a2-a632-4da9-945b-09dc234aaf9c)

### Steps To Reproduce

Restart computer.
Try to open trashbin or ThisPC.
Get the error.

### Requirements

Normally it should open the files but it doesn't open. I can solve it using preview version with it but it's temporary.

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3296

### Log File

[debug.log](https://github.com/files-community/Files/files/14812115/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, have you tried reinstalling Files? 
Make sure to export your settings by going to Files settings > Advanced > Export. then Import your settings from Files settings > Advanced > Import after reinstalling.

**Comment by ElCunq** [comment]
> Thanks for the report, have you tried reinstalling Files? Make sure to export your settings by going to Files settings > Advanced > Export. then Import your settings from Files settings > Advanced > Import after reinstalling.

Yes I tried like 3 or 4 times both stable and preview but it didn't work. Almost all my settings same with standart so I didn't exported them. But I remember I just change preview to acrylic and "set files for default file manager" to on.

**Comment by Josh65-2201** [comment]
What's shown in the path bar?

**Comment by ElCunq** [comment]
Shell:RecycleBinFolder and Shell:MyComputerFolder this  two 
Oh and the quick access part on home shows empty with this bug.

**Comment by ElCunq** [comment]
for again this is the recyclebin
![resim](https://github.com/files-community/Files/assets/112334725/6de20c62-1282-4650-9761-e9fa577d845b)

and this is the home screen
![resim](https://github.com/files-community/Files/assets/112334725/6e00fb10-a665-4a23-b808-fff631462f25)

**Comment by T-i-a-7** [comment]
Same problem here.

**Comment by ElCunq** [comment]
2 weeks later still no progress. That's sad.

**Comment by Josh65-2201** [comment]
There still hasn't been a way to constantly reproduce this, Only you and T-i-a-7 have reported it. Unfortunately there no error in the log to go off either.

**Comment by ElCunq** [comment]
I'm using kaspersky as a antivirus. Can it cause to problem? @T-i-a-7 are you using same?

**Comment by T-i-a-7** [comment]
@ElCunq @Josh65-2201 No, I'm not using it so that is not the problem.
I would also like to tell you that I did a clean install of windows (for another reason, not for this problem) and reinstalled Files as well. Guess what?! Everything is fine now: installed the same way, configured the same way, everything the same but now magically it works.

**Comment by TCAtrevor** [comment]
I am seeing this issue on one computer, but not the other, although I could've sworn it used to be on both. The currently affected computer has a largely filled Recycle Bin and the one no longer having this issue is currently empty. Hope this is relevant. I should've searched this issue sooner to give my feedback.

**Comment by Josh65-2201** [comment]
Does reinstalling Files on the one showing the dialog fix it?

**Comment by ElCunq** [comment]
> Does reinstalling Files on the one showing the dialog fix it?

Nope it didn't fix it. Actually it made no help. I thought it'll make some fixes but none. 🥲

**Comment by ElCunq** [comment]
> I am seeing this issue on one computer, but not the other, although I could've sworn it used to be on both. The currently affected computer has a largely filled Recycle Bin and the one no longer having this issue is currently empty. Hope this is relevant. I should've searched this issue sooner to give my feedback.

Thanks for the feedback I hope it'll help to solve

**Comment by vchalmel** [comment]
Hello, I have the same issue here.

**Comment by justinlosh** [comment]
I'm having the same issue, but not much in the debug log with the exception of the following:

`2024-06-12 19:28:08.4616|Error|System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ObjectReference'.
   at WinRT.IObjectReference.ThrowIfDisposed()
   at WinRT.IObjectReference.AsType[T]()
   at WinRT.ExceptionHelpers.GetHRForException(Exception ex)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)`

**Comment by ElCunq** [comment]
I had to reinstall windows some other problems and it didn't happen again but İ'm scared of it to repeat. I hope it'll be solved soon

**Comment by justinlosh** [comment]
Yeah, I actually just reinstalled Win 11 a week ago.

**Comment by 0x5bfa** [comment]
Thank for you all five people reporting this issue and waiting it to be fixed with great patience.

While Files devs have never been able to reproduce this, what I can tell is enumeration goes wrong without exception but with an unknown error when converting string path (‘Shell:RecycleBinFolder’) or trying to get the first item of recycle bin. But some of you reported this happens also win This PC folder so I guess this is caused due to the first reason.

I’m pretty sure this dialog is used in those two places in single method for enumerating inner children:

https://github.com/files-community/Files/blob/31d6fee922223af49bb20fc40e345300641044e9/src/Files.App/Data/Models/ItemViewModel.cs#L1556o

https://github.com/files-community/Files/blob/31d6fee922223af49bb20fc40e345300641044e9/src/Files.App/Data/Models/ItemViewModel.cs#L1657

This error message is actually an unknown error and using ‘Drive Unplugged’ with ‘NotAFolder’ subtitle isn’t appropriate at all. So I will include an error code in it until next preview build (also next stable is coming soon v3.5).

@hishitetsu Do you think it’d make more sense?

When preview build with this modification published, I’d like you all to test…

**Comment by 0x5bfa** [comment]
> the quick access part on home shows empty with this bug.

@ElCunq Let me know what makes you think so?

**Comment by 0x5bfa** [comment]
Thank for you all five people reporting this issue and waiting it to be fixed with great patience.

While Files devs have never been able to reproduce this, what I can tell is enumeration goes wrong without exception but with an unknown error when converting string path (‘Shell:RecycleBinFolder’).

I’m pretty sure this dialog with humanized error code is used only in this place in single method for enumerating inner children:

https://github.com/files-community/Files/blob/31d6fee922223af49bb20fc40e345300641044e9/src/Files.App/Data/Models/ItemViewModel.cs#L1657

This error message is actually ERROR_INVALID_DRIVE error from HResult. ‘NotAFolder’ message isn’t appropriate at all.



an unknown error and using ‘Drive Unplugged’ with ‘NotAFolder’ subtitle isn’t appropriate at all. So I will log to know until next preview build (also next stable is coming soon v3.5).

https://github.com/files-community/Files/blob/31d6fee922223af49bb20fc40e345300641044e9/src/Files.App/Utils/Storage/Helpers/FilesystemTasks.cs#L48

@yaira2 @hishitetsu fyi let me know it’d make us easy to investigate.

When preview build with this modification published, I’d like you all to paste log here.

**Comment by hishitetsu** [comment]
Is there any possibility of a timeout?
https://github.com/files-community/Files/blob/31d6fee922223af49bb20fc40e345300641044e9/src/Files.App/Data/Models/ItemViewModel.cs#L1616

**Comment by tw333k** [comment]
this started happening to me but when I try to open Network.
I've uninstalled/reinstalled but it's still the same.
<img width="629" alt="image" src="https://github.com/files-community/Files/assets/88950678/3cc4e02f-d020-47b9-981a-8e90da6af092">

**Comment by yaira2** [comment]
This appears to be resolved in v3.6.

**Comment by TCAtrevor** [comment]
This issue is certainly not resolved. I have still received this message on both 3.6 and now 3.7.
![image](https://github.com/user-attachments/assets/3843f865-e783-4593-8462-646e60b04719)
![image](https://github.com/user-attachments/assets/fba5cebd-2632-4dab-a34d-86ce41cc7592)

**Comment by yaira2** [comment]
How do you reproduce the bug? I created a shortcut as described and it works fine.

**Comment by TCAtrevor** [comment]
I'm not sure how it is reproduced. It seems like it's been a mystery for everyone else experiencing it too. I can provide my config if there's any chance that helps, but from my perspective, it's just a random on-and-off issue between my two computers.

**Comment by yaira2** [comment]
How are you accessing Recycle Bin, via the Sidebar?

**Comment by TCAtrevor** [comment]
Recycle Bin does not show up on the sidebar for me. I access it from the desktop icon provided by default on Windows.

**Comment by T-i-a-7** [comment]
@yaira2 As mentioned above, this bug is not currently reproducible. It occurs when the user opens the recycle bin using the icon on the desktop, but for some reason this bug does not happen all the time and for every user. Therefore, it is difficult to reproduce it.

**Comment by yaira2** [comment]
Is Files set as the default file manager?

**Comment by T-i-a-7** [comment]
Yes, but the bug occurs even when this setting is turned off.

**Comment by yaira2** [comment]
How do you reproduce the issue when Files is not the default file manager?

**Comment by T-i-a-7** [comment]
If I remeber correctly (The bug is not happening to me at the moment), you reproduce it by typing the bin directory (wich I don't remeber) directly in Files when it is set as default. But I could be wrong.

**Comment by yaira2** [comment]
I can't reproduce by entering `Shell:RecycleBinFolder` into the path bar, but I'll reopen this issue in case someone has a more reliable way to repro this.

**Comment by TCAtrevor** [comment]
I found another interesting workaround for this situation. If you drag the tab of the new window into an existing one, it is able to load.

https://github.com/user-attachments/assets/a0b43a84-030c-4fbf-ab19-52e01b82ae0a

**Comment by T-i-a-7** [comment]
Yes, it also does the same thing by changing the language in Files' settings

**Comment by Illustar0** [comment]
The same problem happened to me. Unfortunately, I couldn't find a way to reproduce it stably. But maybe you could try to modify the "Startup Settings"?

**Comment by Illustar0** [comment]
For me, this problem occurred after I modified the "Startup Settings", and I can reproduce it stably

**Comment by yaira2** [comment]
> For me, this problem occurred after I modified the "Startup Settings", and I can reproduce it stably

What did you set your settings to?

**Comment by Illustar0** [comment]
> > For me, this problem occurred after I modified the "Startup Settings", and I can reproduce it stably
> 
> What did you set your settings to?

1. Change "Startup Settings" to "Open New Tab"
2. Close Files
3. Open Files
4. Problem occurs

**Comment by Illustar0** [comment]
The only thing that is certain at the moment is that reinstalling Files can temporarily solve this problem, but you never know when it will happen again for what reason.

**Comment by Illustar0** [comment]
It's amazing. The problem just went away. I didn't do anything, but it just got better.

**Comment by Guiruo** [comment]
This problem still exists in the Files 3.7.7.0, but strangely enough, after reinstalling the Windows system, the problem of this drive popping up still exists. I can't determine where the problem is, but I can confirm that it is most likely not the problem of Files. Files work normally on multiple computers I tested with Windows To Go, without exception.

**Comment by Guiruo** [comment]
This problem still exists in the Files 3.7.7.0, but strangely, after reinstalling the Windows system, the problem of this drive popping up still exists. I can't determine where the problem is, but I can confirm that it is most likely not the problem of Files. I have used Windows To Go to test multiple computers, and Files are all working normally, without exception. If you use the Win + E shortcut to open the home page of Files, not the drive page. When you open this computer again, Recycle Bin, Network, etc., the folder with the Shell pin can be used normally. This is the strange problem. Of course, the system I tested is: Windows 11 Professional Workstation Edition 23H2 Build 22631.3737 The version of Files is: Files 3.7.7.0

**Comment by Guiruo** [comment]
> 目前唯一可以确定的是，重新安装 Files 可以暂时解决这个问题，但您永远不知道它何时会因什么原因再次发生。
The problem arises when, after reinstalling Files, if you disable the background permissions for Files and then perform a cold start, it still shows a NotAFolder error. This issue cannot be located in the logs, which is quite strange and seems to be a problem with the Windows system.

**Comment by Guiruo** [comment]
> It's amazing. The problem just went away. I didn't do anything, but it just got better.
This is merely a temporary disappearance of the issue, not a resolution. You never know how or when this problem will reoccur.

**Comment by Illustar0** [comment]
> > It's amazing. The problem just went away. I didn't do anything, but it just got better.
> 
> This is merely a temporary disappearance of the issue, not a resolution. You never know how or when this problem will reoccur.

I know. But it's really amazing, isn't it? We can't locate the problem, or even reproduce it stably.

**Comment by zr0fve** [comment]
This happens to me intermittently. I noticed it happen again recently. Don't know how to recreate it, maybe related to sleep? It was working before I made my desktop sleep then after a few hours when I wake my desktop again its back to being Shell:RecycleBinFolder

I'm on Windows 11 Pro 24H2

**Comment by niusia-ua** [comment]
I also experienced the same problem on Windows 11 Pro 24H2 (Files v3.9.1.0).
In my case, I can't open the recycle bin (mainly, using a desktop shortcut) in two cases:

1. When the Files isn't running yet (both not directly and in the background).
2. When I have unpinned the recycle bin from quick access.

**Comment by zr0fve** [comment]
I have my Files setup as

- Leave app running in background when the window is close - Yes
- Show Files icon in the System Tray - Yes

This happens to me when the App is left running for a while. I have quit it on the tray then re-open to fix the issue.

**Comment by KittyFarts** [comment]
I recently added a Bug report on this but didn't realize one was already opened - #16980 

I closed out the Files app from the system tray but no luck - same result.


   1. Used desktop shortcut and it automatically opened Files Insider Preview - 'Drive Unplugged - NotAFolder'
   2. Went to C:$Recycle.Bin on Files - shows as an empty folder (there are items in the Recycle Bin)
   3. Reverted back to Windows File Explorer - Recycle Bin opens normal.
   4. Went to C:$Recycle.Bin and files are there that are in the Recycle bin.

Running Files version 3.9.3.0, Windows 11 Enterprise 24H2 LTSC (26100.3476)

[debug.log](https://github.com/user-attachments/files/19439268/debug.log)

**Comment by Josh65-2201** [comment]
`C:$Recycle.Bin` is not a folder path, use shell:RecycleBinFolder

**Comment by KittyFarts** [comment]
> `C:$Recycle.Bin` is not a folder path, use shell:RecycleBinFolder

Same result, changes from shell:RecycleBinFolder to Корзина (Recycle Bin) and prompts the same "NotAFolder"

![Image](https://github.com/user-attachments/assets/8b9db1cd-ce07-4d6e-b1d3-139318da00e6)

**Comment by Guiruo** [comment]
It's really weird, it works fine on some systems, but some systems are problematic in the first place, and I think it's more likely that it's a problem with Files itself, which doesn't occur at all in older versions of Files.

**Comment by KittyFarts** [comment]
Also, I just tried it on my other PC that is on Windows 11 Pro for Workstations (26100.3476) that has Files version 3.9.1.0 installed. Same error message. At first I was able to see the folder and I emptied the contents within the Files app. The folders were gone but for some reason The trash bin is still full. After that is when the same error message comes up "Drive Unplugged - NotAFolder"

![Image](https://github.com/user-attachments/assets/98e28508-edcc-4386-9feb-d2c58b085713)

[debug.log](https://github.com/user-attachments/files/19444749/debug.log)

**Comment by KittyFarts** [comment]
Another update, seeing this error on the 'Network' Folder as well:

![Image](https://github.com/user-attachments/assets/b9f86236-6b52-41c5-a283-5041a4e9c470)

**Comment by Illustar0** [comment]
I reinstalled Windows 11 Pro 24H2 today and installed Flies on it. but when I restarted the computer and opened Files again, it told me “NotAFolder”

**Comment by Illustar0** [comment]
I think I've discovered an interesting phenomenon. The error only seems to occur on the first instance of Files that is started after booting. If I start another Files instance, the problem goes away. At least for me it does.
I also consulted the debug logs. Unfortunately, the logs do not contain any valid information

**Comment by mikedorsi** [comment]
Currently happening for me as well on latest version of Win11.

**Comment by yair100** [comment]
Can anyone reproduce this issue in v3.9.9?

**Comment by Illustar0** [comment]
> Can anyone reproduce this issue in v3.9.9?

I can. @yaira2 

![Image](https://github.com/user-attachments/assets/fd54f644-460f-42c6-9225-13dffd0c9423)

**Comment by random-guy9182** [comment]
I don't know where to download version 3.9.9 but I'm on 3.9.1.0 and I came to the same conclusion as Illustar0 before. Basically you have to open Files manually with the system tray background option enabled and then you can open the recycle bin without issues. Open on startup doesn't fix this.

**Comment by Illustar0** [comment]
> I don't know where to download version 3.9.9 but I'm on 3.9.1.0 and I came to the same conclusion as Illustar0 before. Basically you have to open Files manually with the system tray background option enabled and then you can open the recycle bin without issues. Open on startup doesn't fix this.

Visit https://files.community/download, click "Download Preview Version"

**Comment by yair100** [comment]
@Illustar0 can you repro if you change both the system and app language to English?

**Comment by Illustar0** [comment]
> [@Illustar0](https://github.com/Illustar0) can you repro if you change both the system and app language to English?

I changed both the system and Files app language to English, and the issue seems to have disappeared — I couldn’t reproduce it afterward.
That said, the bug was never consistently reproducible to begin with — it came and went unpredictably.
I’m afraid I’ll need to use it for a while longer to know for sure. I’ll update here if it happens again.

**Update**: @yaira2 I used the system in English for two days and didn’t experience the issue. But as soon as I switched back to Chinese, it immediately came back.

**Comment by zr0fve** [comment]
> I have my Files setup as
> 
>     * Leave app running in background when the window is close - Yes
> 
>     * Show Files icon in the System Tray - Yes
> 
> 
> This happens to me when the App is left running for a while. I have quit it on the tray then re-open to fix the issue.

For quite some time I stopped experiencing this issue for some reason. I'm on 3.9.1.0 - Though **I will report back if I see it again**

All I remember I did was to update to [Windows 11 24H2 KB5058499](https://www.reddit.com/r/nvidia/comments/1l1036u/psa_windows_11_24h2_kb5058499_fixes_solves_dxgi/) _(to fix some unrelated issue)_

**Comment by DeepakTCO** [comment]
Has this issue not been fixed yet? This only happens when u enable open at startup. If you open it manually no matter if for the first or whatever you won't face the issue. Kinda annoying for me as opening the app first time takes 3 seconds, so I use startup option

**Comment by Josh65-2201** [comment]
Not yet, this will be closed as complete when it is. People have also reported that it happen regardless of the leave running in background option

**Comment by yair100** [comment]
Users have been able to work around this by using the same localization option for Files and Windows.

**Comment by piknockyou** [comment]
**My Solution (Workaround):**

1. Navigate to *Settings* > *General*.
2. In the **Language** dropdown menu, select any language other than your current one.
3. When prompted to restart, choose one of the following options:
    * **To fix the issue quickly (and change the language):** Click **Yes**.
    * **To fix the issue and keep your original language:** Click **No**, re-select your original language from the dropdown, and then click **Yes** on the second restart prompt.

**Comment by AinaSnow** [comment]
I also encountered this problem. In fact, if you manually open Files once, it will not be triggered. If Files is not running, it will happen if you directly open the folder (if you have set up an alternative explorer).. I tried to unpin the recycle bin from the side in Files, but after unpinning it, the entire pinned content disappeared..

<img width="250" height="65" alt="Image" src="https://github.com/user-attachments/assets/fcf8bca6-e5d7-4a19-9812-92ddc8e0ee18" />

**Comment by Josh65-2201** [comment]
>  the entire pinned content disappeared

That is likely this #15410, please try the workaround there.

**Comment by ZZFFLL** [comment]
我的从Win+E或者桌面图标双击启动都会提示“NotAFolder”

<img width="2314" height="1438" alt="Image" src="https://github.com/user-attachments/assets/69298888-a7b5-4ca2-b3b6-998da9bfb872" />

**Comment by random-guy9182** [comment]
So i was gonna test the beta version or whatever its called but i just cant install it anymore.
Long story short, i did a bunch of windows tweaks and one of them was blocking all microsoft store connections and installs. Previously i had installed Files before the tweaks and now the installer just closes itself when i try it. So until theres an installer that doesnt use the ms store app its literally impossible for me to use Files again.
Also i will repeat that i had found a consistent way of triggering this bug and a workaround and you can find it if you scroll up a bit.

**Comment by Josh65-2201** [comment]
Files doesn't need the Microsoft store to install, it uses App installer that does nothing on it's own and has no reason to be uninstalled, There are other methods to install Files you can also try https://files.community/docs/getting-started/install

If you mean this comment https://github.com/files-community/Files/issues/15083#issuecomment-2781310297 . It's only consistent for you, It works for me with a cold open using the recycle bin on the desktop and many others aren't having that issue. Using `Shell:RecycleBinFolder` also doesn't always work as the person a few comment up tried and had the same error https://github.com/files-community/Files/issues/15083#issuecomment-2749630076

This is still something that can't be constantly reproduced by everyone or any of the Files team developers

**Comment by yair100** [comment]
> Previously i had installed Files before the tweaks and now the installer just closes itself when i try it. So until theres an installer that doesnt use the ms store app its literally impossible for me to use Files again.

@random-guy9182 Files doesn't require the Microsoft Store, but it does require some of the same services needed to install packaged apps. In any event, the bug reported here hasn't been resolved, but users can follow the workaround mentioned at the top of the issue.

**Comment by Illustar0** [comment]
The solution mentioned above is actually to completely restart Files. My guess is that this problem is caused by Files starting too early (just a guess!). Whether it's running Files a while after Windows startup is complete, or completely restarting Files or opening a brand new Files instance when the problem occurs, it can be observed that the problem no longer happens.

**Comment by Johen8** [comment]
I installed Files on two computers (at work and at home). On both of them I marked Files to be the default file manager and to start with Windows. On both machines when I turn on my computer Files is in that state where I can't open "This PC" or "Recycle Bin", but if I close it (through tray) and open again it works normally. My solution for now is to not start it with Windows, because then when I need it I have to wait a bit longer, but at least it's 100% functional.
Perhaps an option for a delayed start could be a compatibility solution?

**Comment by piknockyou** [comment]
> I installed Files on two computers (at work and at home). On both of them I marked Files to be the default file manager and to start with Windows. On both machines when I turn on my computer Files is in that state where I can't open "This PC" or "Recycle Bin", but if I close it (through tray) and open again it works normally. My solution for now is to not start it with Windows, because then when I need it I have to wait a bit longer, but at least it's 100% functional. Perhaps an option for a delayed start could be a compatibility solution?

Have you tried my [workaround](https://github.com/files-community/Files/issues/15083#issuecomment-3261801943)?

**Comment by Josh65-2201** [comment]
That workaround is no different to the first one listed at the top of this issue

**Comment by piknockyou** [comment]
@Josh65-2201  I respectfully disagree. My workaround is distinctly different from those listed at the top.

The current workarounds suggest:
1. Close Files from system tray and reopen
2. Use the same language option for Files and Windows (which could already be the case)

My workaround ([#15083 (comment)](https://github.com/files-community/Files/issues/15083#issuecomment-3261801943)) specifically involves:
1. Navigate to Settings > General
2. **Actively change** the language to a different one in the dropdown
3. When prompted to restart, choose one of the following options:
   - To fix the issue quickly (and change the language): Click **Yes**
   - To fix the issue and keep your original language: Click **No**, re-select your original language from the dropdown, and then click **Yes** on the second restart prompt

The key difference is that I'm suggesting an **active language switch process**, not just ensuring Files and Windows languages match from the start. This deliberate language change and restart sequence appears to refresh/reinitialize something in Files that resolves the issue.

Three users gave my comment a thumbs up, so I believe it's worth distinguishing from the existing workarounds.

**Comment by Illustar0** [comment]
I don't think so. These temporary workarounds are essentially all about completely restarting Files (except for keeping Files' language consistent with Windows).

**Comment by yair100** [comment]
> The key difference is that I'm suggesting an active language switch process, not just ensuring Files and Windows languages match from the start. This deliberate language change and restart sequence appears to refresh/reinitialize something in Files that resolves the issue.

This works, but has to be repeated every time the issue occurs. The workaround at the top of the issue is supposed to remove the issue altogether.

**Comment by Stephan-Sun** [comment]
I met same issue when I wake up computer from sleep after a night. Both stable and preview edition.

**Comment by yair100** [comment]
I'm excited to share an update regarding this issue. We're testing a potential fix in #17863.
