### ISSUE TITLE
Crashing when USB Drive plugged in

### ISSUE THREAD

**Issue by RitwikSHS10** [files-community/Files#15328]
### Description

Crashing when USB Drive plugged in

### Steps To Reproduce

stop its crashing?

### Requirements

- e.g. Fix crash that occurs when...
stop its crashing when USB is plugged in

### Files Version

3.3.1.0

### Windows Version

10.0.22631.3527

### Log File

2024-05-07 20:57:22.4953|Information|App launched. Launch args type: ProtocolActivatedEventArgs
2024-05-07 20:57:26.3923|Information|Adding cloud provider "OneDrive" mapped to C:\Users\ritwi\OneDrive
2024-05-07 20:57:27.2736|Information|Running on ARM: False
2024-05-07 20:57:28.4682|Information|Drive added: C:\, Fixed
2024-05-07 20:57:28.5942|Information|Drive added: D:\, Removable
2024-05-07 20:57:28.6805|Information|Drive added: D:\
2024-05-07 20:57:32.9308|Information|SIDELOAD: Checking for updates...
2024-05-07 20:57:34.5703|Information|SIDELOAD: Current Package Name: FilesPreview
2024-05-07 20:57:34.5711|Information|SIDELOAD: Remote Package Name: FilesPreview
2024-05-07 20:57:34.5714|Information|SIDELOAD: Current Version: 3.3.1.0
2024-05-07 20:57:34.5717|Information|SIDELOAD: Remote Version: 3.3.7.0
2024-05-07 20:57:34.5719|Information|SIDELOAD: Update found.
2024-05-07 20:57:34.5722|Information|SIDELOAD: Starting background download.
2024-05-07 20:57:48.6468|Information|Download time taken: 00:00:14
2024-05-07 21:03:25.3683|Information|Drive removed: \\?\STORAGE#Volume#{899f9b8a-c9b4-11ee-ae44-38d57a77aedc}#0000000000100000#{53f5630d-b6bf-11d0-94f2-00a0c91efb8b}
2024-05-07 21:03:26.1837|Information|Drive removed: D:
2024-05-07 21:04:15.4316|Information|Drive added: D:\
2024-05-07 21:04:16.2619|Information|Drive added: D:\
2024-05-07 21:04:24.4159|Information|The app is being activated. Activation type: ProtocolActivatedEventArgs
2024-05-07 21:05:39.7630|Information|Drive removed: \\?\STORAGE#Volume#{899f9b8a-c9b4-11ee-ae44-38d57a77aedc}#0000000000100000#{53f5630d-b6bf-11d0-94f2-00a0c91efb8b}
2024-05-07 21:05:40.6725|Information|Drive removed: D:
2024-05-07 21:05:48.3831|Information|Drive added: D:\
2024-05-07 21:05:49.1611|Information|Drive added: D:\
2024-05-07 21:05:56.1187|Information|The app is being activated. Activation type: ProtocolActivatedEventArgs
2024-05-07 21:06:22.1184|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:06:22.7388|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:06:24.5291|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:06:24.7620|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:06:26.5699|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:06:26.8240|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:06:27.8928|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:06:28.2711|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:06:29.3186|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:06:29.6439|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:06:30.7764|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:06:38.5811|Information|Drive removed: \\?\STORAGE#Volume#{899f9b8a-c9b4-11ee-ae44-38d57a77aedc}#0000000000100000#{53f5630d-b6bf-11d0-94f2-00a0c91efb8b}
2024-05-07 21:06:39.0153|Information|Drive removed: D:
2024-05-07 21:44:25.7288|Information|Drive added: D:\
2024-05-07 21:44:25.8860|Information|Drive added: D:\
2024-05-07 21:44:33.8155|Information|The app is being activated. Activation type: ProtocolActivatedEventArgs
2024-05-07 21:47:52.2984|Error|System.Runtime.InteropServices.COMException (0x80131500)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.ILayoutPreferencesDatabaseClassMethods.GetPreferences(IObjectReference _obj, String filePath, Nullable`1 frn)
   at Files.App.Data.Models.LayoutPreferencesManager.GetLayoutPreferencesForPath(String path)
   at Files.App.Data.Models.LayoutPreferencesManager.GetLayoutType(String path, Boolean changeLayoutMode)
   at Files.App.Views.Shells.ModernShellPage.NavigateToPath(String navigationPath, Type sourcePageType, NavigationArguments navArgs)
   at Files.App.ViewModels.UserControls.SidebarViewModel.HandleItemInvokedAsync(Object item, PointerUpdateKind pointerUpdateKind)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
2024-05-07 21:48:22.4416|Information|App launched. Launch args type: ProtocolActivatedEventArgs
2024-05-07 21:48:26.3772|Information|Adding cloud provider "OneDrive" mapped to C:\Users\ritwi\OneDrive
2024-05-07 21:48:27.5851|Information|Running on ARM: False
2024-05-07 21:48:27.6949|Information|Drive added: C:\, Fixed
2024-05-07 21:48:27.8807|Information|Drive added: D:\, Removable
2024-05-07 21:48:27.9669|Information|Drive added: D:\
2024-05-07 21:48:32.5085|Error|System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Specified cast is not valid.)
 ---> System.InvalidCastException: Specified cast is not valid.
   at WinRT.DelegateExtensions.DynamicInvokeAbi(Delegate del, Object[] invoke_params)
   at ABI.System.Collections.Generic.IEnumerator`1.get__Current()
   at ABI.System.Collections.Generic.IEnumerator`1.FromAbiHelper.MoveNext()
   at Files.App.Utils.FileTags.FileTagsHelper.UpdateTagsDb()
   at Files.App.Helpers.AppLifecycleHelper.InitializeAppComponentsAsync()
   at Files.App.App.<OnLaunched>g__ActivateAsync|44_0()
   --- End of inner exception stack trace ---
2024-05-07 21:48:49.5016|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:48:49.5195|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:48:49.5861|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:48:49.6094|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:48:49.6436|Information|System.Runtime.InteropServices.COMException (0x800706F4)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.IFileTagsDatabaseClassMethods.SetTags(IObjectReference _obj, String filePath, Nullable`1 frn, String[] tags)
   at Files.App.Utils.Storage.FileOperationsHelpers.<>c__DisplayClass17_1.<UpdateFileTagsDb>b__0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Action action, ILogger logger, Type exceptionToIgnore)
2024-05-07 21:51:17.1123|Information|The app is being activated. Activation type: ProtocolActivatedEventArgs

**Comment by yaira2** [comment]
Thank you for the report, v3.3.1 is an older preview build and is no longer supported. The latest preview build v3.3.7 shouldn't have this issue.
