### ISSUE TITLE
Cut-pasting a parent folder to a child folder crashes the app

### ISSUE THREAD

**Issue by soumyamahunt** [files-community/Files#1545]
**Describe the bug**
Cut-pasting a parent folder to a child folder crashes the app.

**To Reproduce**
1. Open files-uwp app.
2. Cut a folder which has children folders, i.e. cut "C:\Users\Documets\Test"
3. Try pasting it to a child folder, i.e. paste in "C:\Users\Documents\Test\ChildTest"

**Expected behavior**
The operation should prompt a dialog giving user to either skip or cancel the operation. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1903 18362.239
 - App version: v0.12.0

**Additional context**
Although there exists logic for handling this type of cases by showing dialog, but the dialog creation throws exception. Error log:
```
2020-07-23 10:56:09.3884|ERROR|Files.App|The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))|System.Exception: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))
   at Windows.UI.Xaml.Data.Binding..ctor()
   at Files.Interacts.Interaction.<>c__DisplayClass60_0.<<PasteItems>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Files.Interacts.Interaction.PasteItems(DataPackageView packageView, String destinationPath, DataPackageOperation acceptedOperation)
   at Files.Interacts.Interaction.PasteItem_ClickAsync(Object sender, RoutedEventArgs e)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

**Comment by yaichenbaum** [comment]
@soumyamahunt This issue should be resolved with #2742.
