### ISSUE TITLE
Unknown reasons cause a high probability of failing to display anything other than the drive when starting from the background

### ISSUE THREAD

**Issue by CookSleep** [files-community/Files#15742]
### Description

Unknown reasons cause a high probability of failing to display anything other than the drive when starting from the background
*This time I **did not** enable "Set Files as the default file manager"*

### Steps To Reproduce

1. When Files is already running in the background, start it
2. Everything except the drive disappeared!
![PixPin_2024-07-02_17-50-28](https://github.com/files-community/Files/assets/151028412/4b22a9f4-0beb-458b-b834-7247bee053df)

### Requirements

Fix this strange issue, but honestly, I don't know why...
Anyway, it has indeed been happening frequently recently :(

### Files Version

3.5.0.0

### Windows Version

1000.22700.1009.0

### Log File

[debug.log](https://github.com/user-attachments/files/16066390/debug.log)

**Comment by 0x5bfa** [comment]
```

System.Runtime.InteropServices.COMException (0x80004005): 未指定的错误

未指定的错误

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.System.Collections.Specialized.NotifyCollectionChangedEventHandler.NativeDelegateWrapper.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Files.Shared.Extensions.LinqExtensions.AddSorted[T](IList`1 list, T item)
   at Files.App.ViewModels.UserControls.Widgets.DrivesWidgetViewModel.<Drives_CollectionChanged>b__36_0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Func`1 action, ILogger logger, Type exceptionToIgnore)

``` 

Wasn’t this caused by being without interlock?

**Comment by 0x5bfa** [comment]
What happens when you click a drive card?

**Comment by CookSleep** [comment]
> What happens when you click a drive card?

It opens normally, but the items in the sidebar still won't come back. To restore everything to its original state, you need to exit and reopen Files😣

**Comment by yaira2** [comment]
Thank you for the report, the solution mentioned here often helps https://github.com/files-community/Files/issues/15410#issuecomment-2160835642.

Either way, we're going to continue looking for a proper solution and will continue tracking this in #15410.
