### ISSUE TITLE
cant set files as default explorer

### ISSUE THREAD

**Issue by prathambahekar** [files-community/Files#16172]
### Description

https://github.com/user-attachments/assets/942b9da0-2029-400c-ad04-0212b6acaa0d

### Steps To Reproduce

i even tried developer build. its showing the same

### Requirements

- e.g. Fix crash that occurs when...
i even tried by finding setdefault.reg filw but then it is showing some explorer error

### Files Version

3.7.0.0

### Windows Version

10.0.22631.4112

### Log File

   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionWithTelemetryAsync(HttpRequestMessage request, HttpConnectionPool pool, Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.Metrics.MetricsHandler.SendAsyncWithMetrics(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Files.App.Services.SideloadUpdateService.CheckForUpdatesAsync()
2024-09-10 10:21:34.5740|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-09-10 10:21:36.6662|Warning|Google Drive registry key for key name 'Software\Google\DriveFS' not found.
2024-09-10 10:21:37.0544|Information|Adding cloud provider "OneDrive" mapped to C:\Users\Pratham's Laptop\OneDrive
2024-09-10 10:21:37.4528|Information|Drive added: C:\, Fixed
2024-09-10 10:21:37.5134|Information|Drive added: D:\, Fixed
2024-09-10 10:21:38.6336|Information|SIDELOAD: Checking for updates...
2024-09-10 10:21:38.6402|Error|System.Net.Http.HttpRequestException: No such host is known. (cdn.files.community:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionWithTelemetryAsync(HttpRequestMessage request, HttpConnectionPool pool, Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.Metrics.MetricsHandler.SendAsyncWithMetrics(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Files.App.Services.SideloadUpdateService.CheckForUpdatesAsync()
2024-09-10 10:22:30.9091|Information|Running on ARM: False
2024-09-10 11:13:12.4270|Information|Drive added: \\?\vivo 1904\
2024-09-10 11:13:19.2114|Information|Drive removed: \\?\USB#VID_2D95&PID_6002#PZX8PBFYDEMBDM75#{6ac27878-a6fa-4155-ba85-f98f491d4f33}
2024-09-10 11:13:20.3948|Information|Drive added: \\?\vivo 1904\
2024-09-10 11:13:21.3907|Information|Drive removed: \\?\USB#VID_2D95&PID_6002#PZX8PBFYDEMBDM75#{6ac27878-a6fa-4155-ba85-f98f491d4f33}
2024-09-10 11:13:21.7891|Information|Drive added: \\?\vivo 1904\
2024-09-10 11:14:57.5594|Information|Drive removed: \\?\USB#VID_2D95&PID_6002#PZX8PBFYDEMBDM75#{6ac27878-a6fa-4155-ba85-f98f491d4f33}
2024-09-10 11:17:45.3621|Information|Drive added: \\?\vivo 1904\
2024-09-10 11:18:10.6827|Information|Drive removed: \\?\USB#VID_2D95&PID_6003&MI_00#6&2e2a08d5&0&0000#{6ac27878-a6fa-4155-ba85-f98f491d4f33}
2024-09-10 12:12:07.8001|Information|Drive added: E:\
2024-09-10 12:19:33.5244|Information|Drive added: F:\
2024-09-10 12:20:05.0115|Information|Drive removed: E:
2024-09-10 12:20:06.0124|Information|Drive removed: F:
2024-09-10 12:23:10.9767|Information|SIDELOAD: Checking for updates...
2024-09-10 12:23:11.2808|Information|The app is being activated. Activation type: LaunchActivatedEventArgs
2024-09-10 12:23:11.3650|Warning|Google Drive registry key for key name 'Software\Google\DriveFS' not found.
2024-09-10 12:23:11.4291|Information|Drive added: C:\, Fixed
2024-09-10 12:23:11.5142|Information|Drive added: D:\, Fixed
2024-09-10 12:23:16.7297|Information|SIDELOAD: Current Package Name: Files
2024-09-10 12:23:16.7300|Information|SIDELOAD: Remote Package Name: Files
2024-09-10 12:23:16.7302|Information|SIDELOAD: Current Version: 3.7.0.0
2024-09-10 12:23:16.7305|Information|SIDELOAD: Remote Version: 3.7.0.0
2024-09-10 12:23:16.7308|Warning|SIDELOAD: Update not found.
2024-09-10 12:37:00.7820|Information|SIDELOAD: Checking for updates...
2024-09-10 12:37:01.0666|Information|The app is being activated. Activation type: LaunchActivatedEventArgs
2024-09-10 12:37:01.1496|Warning|Google Drive registry key for key name 'Software\Google\DriveFS' not found.
2024-09-10 12:37:02.0130|Information|Drive added: C:\, Fixed
2024-09-10 12:37:02.0379|Information|Drive added: D:\, Fixed
2024-09-10 12:37:02.9682|Information|SIDELOAD: Current Package Name: Files
2024-09-10 12:37:02.9685|Information|SIDELOAD: Remote Package Name: Files
2024-09-10 12:37:02.9686|Information|SIDELOAD: Current Version: 3.7.0.0
2024-09-10 12:37:02.9687|Information|SIDELOAD: Remote Version: 3.7.0.0
2024-09-10 12:37:02.9689|Warning|SIDELOAD: Update not found.
2024-09-10 13:00:17.7600|Information|SIDELOAD: Checking for updates...
2024-09-10 13:00:17.7990|Information|The app is being activated. Activation type: LaunchActivatedEventArgs
2024-09-10 13:00:17.8929|Warning|Google Drive registry key for key name 'Software\Google\DriveFS' not found.
2024-09-10 13:00:17.9808|Information|Drive added: C:\, Fixed
2024-09-10 13:00:18.0010|Information|Drive added: D:\, Fixed
2024-09-10 13:00:20.5688|Information|SIDELOAD: Current Package Name: Files
2024-09-10 13:00:20.5692|Information|SIDELOAD: Remote Package Name: Files
2024-09-10 13:00:20.5693|Information|SIDELOAD: Current Version: 3.7.0.0
2024-09-10 13:00:20.5694|Information|SIDELOAD: Remote Version: 3.7.0.0
2024-09-10 13:00:20.5697|Warning|SIDELOAD: Update not found.
2024-09-10 13:02:23.1007|Information|SIDELOAD: Checking for updates...
2024-09-10 13:02:23.1386|Information|The app is being activated. Activation type: LaunchActivatedEventArgs
2024-09-10 13:02:23.2329|Warning|Google Drive registry key for key name 'Software\Google\DriveFS' not found.
2024-09-10 13:02:23.3087|Information|Drive added: C:\, Fixed
2024-09-10 13:02:23.3295|Information|Drive added: D:\, Fixed
2024-09-10 13:02:23.6143|Information|SIDELOAD: Current Package Name: Files
2024-09-10 13:02:23.6145|Information|SIDELOAD: Remote Package Name: Files
2024-09-10 13:02:23.6146|Information|SIDELOAD: Current Version: 3.7.0.0
2024-09-10 13:02:23.6149|Information|SIDELOAD: Remote Version: 3.7.0.0
2024-09-10 13:02:23.6153|Warning|SIDELOAD: Update not found.
2024-09-10 13:06:33.5457|Information|SIDELOAD: Checking for updates...
2024-09-10 13:06:33.5821|Information|The app is being activated. Activation type: LaunchActivatedEventArgs
2024-09-10 13:06:33.6546|Warning|Google Drive registry key for key name 'Software\Google\DriveFS' not found.
2024-09-10 13:06:33.7208|Information|Drive added: C:\, Fixed
2024-09-10 13:06:33.7469|Information|Drive added: D:\, Fixed
2024-09-10 13:06:37.4102|Information|SIDELOAD: Current Package Name: Files
2024-09-10 13:06:37.4108|Information|SIDELOAD: Remote Package Name: Files
2024-09-10 13:06:37.4112|Information|SIDELOAD: Current Version: 3.7.0.0
2024-09-10 13:06:37.4114|Information|SIDELOAD: Remote Version: 3.7.0.0
2024-09-10 13:06:37.4119|Warning|SIDELOAD: Update not found.
2024-09-10 22:36:56.4552|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-09-10 22:36:58.1253|Warning|Google Drive registry key for key name 'Software\Google\DriveFS' not found.
2024-09-10 22:36:58.4255|Information|Adding cloud provider "OneDrive" mapped to C:\Users\Pratham's Laptop\OneDrive
2024-09-10 22:36:58.7739|Information|Drive added: C:\, Fixed
2024-09-10 22:36:58.9495|Information|Drive added: D:\, Fixed
2024-09-10 22:36:59.7183|Information|SIDELOAD: Checking for updates...
2024-09-10 22:37:01.3018|Information|SIDELOAD: Current Package Name: Files
2024-09-10 22:37:01.3021|Information|SIDELOAD: Remote Package Name: Files
2024-09-10 22:37:01.3023|Information|SIDELOAD: Current Version: 3.7.0.0
2024-09-10 22:37:01.3024|Information|SIDELOAD: Remote Version: 3.7.0.0
2024-09-10 22:37:01.3027|Warning|SIDELOAD: Update not found.
2024-09-10 22:43:05.4901|Information|Running on ARM: False

**Comment by yaira2** [comment]
This can happen if the file permissions for the Windows Apps folder have been modified. Unfortunately, repairing the permissions is very difficult, and the only known solution is to reinstall Windows.

**Comment by Josh65-2201** [comment]
Please also upload the log file and don't copy and paste the text for future issues.

**Comment by prathambahekar** [comment]
> This can happen if the file permissions for the Windows Apps folder have been modified. Unfortunately, repairing the permissions is very difficult, and the only known solution is to reinstall Windows.

but i already reinstall it last week and still facing this issue

**Comment by yaira2** [comment]
Can you also confirm that your using the admin account?

**Comment by prathambahekar** [comment]
> Can you also confirm that your using the admin account?

how can i do that

**Comment by prathambahekar** [comment]
> Can you also confirm that your using the admin account?
![Screenshot 2024-09-10 225410](https://github.com/user-attachments/assets/c476fc83-1d9a-495e-9284-0ef828539a75)
is this enough??

**Comment by yaira2** [comment]
Yes
