### ISSUE TITLE
Unable to run as administrator

### ISSUE THREAD

**Issue by mpgoodall** [files-community/Files#16278]
### Description

I have installed Files as a non-admin... When right-clicking on the Files app in the start menu, there is an option to "Run as administrator". When I do this, it does present a UAC prompt but then fails to open... It attempts to launch, but then a werfault.exe process is also spawned and it appears to crash. I don't get to see any messages.

If I run CMD as administrator and attempt to install it from there, it launches the install window with re-install and launch... If I click launch, it opens but does not seem to be running as administrator. If I attempt to re-install it makes no difference.

These are AD user accounts with administrator privileges, not local administrator accounts.

### Steps To Reproduce

1. Click Start
2. Right-click Files app > Run as administrator
3. UAC Prompt > Enter credentials
4. Nothing is displayed/open

### Requirements

Opens Files as the user with the credentials used.

### Files Version

\\svsccm01\D$\Program Files\Microsoft Configuration Manager\Logs

### Windows Version

10.0.22631

### User ID

files-community

### Log File

[debug.log](https://github.com/user-attachments/files/17181603/debug.log)

This log file is from my non-admin account. I was not able to find a debug.log file under my admin account.

**Comment by yaira2** [comment]
Which version of Files are you using?

**Comment by mpgoodall** [comment]
Sorry, added the wrong paste, I have updated the request now - Files Version: 3.7.7.0 - Windows version: 10.0.22631.4169

**Comment by 0x5bfa** [comment]
werfault is Windows Error Report and sounds like your Windows recognizes this fault. Can you check if there's an entry for this incident in Event Viewer (Windows logs > Application)?

**Comment by mpgoodall** [comment]
Yep, there is. I have sanitised computer/user

Log Name:      Application
Source:        .NET Runtime
Date:          30/09/2024 12:23:00 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      XXXXXXXXXXXXXXXXXX
Description:
Application: Files.exe
CoreCLR Version: 8.0.724.31311
.NET Version: 8.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80070520): A specified logon session does not exist. It may already have been terminated.

A specified logon session does not exist. It may already have been terminated.

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.Windows.AppLifecycle.IAppInstanceMethods.GetActivatedEventArgs(IObjectReference _obj)
   at Files.App.Program.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-09-30T02:23:00.4871230Z" />
    <EventRecordID>216665</EventRecordID>
    <Correlation />
    <Execution ProcessID="102644" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>XXXXXXXXXXXXXXXXXX</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Files.exe
CoreCLR Version: 8.0.724.31311
.NET Version: 8.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80070520): A specified logon session does not exist. It may already have been terminated.

A specified logon session does not exist. It may already have been terminated.

   at WinRT.ExceptionHelpers.&lt;ThrowExceptionForHR&gt;g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.Windows.AppLifecycle.IAppInstanceMethods.GetActivatedEventArgs(IObjectReference _obj)
   at Files.App.Program.Main()
</Data>
  </EventData>
</Event>



Log Name:      Application
Source:        Application Error
Date:          30/09/2024 12:23:00 PM
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          XXXXXXXXXXXXXXXXXX
Computer:      XXXXXXXXXXXXXXXXXX
Description:
Faulting application name: Files.exe, version: 1.0.0.0, time stamp: 0x666b0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4111, time stamp: 0x03c619d0
Exception code: 0xe0434352
Fault offset: 0x000000000005fabc
Faulting process id: 0x0x190F4
Faulting application start time: 0x0x1DB12DFAABADFF4
Faulting application path: C:\Program Files\WindowsApps\Files_3.7.7.0_x64__1y0xx7n9077q4\Files.App\Files.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: bfaf0929-c0ac-4a0f-99c1-912ddc905d20
Faulting package full name: Files_3.7.7.0_x64__1y0xx7n9077q4
Faulting package-relative application ID: App
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-09-30T02:23:00.6063482Z" />
    <EventRecordID>216666</EventRecordID>
    <Correlation />
    <Execution ProcessID="102896" ThreadID="102900" />
    <Channel>Application</Channel>
    <Computer>XXXXXXXXXXXXXXXXXX</Computer>
    <Security UserID="XXXXXXXXXXXXXXXXXX" />
  </System>
  <EventData>
    <Data Name="AppName">Files.exe</Data>
    <Data Name="AppVersion">1.0.0.0</Data>
    <Data Name="AppTimeStamp">666b0000</Data>
    <Data Name="ModuleName">KERNELBASE.dll</Data>
    <Data Name="ModuleVersion">10.0.22621.4111</Data>
    <Data Name="ModuleTimeStamp">03c619d0</Data>
    <Data Name="ExceptionCode">e0434352</Data>
    <Data Name="FaultingOffset">000000000005fabc</Data>
    <Data Name="ProcessId">0x190f4</Data>
    <Data Name="ProcessCreationTime">0x1db12dfaabadff4</Data>
    <Data Name="AppPath">C:\Program Files\WindowsApps\Files_3.7.7.0_x64__1y0xx7n9077q4\Files.App\Files.exe</Data>
    <Data Name="ModulePath">C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data Name="IntegratorReportId">bfaf0929-c0ac-4a0f-99c1-912ddc905d20</Data>
    <Data Name="PackageFullName">Files_3.7.7.0_x64__1y0xx7n9077q4</Data>
    <Data Name="PackageRelativeAppId">App</Data>
  </EventData>
</Event>

**Comment by 0x5bfa** [comment]
The error codes seem to be ERROR_NO_SUCH_LOGON_SESSION and EXCEPTION_COMPLUS.

Is your Windows controlled by an organization or something? Or modified version of Windows?

**Comment by mpgoodall** [comment]
In a way, so yes it is a corporate computer connected to an AD domain, the version of Windows isn't modified... But yes I am logging on as a non-admin AD user and trying to run the app as an admin AD user... I am not logged onto the computer interactively as my AD admin account and there are no local admin accounts...

**Comment by yaira2** [comment]
Do credentials for the local admin account work?

**Comment by mpgoodall** [comment]
No, same issue. FYI UAC settings are set to Always notify... I can launch something like the UWP app Terminal the way I am trying to launch Files.... I ran files as admin on my own personal machine, which did work but it also had an additional message box, which I am failing to recall what it said exactly but it was within the Files app, oh right I think it said something about not being able to drag and drop but otherwise it worked fine. In that scenario the user for on my personal machine was already admin though, so I'll have to re-test with a non-admin account and then try to run as admin

**Comment by cobdev** [comment]
Hi everyone, I'd like to say that we're seeing this behavior as well. Here's our scenario:

- Windows 11 Enterprise (24H2)
- Files v3.8.0.0 (classic installer)
- Able to launch with standard domain user account
- Unable to launch using "Run as Administrator" option 

We were hoping to use Files as a tool for our admin users who generally stay logged on with their standard (unprivileged) accounts throughout the day. In the event they do need to perform an administrative file operation, they're launching other (inferior) tools like XYPlorer or Explorer++ using the "Run as Administrator" function and then supplying their alternate (administrative credentials). Those applications are then running with the elevated/administrative privileges of the other account.

**Here's what the application log says after each attempt:**

Faulting application name: Files.exe, version: 1.0.0.0, time stamp: 0x666b0000
Faulting module name: KERNELBASE.dll, version: 10.0.26100.1591, time stamp: 0x3e0f7b9b
Exception code: 0xe0434352
Fault offset: 0x00000000000c6d9a
Faulting process id: 0x5164
Faulting application start time: 0x1DB45A6AB1FCFF9
Faulting application path: C:\Program Files\WindowsApps\Files_3.8.0.0_x64__1y0xx7n9077q4\Files.App\Files.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 26233106-47bf-4037-8ab4-c16378133dce
Faulting package full name: Files_3.8.0.0_x64__1y0xx7n9077q4
Faulting package-relative application ID: App

Application: Files.exe
CoreCLR Version: 8.0.724.31311
.NET Version: 8.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80070520): A specified logon session does not exist. It may already have been terminated.

A specified logon session does not exist. It may already have been terminated.

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.Windows.AppLifecycle.IAppInstanceMethods.GetActivatedEventArgs(IObjectReference _obj)
   at Files.App.Program.Main()

**Comment by TheVodouch** [comment]
> Hi everyone, I'd like to say that we're seeing this behavior as well. Here's our scenario:
> 
>     * Windows 11 Enterprise (24H2)
> 
>     * Files v3.8.0.0 (classic installer)
> 
>     * Able to launch with standard domain user account
> 
>     * Unable to launch using "Run as administrator" or "Run as other user" options
> 
> 
> We were hoping to use Files as a tool for our admin users who generally stay logged on with their standard (unprivileged) accounts throughout the day. In the event they do need to perform an administrative file operation, they're launching other (inferior) tools like XYPlorer or Explorer++ using either of the "Run as administrator" or "Run as different user" functions and then supplying their alternate (administrative credentials). Those applications are then running with the elevated/administrative privileges of the other account.
> 
> FYI: I'd suggest updating the title of this bug to be "ability run as other user" as I think this is what's failing here...
> 
> As a test, if I grant my standard domain account "local administrator" privileges, then the "Run as Administrator" option DOES work. I think what's actually needed is the ability to launch the app via a separate process, under alternative credentials.
> 
> **Here's what the application log says after each attempt:**
> 
> Faulting application name: Files.exe, version: 1.0.0.0, time stamp: 0x666b0000 Faulting module name: KERNELBASE.dll, version: 10.0.26100.1591, time stamp: 0x3e0f7b9b Exception code: 0xe0434352 Fault offset: 0x00000000000c6d9a Faulting process id: 0x5164 Faulting application start time: 0x1DB45A6AB1FCFF9 Faulting application path: C:\Program Files\WindowsApps\Files_3.8.0.0_x64__1y0xx7n9077q4\Files.App\Files.exe Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll Report Id: 26233106-47bf-4037-8ab4-c16378133dce Faulting package full name: Files_3.8.0.0_x64__1y0xx7n9077q4 Faulting package-relative application ID: App
> 
> Application: Files.exe CoreCLR Version: 8.0.724.31311 .NET Version: 8.0.7 Description: The process was terminated due to an unhandled exception. Exception Info: System.Runtime.InteropServices.COMException (0x80070520): A specified logon session does not exist. It may already have been terminated.
> 
> A specified logon session does not exist. It may already have been terminated.
> 
> at WinRT.ExceptionHelpers.g__Throw|39_0(Int32 hr) at ABI.Microsoft.Windows.AppLifecycle.IAppInstanceMethods.GetActivatedEventArgs(IObjectReference _obj) at Files.App.Program.Main()

We're having the same issue in our environment. System admins here have two accounts one with more basic access and the other "admin" account with higher privileges. When we're logged on with the basic account and need to run Files with the admin account we get the same error and sometimes get a pop up window saying that ‘the system cannot find the file specified’.

**Comment by Kermer** [comment]
+1
Mainly working on user account, when trying to run Files as admin (different account) it crashes.

Win 11, Files 3.9.1.0.

<details><summary>A specified logon session does not exist. It may already have been terminated.</summary>

```
Application: Files.exe
CoreCLR Version: 8.0.724.31311
.NET Version: 8.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80070520): A specified logon session does not exist. It may already have been terminated.

A specified logon session does not exist. It may already have been terminated.

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.Windows.AppLifecycle.IAppInstanceMethods.GetActivatedEventArgs(IObjectReference _obj)
   at Files.App.Program.Main()
```

</details>
