### ISSUE TITLE
Horizontal tab: The app crashes when trying to open a new tab

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#1641]
**Edit:** This happens if "Multitasking flyout" is disabled

Log:

2020-08-03 22:21:50.1164|ERROR|Files.App|Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.Controls.InteractionViewModel.set_TabStripSelectedIndex(Int32 value)
   at Files.UserControls.HorizontalMultitaskingControl.horizontalTabView_TabItemsChanged(TabView sender, IVectorChangedEventArgs args)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Insert(Int32 index, T item)
   at Files.Views.MainPage.AddNewTab(Type t, String path, Int32 atIndex)
   at Files.UserControls.HorizontalMultitaskingControl.TabView_AddTabButtonClick(TabView sender, Object args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()

**Comment by osieltorres** [comment]
I have been facing same issue, but in my case, I only disabled this multitasking flyout option on settings, then I tried to open a new tab, and app crashes.

**Comment by XPoppyX** [comment]
I confirm that it crashes after disabling "Multitasking Flyout"

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue was resolved in our stable branch and should be available from the Microsoft Store.
