### ISSUE TITLE
Bug: Slow right click panel

### ISSUE THREAD

**Issue by Diego-VRFP** [files-community/Files#16440]
### Description

When I right-click on files, the panel appears without any problems, but when I right-click on a folder, the panel freezes for a few seconds and then lets me select options. Also, a couple of times when I right-click on different files and folders to check the speed at which I can interact with the panel, Files suddenly closes. If I put the shell extensions without a submenu, I see that until they load, I can't interact with the panel, so I don't know if that's what's slowing it down.

### Steps To Reproduce

1-Right click on a folder
2-Locked context menu panel
3-Wait several seconds for the shell extensions to load
4-Context menu panel unlocked

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

### User ID

f9452645-268a-402c-8a07-991100aa7da4

### Log File

2024-11-05 12:26:51.1050|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-11-05 12:26:53.2920|Information|Adding cloud provider "OneDrive" mapped to D:\Diego\OneDrive
2024-11-05 12:26:54.0150|Information|Running on ARM: False
2024-11-05 12:26:54.0942|Information|Drive added: C:\, Fixed
2024-11-05 12:26:54.2765|Information|Drive added: D:\, Fixed
2024-11-05 12:26:57.3088|Information|SIDELOAD: Checking for updates...
2024-11-05 12:26:58.0661|Information|SIDELOAD: Current Package Name: Files
2024-11-05 12:26:58.0664|Information|SIDELOAD: Remote Package Name: Files
2024-11-05 12:26:58.0666|Information|SIDELOAD: Current Version: 3.3.0.0
2024-11-05 12:26:58.0668|Information|SIDELOAD: Remote Version: 3.7.11.0
2024-11-05 12:26:58.0670|Information|SIDELOAD: Update found.
2024-11-05 12:26:58.0671|Information|SIDELOAD: Starting background download.
2024-11-05 12:27:01.7752|Information|Download time taken: 00:00:03
2024-11-05 12:34:40.1734|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-11-05 12:34:42.4555|Information|Adding cloud provider "OneDrive" mapped to D:\Diego\OneDrive
2024-11-05 12:34:42.7800|Information|Drive added: C:\, Fixed
2024-11-05 12:34:42.8689|Information|Drive added: D:\, Fixed
2024-11-05 12:34:44.8958|Information|SIDELOAD: Checking for updates...
2024-11-05 12:34:45.7185|Information|SIDELOAD: Current Package Name: Files
2024-11-05 12:34:45.7187|Information|SIDELOAD: Remote Package Name: Files
2024-11-05 12:34:45.7189|Information|SIDELOAD: Current Version: 3.7.11.0
2024-11-05 12:34:45.7190|Information|SIDELOAD: Remote Version: 3.7.11.0
2024-11-05 12:34:45.7191|Warning|SIDELOAD: Update not found.
2024-11-05 12:35:51.5075|Warning|System.Runtime.InteropServices.COMException (0x800705B4): Se devolvió esta operación porque se agotó el tiempo de espera. (0x800705B4)
   at Vanara.PInvoke.Shell32.IShellLinkW.Resolve(HWND hwnd, SLR_FLAGS fFlags)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Utils.Storage.FileOperationsHelpers.ParseLinkAsync(String linkPath)
2024-11-05 12:35:51.5234|Information|Running on ARM: False
2024-11-05 12:38:34.1832|Warning|System.Runtime.InteropServices.COMException (0x800705B4): Se devolvió esta operación porque se agotó el tiempo de espera. (0x800705B4)
   at Vanara.PInvoke.Shell32.IShellLinkW.Resolve(HWND hwnd, SLR_FLAGS fFlags)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Utils.Storage.FileOperationsHelpers.ParseLinkAsync(String linkPath)
2024-11-05 12:38:40.7963|Warning|System.Runtime.InteropServices.COMException (0x800705B4): Se devolvió esta operación porque se agotó el tiempo de espera. (0x800705B4)
   at Vanara.PInvoke.Shell32.IShellLinkW.Resolve(HWND hwnd, SLR_FLAGS fFlags)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Utils.Storage.FileOperationsHelpers.ParseLinkAsync(String linkPath)
2024-11-05 12:38:40.9365|Warning|System.Runtime.InteropServices.COMException (0x800705B4): Se devolvió esta operación porque se agotó el tiempo de espera. (0x800705B4)
   at Vanara.PInvoke.Shell32.IShellLinkW.Resolve(HWND hwnd, SLR_FLAGS fFlags)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Utils.Storage.FileOperationsHelpers.ParseLinkAsync(String linkPath)
2024-11-05 12:42:39.3385|Information|SIDELOAD: Checking for updates...
2024-11-05 12:42:39.3856|Information|The app is being activated. Activation type: LaunchActivatedEventArgs
2024-11-05 12:42:39.6870|Information|Drive added: C:\, Fixed
2024-11-05 12:42:39.7794|Information|Drive added: D:\, Fixed
2024-11-05 12:42:40.0622|Information|SIDELOAD: Current Package Name: Files
2024-11-05 12:42:40.0625|Information|SIDELOAD: Remote Package Name: Files
2024-11-05 12:42:40.0626|Information|SIDELOAD: Current Version: 3.7.11.0
2024-11-05 12:42:40.0627|Information|SIDELOAD: Remote Version: 3.7.11.0
2024-11-05 12:42:40.0628|Warning|SIDELOAD: Update not found.
2024-11-05 12:48:26.5484|Information|The app is being activated. Activation type: FileActivatedEventArgs
2024-11-05 12:49:02.6825|Information|The app is being activated. Activation type: FileActivatedEventArgs
2024-11-05 12:54:54.3633|Information|The app is being activated. Activation type: FileActivatedEventArgs
2024-11-05 12:59:55.8345|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-11-05 12:59:56.4883|Information|Adding cloud provider "OneDrive" mapped to D:\Diego\OneDrive
2024-11-05 12:59:56.7715|Information|Drive added: C:\, Fixed
2024-11-05 12:59:56.8805|Information|Running on ARM: False
2024-11-05 12:59:56.9156|Information|Drive added: D:\, Fixed
2024-11-05 12:59:59.0194|Information|SIDELOAD: Checking for updates...
2024-11-05 12:59:59.5675|Information|SIDELOAD: Current Package Name: Files
2024-11-05 12:59:59.5678|Information|SIDELOAD: Remote Package Name: Files
2024-11-05 12:59:59.5680|Information|SIDELOAD: Current Version: 3.7.11.0
2024-11-05 12:59:59.5681|Information|SIDELOAD: Remote Version: 3.7.11.0
2024-11-05 12:59:59.5682|Warning|SIDELOAD: Update not found.
2024-11-05 13:01:33.5926|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-11-05 13:01:34.0396|Information|Adding cloud provider "OneDrive" mapped to D:\Diego\OneDrive
2024-11-05 13:01:34.5441|Information|Drive added: C:\, Fixed
2024-11-05 13:01:34.6156|Information|Running on ARM: False
2024-11-05 13:01:34.6464|Information|Drive added: D:\, Fixed
2024-11-05 13:01:36.6126|Information|SIDELOAD: Checking for updates...
2024-11-05 13:01:37.0714|Information|SIDELOAD: Current Package Name: Files
2024-11-05 13:01:37.0717|Information|SIDELOAD: Remote Package Name: Files
2024-11-05 13:01:37.0719|Information|SIDELOAD: Current Version: 3.7.11.0
2024-11-05 13:01:37.0720|Information|SIDELOAD: Remote Version: 3.7.11.0
2024-11-05 13:01:37.0721|Warning|SIDELOAD: Update not found.
2024-11-05 13:13:35.1098|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-11-05 13:13:35.7703|Information|Adding cloud provider "OneDrive" mapped to D:\Diego\OneDrive
2024-11-05 13:13:36.0749|Information|Drive added: C:\, Fixed
2024-11-05 13:13:36.2044|Information|Running on ARM: False
2024-11-05 13:13:36.3728|Information|Drive added: D:\, Fixed
2024-11-05 13:13:38.3381|Information|SIDELOAD: Checking for updates...
2024-11-05 13:13:38.9960|Information|SIDELOAD: Current Package Name: Files
2024-11-05 13:13:38.9963|Information|SIDELOAD: Remote Package Name: Files
2024-11-05 13:13:38.9965|Information|SIDELOAD: Current Version: 3.7.11.0
2024-11-05 13:13:38.9967|Information|SIDELOAD: Remote Version: 3.7.11.0
2024-11-05 13:13:38.9968|Warning|SIDELOAD: Update not found.

**Comment by Diego-VRFP** [comment]
I already had the shell extensions in a submenu and I tried to remove them from the submenu to see if it would do something and that's when I realized that until that was loaded I couldn't interact with the panel.
No, I'm not using a column layout, I'm using the grid layout

**Comment by yaira2** [comment]
Do you have a lot of options in the sub menu?

**Comment by Diego-VRFP** [comment]
In the folders I have 11 options in the submenu, but in the submenu when I right-click on a .exe, for example, I have 14 and in this case it is not slow or takes a long time to load, it only happens in the folders.

**Comment by BedBug2479** [comment]
Same happening for me

it takes a good 1-2 sec to show the right-click menu for a folder/file

**Comment by yaira2** [comment]
Can you send a screenshot of the extensions? It's possible there is an extension that's only present for folders which is slowing down the menu,

**Comment by BedBug2479** [comment]
> Can you send a screenshot of the extensions? It's possible there is an extension that's only present for folders which is slowing down the menu,

below extensions are present in the folder where it takes time to right-click
- rar
- mkv hevc (1gb+ each too many)
- folders
- zip
- 1 or 2 txt

should i send a ss?

**Comment by yaira2** [comment]
I meant the list of shell extensions for folders compared to files. This can help narrow down if there is a specific shell extension that's slowing down the menu. In any event, we're going to continue tracking this in #11112.

**Comment by BedBug2479** [comment]
> I meant the list of shell extensions for folders compared to files. This can help narrow down if there is a specific shell extension that's slowing down the menu on your device. In any event, we're going to continue tracking this in [#11112](https://github.com/files-community/Files/issues/11112).

not sure how to do " list of shell extensions for folders compared to files"

**Comment by Diego-VRFP** [comment]
These are the differences I see when I open the context menu on an .exe and a folder:
EXE:
Nanazip, Notepad++, Unlock with File Locksmith, Notepad, Change name with PowerRename, Add to favorites, Fix compatibility issues, Unlock with File Locksmith (again?), Scan with Malwarebytes, Change name with PowerRename (again?), Restore previous versions and Pin to start menu.
Folder:
Nanazip, Unlock with File Locksmith, Open with Visual Studio, Search in Adobe Bridge, Restore previous versions, Change Folder Icon (from folderico program), Scan with Malwarebytes, Unlock with File Locksmith (again?) and Pin to start menu.

**Comment by BedBug2479** [comment]
for EXE
![Image](https://github.com/user-attachments/assets/df64e9f2-48e2-4c43-baac-276a19f3c3bd)

for Folder
![Image](https://github.com/user-attachments/assets/72bf393f-2304-4b1e-9437-303c723d2d3f)

**Comment by Diego-VRFP** [comment]
The duplicates are from PowerToys and I see them with Windows Explorer as well. Regarding Notepad++, I don't know what it has to do with it, because Notepad++ doesn't appear in the context menu of the folders, which is what slows it down, it only appears in other types of files.

**Comment by yaira2** [comment]
My apologies, I thought the issue was only with files. Can you check if disabling PowerToys solves the issue?

**Comment by Diego-VRFP** [comment]
It's because of Folderico, which allows you to have direct access to various icon libraries from the context menu. If I remove those libraries, the context menu for folders loads faster. The thing is that this doesn't happen with Windows Explorer, but I don't care about not having those libraries with quick access.

**Comment by yaira2** [comment]
Thank you for the update. The reason you’re not experiencing the issue in File Explorer is because of its heavy caching. While Files does implement basic caching, it isn't as robust as what File Explorer offers. We’re actively exploring ways to improve caching in Files and will continue to monitor this issue in #11112.
