### ISSUE TITLE
Bug: Files app crashes when opening context menu in column layout view with right click

### ISSUE THREAD

**Issue by JackSparrow006** [files-community/Files#16588]
### Description

Description:
The Files app immediately crashes when attempting to open the right-click context menu while in column layout view. The crash occurs consistently on every right-click attempt, making it impossible to access context menu options in this view mode. 

The app crashes completely without any error message or warning, requiring a reopening to continue using the application. This issue specifically occurs only in the column layout view - other view modes (grid, list, details) work normally with context menu.

### Steps To Reproduce

1. Open Files app
2. Switch to column layout view
3. Right-click on any file or folder
4. App crashes immediately or viewing snaps to the left + Content menu glitches

### Files Version

3.8.0.0

### Windows Version

23h2

### Log File

2024-12-07 23:17:39.5560|Information|SIDELOAD: Current Version: 3.8.0.0
2024-12-07 23:17:39.5562|Information|SIDELOAD: Remote Version: 3.8.0.0
2024-12-07 23:17:39.5565|Warning|SIDELOAD: Update not found.
2024-12-07 23:18:14.9206|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-12-07 23:18:15.5035|Information|Adding cloud provider "Proton Drive" mapped to C:\Users\Name - Razer\Proton Drive\-UserID-
2024-12-07 23:18:16.6077|Information|Drive added: C:\, Fixed
2024-12-07 23:18:16.8821|Information|Running on ARM: False
2024-12-07 23:18:21.5287|Information|SIDELOAD: Checking for updates...
2024-12-07 23:18:22.1016|Information|SIDELOAD: Current Package Name: Files
2024-12-07 23:18:22.1019|Information|SIDELOAD: Remote Package Name: Files
2024-12-07 23:18:22.1021|Information|SIDELOAD: Current Version: 3.8.0.0
2024-12-07 23:18:22.1022|Information|SIDELOAD: Remote Version: 3.8.0.0
2024-12-07 23:18:22.1028|Warning|SIDELOAD: Update not found.
2024-12-08 08:41:02.1673|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-12-08 08:41:06.4232|Information|Adding cloud provider "Proton Drive" mapped to C:\Users\Name - Razer\Proton Drive\-UserID-
2024-12-08 08:41:07.4250|Information|Drive added: C:\, Fixed
2024-12-08 08:41:07.6180|Information|Running on ARM: False
2024-12-08 08:41:11.0646|Information|SIDELOAD: Checking for updates...
2024-12-08 08:41:11.7380|Information|SIDELOAD: Current Package Name: Files
2024-12-08 08:41:11.7383|Information|SIDELOAD: Remote Package Name: Files
2024-12-08 08:41:11.7388|Information|SIDELOAD: Current Version: 3.8.0.0
2024-12-08 08:41:11.7396|Information|SIDELOAD: Remote Version: 3.8.0.0
2024-12-08 08:41:11.7399|Warning|SIDELOAD: Update not found.
2024-12-08 09:48:32.5061|Information|SIDELOAD: Checking for updates...
2024-12-08 09:48:32.5721|Information|The app is being activated. Activation type: LaunchActivatedEventArgs
2024-12-08 09:48:32.9953|Information|SIDELOAD: Current Package Name: Files
2024-12-08 09:48:32.9956|Information|SIDELOAD: Remote Package Name: Files
2024-12-08 09:48:32.9957|Information|SIDELOAD: Current Version: 3.8.0.0
2024-12-08 09:48:32.9958|Information|SIDELOAD: Remote Version: 3.8.0.0
2024-12-08 09:48:32.9959|Warning|SIDELOAD: Update not found.
2024-12-08 09:48:34.5734|Information|System.Runtime.InteropServices.COMException (0x80004005): Unspecified error

Unspecified error

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.System.Collections.Specialized.NotifyCollectionChangedEventHandler.NativeDelegateWrapper.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.Collection`1.Remove(T item)
   at Files.App.ViewModels.UserControls.Widgets.DrivesWidgetViewModel.<Drives_CollectionChanged>b__28_0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Func`1 action, ILogger logger, Type exceptionToIgnore)
2024-12-08 09:48:34.7607|Information|Drive added: C:\, Fixed
2024-12-08 09:48:34.9586|Information|System.Runtime.InteropServices.COMException (0x80004005): Unspecified error

Unspecified error

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.System.Collections.Specialized.NotifyCollectionChangedEventHandler.NativeDelegateWrapper.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Files.Shared.Extensions.LinqExtensions.AddSorted[T](IList`1 list, T item)
   at Files.App.ViewModels.UserControls.Widgets.DrivesWidgetViewModel.<Drives_CollectionChanged>b__28_0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Func`1 action, ILogger logger, Type exceptionToIgnore)
2024-12-08 11:37:00.2378|Information|SIDELOAD: Checking for updates...
2024-12-08 11:37:00.7335|Information|SIDELOAD: Current Package Name: Files
2024-12-08 11:37:00.7340|Information|SIDELOAD: Remote Package Name: Files
2024-12-08 11:37:00.7343|Information|SIDELOAD: Current Version: 3.8.0.0
2024-12-08 11:37:00.7346|Information|SIDELOAD: Remote Version: 3.8.0.0
2024-12-08 11:37:00.7348|Warning|SIDELOAD: Update not found.
2024-12-08 11:37:00.9952|Information|The app is being activated. Activation type: LaunchActivatedEventArgs
2024-12-08 11:37:01.7578|Information|Drive added: C:\, Fixed
2024-12-08 13:09:13.8907|Information|SIDELOAD: Checking for updates...
2024-12-08 13:09:14.6721|Information|The app is being activated. Activation type: LaunchActivatedEventArgs
2024-12-08 13:09:21.0703|Information|SIDELOAD: Current Package Name: Files
2024-12-08 13:09:21.0717|Information|SIDELOAD: Remote Package Name: Files
2024-12-08 13:09:21.0725|Information|SIDELOAD: Current Version: 3.8.0.0
2024-12-08 13:09:21.0732|Information|SIDELOAD: Remote Version: 3.8.0.0
2024-12-08 13:09:21.0738|Warning|SIDELOAD: Update not found.
2024-12-08 13:09:29.5253|Information|Drive added: C:\, Fixed
2024-12-08 13:09:34.6395|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-12-08 13:09:45.0588|Information|Adding cloud provider "Proton Drive" mapped to C:\Users\Name- Razer\Proton Drive\-UserID-
2024-12-08 13:09:48.1086|Information|Drive added: C:\, Fixed
2024-12-08 13:09:49.4120|Information|Running on ARM: False
2024-12-08 13:10:05.6886|Information|SIDELOAD: Checking for updates...
2024-12-08 13:10:07.0590|Information|SIDELOAD: Current Package Name: Files
2024-12-08 13:10:07.0600|Information|SIDELOAD: Remote Package Name: Files
2024-12-08 13:10:07.0608|Information|SIDELOAD: Current Version: 3.8.0.0
2024-12-08 13:10:07.0616|Information|SIDELOAD: Remote Version: 3.8.0.0
2024-12-08 13:10:07.0624|Warning|SIDELOAD: Update not found.
2024-12-08 13:15:42.2155|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-12-08 13:15:43.1366|Information|Adding cloud provider "Proton Drive" mapped to C:\Users\Name - Razer\Proton Drive\-UserID-
2024-12-08 13:15:44.2534|Information|Drive added: C:\, Fixed
2024-12-08 13:15:45.1218|Information|Running on ARM: False
2024-12-08 13:15:56.2315|Information|SIDELOAD: Checking for updates...
2024-12-08 13:15:56.8560|Information|SIDELOAD: Current Package Name: Files
2024-12-08 13:15:56.8565|Information|SIDELOAD: Remote Package Name: Files
2024-12-08 13:15:56.8567|Information|SIDELOAD: Current Version: 3.8.0.0
2024-12-08 13:15:56.8569|Information|SIDELOAD: Remote Version: 3.8.0.0
2024-12-08 13:15:56.8571|Warning|SIDELOAD: Update not found.
2024-12-08 13:16:42.4593|Error|System.Runtime.InteropServices.COMException (0x80004005): FileSaveDialog returned invalid shell item.
   at Files.App.Services.CommonDialogService.Open_FileOpenDialog(IntPtr hWnd, Boolean pickFoldersOnly, String[] filters, SpecialFolder defaultFolder, String& filePath)
2024-12-08 13:31:56.6105|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-12-08 13:31:57.4986|Information|Adding cloud provider "Proton Drive" mapped to C:\Users\Name - Razer\Proton Drive\-UserID-
2024-12-08 13:31:58.7923|Information|Drive added: C:\, Fixed
2024-12-08 13:32:00.8165|Information|Running on ARM: False
2024-12-08 13:32:09.6338|Information|SIDELOAD: Checking for updates...
2024-12-08 13:32:10.6156|Information|SIDELOAD: Current Package Name: Files
2024-12-08 13:32:10.6160|Information|SIDELOAD: Remote Package Name: Files
2024-12-08 13:32:10.6162|Information|SIDELOAD: Current Version: 3.8.0.0
2024-12-08 13:32:10.6164|Information|SIDELOAD: Remote Version: 3.8.0.0
2024-12-08 13:32:10.6165|Warning|SIDELOAD: Update not found.
2024-12-08 13:37:05.5543|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-12-08 13:37:05.5941|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-12-08 13:37:17.1386|Information|Adding cloud provider "Proton Drive" mapped to C:\Users\Name - Razer\Proton Drive\-UserID-
2024-12-08 13:37:17.1470|Information|Adding cloud provider "Proton Drive" mapped to C:\Users\Name - Razer\Proton Drive\-UserID-
2024-12-08 13:37:20.0821|Information|Drive added: C:\, Fixed
2024-12-08 13:37:21.3213|Information|Drive added: C:\, Fixed
2024-12-08 13:37:22.0511|Information|Running on ARM: False
2024-12-08 13:37:22.0577|Information|Running on ARM: False
2024-12-08 13:37:39.4052|Information|SIDELOAD: Checking for updates...
2024-12-08 13:37:40.3754|Information|SIDELOAD: Current Package Name: Files
2024-12-08 13:37:40.3756|Information|SIDELOAD: Current Package Name: Files
2024-12-08 13:37:40.3759|Information|SIDELOAD: Remote Package Name: Files
2024-12-08 13:37:40.3766|Information|SIDELOAD: Remote Package Name: Files
2024-12-08 13:37:40.3770|Information|SIDELOAD: Current Version: 3.8.0.0
2024-12-08 13:37:40.3772|Information|SIDELOAD: Current Version: 3.8.0.0
2024-12-08 13:37:40.3774|Information|SIDELOAD: Remote Version: 3.8.0.0
2024-12-08 13:37:40.3781|Warning|SIDELOAD: Update not found.
2024-12-08 13:37:40.3780|Warning|SIDELOAD: Update not found.
2024-12-08 13:39:10.3701|Information|The app is being activated. Activation type: ProtocolActivatedEventArgs
2024-12-08 13:39:32.4797|Information|The app is being activated. Activation type: ProtocolActivatedEventArgs

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #16193 . You can check there or click subscribe in the right sidebar for updates.
In future please upload the log file and don't copy and paste the contents.
