### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by hgkleene** [files-community/Files#16609]
### Description

Since I installed and reinstalled your program, it happens regularly that the app "hangs" after clicking through as I do in Windows Explorer or that it closes itself during use. It seems that it (after starting) cannot keep up with the clicking of the mouse. Not even when this happens quietly. I would like to see a solution for this.

### Steps To Reproduce

-

### Files Version

3.8.0.0

### Windows Version

Windows 11, version 23H2

### User ID

4fb43b16-47f0-4c02-9812-857840ec7fd5

### Log File

**Comment by Josh65-2201** [comment]
Thanks for the report
- Can you please upload (Do not copy and paste content) the debug.log file directly to GitHub (email attachments don't work) . You can get it in Files settings > About > Open log folder.
- Can you provide the steps to reproduce this issue, including what your clicking

**Comment by hgkleene** [comment]
at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Func`1 action, ILogger logger, Type exceptionToIgnore)
2024-12-24 12:34:31.6375|Information|Drive added: J:\, Fixed
2024-12-24 12:34:31.6391|Information|System.Runtime.InteropServices.COMException (0x80004005): Niet nader omschreven fout

Niet nader omschreven fout

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.System.Collections.Specialized.NotifyCollectionChangedEventHandler.NativeDelegateWrapper.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Files.Shared.Extensions.LinqExtensions.AddSorted[T](IList`1 list, T item)
   at Files.App.ViewModels.UserControls.Widgets.DrivesWidgetViewModel.<Drives_CollectionChanged>b__28_0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Func`1 action, ILogger logger, Type exceptionToIgnore)
2024-12-24 12:34:31.6746|Information|Drive added: K:\, Fixed
2024-12-24 12:34:31.7225|Information|System.Runtime.InteropServices.COMException (0x80004005): Niet nader omschreven fout

Niet nader omschreven fout

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.System.Collections.Specialized.NotifyCollectionChangedEventHandler.NativeDelegateWrapper.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.Collection`1.Remove(T item)
   at Files.App.ViewModels.UserControls.Widgets.DrivesWidgetViewModel.<Drives_CollectionChanged>b__28_0()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Func`1 action, ILogger logger, Type exceptionToIgnore)
2024-12-25 12:16:42.4192|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-12-25 12:16:45.2282|Information|Drive added: C:\, Fixed
2024-12-25 12:16:45.3533|Information|Drive added: D:\, Fixed
2024-12-25 12:16:45.3945|Information|Drive added: E:\, Fixed
2024-12-25 12:16:45.7203|Information|Drive added: F:\, Fixed
2024-12-25 12:16:45.7721|Warning|Invalid path: S:\My Drive
2024-12-25 12:16:45.8594|Warning|Invalid path: S:\My Drive
2024-12-25 12:16:45.9037|Information|Adding cloud provider "iCloud Drive" mapped to E:\iCloudDrive
2024-12-25 12:16:46.0677|Information|Drive added: G:\, Fixed
2024-12-25 12:16:46.4620|Information|Drive added: H:\, Fixed
2024-12-25 12:16:46.6287|Information|Drive added: J:\, Fixed
2024-12-25 12:16:46.7243|Information|Adding cloud provider "iCloud Photos" mapped to C:\Users\hgkle\Pictures\iCloud Photos\Photos
2024-12-25 12:16:46.7321|Information|Drive added: K:\, Fixed
2024-12-25 12:16:46.9229|Information|Adding cloud provider "Dropbox" mapped to E:\Dropbox
2024-12-25 12:16:46.9787|Information|Drive added: K:\
2024-12-25 12:16:47.0063|Information|Drive added: J:\
2024-12-25 12:16:47.1091|Information|Adding cloud provider "OneDrive" mapped to E:\OneDrive
2024-12-25 12:17:04.5277|Information|STORE: Checking for updates...
2024-12-25 12:17:06.0055|Information|Running on ARM: False
2024-12-26 12:11:27.6797|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-12-26 12:11:29.6953|Information|Drive added: C:\, Fixed
2024-12-26 12:11:29.7638|Information|Drive added: D:\, Fixed
2024-12-26 12:11:29.9220|Information|Drive added: E:\, Fixed
2024-12-26 12:11:29.9588|Information|Drive added: F:\, Fixed
2024-12-26 12:11:30.0645|Information|Drive added: G:\, Fixed
2024-12-26 12:11:30.0683|Warning|Invalid path: S:\My Drive
2024-12-26 12:11:30.0744|Warning|Invalid path: S:\My Drive
2024-12-26 12:11:30.0889|Information|Adding cloud provider "iCloud Drive" mapped to E:\iCloudDrive
2024-12-26 12:11:30.1230|Information|Drive added: H:\, Fixed
2024-12-26 12:11:30.1862|Information|Drive added: J:\, Fixed
2024-12-26 12:11:30.2338|Information|Drive added: K:\, Fixed
2024-12-26 12:11:30.2658|Information|Adding cloud provider "iCloud Photos" mapped to C:\Users\hgkle\Pictures\iCloud Photos\Photos
2024-12-26 12:11:30.3371|Information|Drive added: K:\
2024-12-26 12:11:30.3649|Information|Drive added: J:\
2024-12-26 12:11:30.3781|Information|Adding cloud provider "Dropbox" mapped to E:\Dropbox
2024-12-26 12:11:30.4863|Information|Adding cloud provider "OneDrive" mapped to E:\OneDrive
2024-12-26 12:11:44.0779|Information|STORE: Checking for updates...
2024-12-27 11:19:00.3458|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-12-27 11:19:02.6150|Information|Drive added: C:\, Fixed
2024-12-27 11:19:02.7026|Information|Drive added: D:\, Fixed
2024-12-27 11:19:02.7459|Information|Drive added: E:\, Fixed
2024-12-27 11:19:02.9942|Information|Drive added: F:\, Fixed
2024-12-27 11:19:03.0157|Warning|Invalid path: S:\My Drive
2024-12-27 11:19:03.0225|Warning|Invalid path: S:\My Drive
2024-12-27 11:19:03.0245|Information|Adding cloud provider "iCloud Drive" mapped to E:\iCloudDrive
2024-12-27 11:19:03.0465|Information|Drive added: G:\, Fixed
2024-12-27 11:19:03.1182|Information|Drive added: H:\, Fixed
2024-12-27 11:19:03.1860|Information|Drive added: J:\, Fixed
2024-12-27 11:19:03.2392|Information|Adding cloud provider "iCloud Photos" mapped to C:\Users\hgkle\Pictures\iCloud Photos\Photos
2024-12-27 11:19:03.2508|Information|Drive added: K:\, Fixed
2024-12-27 11:19:03.3789|Information|Adding cloud provider "Dropbox" mapped to E:\Dropbox
2024-12-27 11:19:03.3909|Information|Drive added: K:\
2024-12-27 11:19:03.4216|Information|Drive added: J:\
2024-12-27 11:19:03.4962|Information|Adding cloud provider "OneDrive" mapped to E:\OneDrive
2024-12-27 11:19:25.6340|Information|STORE: Checking for updates...
2024-12-27 11:24:00.7406|Information|Running on ARM: False
2024-12-27 12:19:35.0689|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-12-27 12:19:37.1936|Information|Drive added: C:\, Fixed
2024-12-27 12:19:37.2612|Information|Drive added: D:\, Fixed
2024-12-27 12:19:37.4449|Information|Drive added: E:\, Fixed
2024-12-27 12:19:37.4933|Information|Drive added: F:\, Fixed
2024-12-27 12:19:37.5783|Information|Drive added: G:\, Fixed
2024-12-27 12:19:37.5917|Warning|Invalid path: S:\My Drive
2024-12-27 12:19:37.5976|Warning|Invalid path: S:\My Drive
2024-12-27 12:19:37.5991|Information|Adding cloud provider "iCloud Drive" mapped to E:\iCloudDrive
2024-12-27 12:19:37.6307|Information|Drive added: H:\, Fixed
2024-12-27 12:19:37.6835|Information|Drive added: J:\, Fixed
2024-12-27 12:19:37.7215|Information|Drive added: K:\, Fixed
2024-12-27 12:19:37.7679|Information|Adding cloud provider "iCloud Photos" mapped to C:\Users\hgkle\Pictures\iCloud Photos\Photos
2024-12-27 12:19:37.8461|Information|Adding cloud provider "Dropbox" mapped to E:\Dropbox
2024-12-27 12:19:37.8630|Information|Drive added: K:\
2024-12-27 12:19:37.8879|Information|Drive added: J:\
2024-12-27 12:19:37.9407|Information|Adding cloud provider "OneDrive" mapped to E:\OneDrive
2024-12-27 12:19:50.2031|Information|STORE: Checking for updates...
2024-12-27 12:19:59.7426|Information|Drive added: L:\
2024-12-27 12:20:00.2625|Information|Drive added: L:\
2024-12-27 12:20:03.5810|Information|Running on ARM: False
2024-12-28 11:55:37.8947|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-12-28 11:55:40.9247|Information|Drive added: C:\, Fixed
2024-12-28 11:55:40.9869|Information|Drive added: D:\, Fixed
2024-12-28 11:55:41.1542|Information|Drive added: E:\, Fixed
2024-12-28 11:55:41.1982|Information|Drive added: F:\, Fixed
2024-12-28 11:55:41.2784|Warning|Invalid path: S:\My Drive
2024-12-28 11:55:41.2842|Warning|Invalid path: S:\My Drive
2024-12-28 11:55:41.2858|Information|Adding cloud provider "iCloud Drive" mapped to E:\iCloudDrive
2024-12-28 11:55:41.3036|Information|Drive added: G:\, Fixed
2024-12-28 11:55:41.3562|Information|Drive added: H:\, Fixed
2024-12-28 11:55:41.3970|Information|Drive added: J:\, Fixed
2024-12-28 11:55:41.4212|Information|Adding cloud provider "iCloud Photos" mapped to C:\Users\hgkle\Pictures\iCloud Photos\Photos
2024-12-28 11:55:41.4280|Information|Drive added: K:\, Fixed
2024-12-28 11:55:41.4684|Information|Drive added: L:\, Removable
2024-12-28 11:55:41.5426|Information|Adding cloud provider "Dropbox" mapped to E:\Dropbox
2024-12-28 11:55:41.5710|Information|Drive added: L:\
2024-12-28 11:55:41.5936|Information|Drive added: K:\
2024-12-28 11:55:41.6209|Information|Drive added: J:\
2024-12-28 11:55:41.6691|Information|Adding cloud provider "OneDrive" mapped to E:\OneDrive
2024-12-28 11:55:55.3554|Information|STORE: Checking for updates...
2024-12-28 11:55:55.9414|Information|Running on ARM: False
2024-12-28 14:12:33.0638|Information|STORE: Checking for updates...
2024-12-28 14:12:33.1807|Information|The app is being activated. Activation type: LaunchActivatedEventArgs
2024-12-28 14:12:33.5145|Information|Drive added: C:\, Fixed
2024-12-28 14:12:33.5511|Information|Drive added: D:\, Fixed
2024-12-28 14:12:33.6045|Information|Drive added: E:\, Fixed
2024-12-28 14:12:33.6722|Information|Drive added: F:\, Fixed
2024-12-28 14:12:33.7158|Information|Drive added: G:\, Fixed
2024-12-28 14:12:33.7565|Information|Drive added: H:\, Fixed
2024-12-28 14:12:33.8009|Information|Drive added: J:\, Fixed
2024-12-28 14:12:47.2556|Information|Drive added: K:\, Fixed
2024-12-28 14:12:47.6685|Information|Drive added: L:\, Removable
2024-12-28 14:14:26.2777|Information|The app is being activated. Activation type: ProtocolActivatedEventArgs
