### ISSUE TITLE
The app crashes when trying to open drive properties

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#2340]
It crashes when I try to see the properties of any drive, from the sidebar and the folder / explorer

**LOG:**

2020-11-14 21:04:38.4166|ERROR|Files.App|Value cannot be null.
Parameter name: path1|System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Files.View_Models.SelectedItemsPropertiesViewModel.get_IsReadOnly()
   at Files.PropertiesGeneral.PropertiesGeneral_obj1_Bindings.Update_ViewModel(SelectedItemsPropertiesViewModel obj, Int32 phase)
   at Files.PropertiesGeneral.PropertiesGeneral_obj1_Bindings.Update_(PropertiesGeneral obj, Int32 phase)
   at Files.PropertiesGeneral.PropertiesGeneral_obj1_Bindings.Update()
   at Files.PropertiesGeneral.PropertiesGeneral_obj1_Bindings.Initialize()
   at Files.PropertiesGeneral.PropertiesGeneral_obj1_Bindings.Loading(FrameworkElement src, Object data)

**Comment by gave92** [comment]
After #2337 😅
