### ISSUE TITLE
The app crashes when trying to restart it after changing the language

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#2873]
**To Reproduce**
1. Go to Settings > Preferences
2. Change the language of the app to any other
3. You will see the message to restart the app
4. Click on "Yes"
5. When trying to start the app, it crashes

**Screenshots**
![crash](https://user-images.githubusercontent.com/61259627/103841489-7850ff00-5072-11eb-88d9-ae7ddef3728e.gif)

**Log**
2021-01-06 22:55:59.5161|INFO|Files.App|App activated|
2021-01-06 22:55:59.5992|ERROR|Files.App|Index was outside the bounds of the array.|System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Files.App.OnActivated(IActivatedEventArgs args)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()

**Comment by yaichenbaum** [comment]
@XPoppyX This issue should resolved with #2879.
