### ISSUE TITLE
Paste images from Clipboard is broken

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Files#3690]
**Describe the bug**
Pasting images from Clipboard to folders is broken since updating to 1.3.0.0

**To Reproduce**
1. Copy an image to clipboard
2. Ctrl+V to folder
3. Image is not created

**Expected behavior**
A new image should be created

**Log file**
FullTrust exception:
```
2021-02-23 08:19:09.3194|INFO|FilesFullTrust.Win32API|COM object that has been separated from its underlying RCW cannot be used.|System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr pUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at Vanara.PInvoke.Shell32.SHGetImageList(SHIL iImageList, Guid& riid, IImageList& ppv)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize)
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
```

**Comment by gave92** [comment]
@d2dyno1 I don't think we use the fulltrustprocess for that functionality, and the exception you posted is handled (it's related to some icons not appearing, but should not be the cause of this issue)

**Comment by d2dyno1** [comment]
hmm 🤔

**Comment by winston-de** [comment]
@d2dyno1 I noticed that there is a bug where keyboard shortcuts stop working, including Ctrl+V. If you manually paste through more options, does it work?

**Comment by gave92** [comment]
Pasting images works fine for me in 1.3. Sometimes though when I open the app all shortcuts are not working as @winston-de says.

**Comment by d2dyno1** [comment]
> Pasting images works fine for me in 1.3. Sometimes though when I open the app all shortcuts are not working as @winston-de says.

Yes, I have the same issue

**Comment by winston-de** [comment]
#3702

**Comment by gave92** [comment]
Merging with #3702
