### ISSUE TITLE
"Drive Unplugged" message appears when you restart it after changing the language

### ISSUE THREAD

**Issue by Rick-HM** [files-community/Files#3983]
**1-** Change the language

**2-** Restart the app

**3-** You see the following message:
![Captura de pantalla (37)](https://user-images.githubusercontent.com/61259627/110845925-f061be00-8289-11eb-9f0a-ec6bb6804ed4.png)

--------------

### I noticed that when restarting, the uri for "new tab" appears in the previous language:

In this case, I changed the language from  SPANISH to ENGLISH. After restarting, in the address bar, "New tab" appears in Spanish

![crash2](https://user-images.githubusercontent.com/61259627/110846835-fefca500-828a-11eb-9197-0a36ce505103.gif)

--------------------

**Log:**
`2021-03-11 16:27:48.9954|ERROR|Files.Helpers.PathNormalization|Nueva pestaña\|System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Files.Helpers.PathNormalization.NormalizePath(String path)
2021-03-11 16:28:10.6568|ERROR|Files.App|Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.Helpers.AdaptiveLayoutHelpers.PredictLayoutMode(FolderSettingsViewModel folderSettings, ItemViewModel filesystemViewModel)
   at Files.ViewModels.ItemViewModel.RapidAddItemsToCollectionAsync(String path, String previousDir, Boolean useCache)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
`

**Comment by gave92** [comment]
Could you test again with latest main? After 726926c

**Comment by XPoppyX** [comment]
@gave92 

![Captura de pantalla 2021-03-11 172327](https://user-images.githubusercontent.com/61259627/110850401-83045c00-828e-11eb-94d1-a66e67337400.png)

**Comment by gave92** [comment]
But no crash?

**Comment by XPoppyX** [comment]
now it does not crash

**Comment by deadlybreakdown** [comment]
I also receive this error message when trying to connect to any server share or network drive. Win 10 2004.

**Comment by SHADOW-XIII** [comment]
I had this issue appeared just after updating today.
Turns out the first tab, opened before on "Home" was not loading (and was blank), opened Home again there and stopped showing the issue
Looks like something broke loading "Home" between versions
