### ISSUE TITLE
Double Folder Created Crash On Open

### ISSUE THREAD

**Issue by evancjohnson** [files-community/Files#4303]
**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Go to a folder
2. Create a new folder
3. Click on the folder 
4. App stops no message

**Expected behavior**
The folder opens properly

**Logfile**
[crash.txt](https://github.com/files-community/Files/files/6206648/crash.txt)
Attached but this is the exception
``` 
2021-03-25 12:17:26.6269|ERROR|FilesFullTrust.Program|Pipe is broken.|System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at FilesFullTrust.Win32API.<SendMessageAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FilesFullTrust.Program.<Watcher_Changed>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: Windows 10 Enterprise 20H2 19042.867
 - App version: V1.5

**Additional comment**
I restarted and tried to add a folder in the same spot with no issue. Fair note I did turn off cache files and folders for better performance when attempting again.

I also just updated to the newest version.

**Comment by gave92** [comment]
From other similar issues, it's turning off the cache that does the trick.

**Comment by evancjohnson** [comment]
Do you guys have any sort of opt in crash analytics that I could turn on to help when the application crashes?

**Comment by gave92** [comment]
There's actually an automatic crash reporting system. But error logs without description/steps to reproduce are often not that useful, so github issues are very valuable to us.

**Comment by evancjohnson** [comment]
Are you guys using MS AppCenter for crash reporting?

**Comment by gave92** [comment]
@evancjohnson yeah.

**Comment by evancjohnson** [comment]
You can attach files with AppCenter when you track an exception, [MS Docs](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp#handled-errors) which should allow you to upload the logs along with crash context for a little bit more help in the case that people don't go to github

**Comment by gave92** [comment]
Thanks @evancjohnson, basically we currently collect the stacktrace / crash log which contains the error + lines of code involved and Appcenter adds OS version, app version and locale.
The above + github has given good results up to know.

**Comment by gave92** [comment]
Merging with #4282

**Comment by evancjohnson** [comment]
@gave92 Mind if I add the callback to upload the logs in a PR?

**Comment by gave92** [comment]
@evancjohnson why not, but I'd suggest opening a new issue about it first, so the proposa can be evaluated by the other contributors before you spend time on it.
