### ISSUE TITLE
Crash when trying to delete library folder.

### ISSUE THREAD

**Issue by tsvietOK** [files-community/Files#4428]
**Explain the bug**
Crash when trying to delete library folder.
**To reproduce**
1. Go to Home tab
2. Create new library.
3. Delete this new library
4. Crash

**Logfile**
```
2021-04-02 22:25:36.8038|ERROR|Files.App|Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.Views.ModernShellPage.get_StatusCenterActions()
   at Files.Filesystem.FilesystemHelpers.DeleteItemAsync(IStorageItemWithPath source, Boolean showDialog, Boolean permanently, Boolean registerHistory)
   at Files.Views.YourHome.LibraryWidget_LibraryCardDeleteInvoked(Object sender, LibraryCardEventArgs e)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.906] 
 - App version: [e.g. v1.3.1.0]

**Comment by yaichenbaum** [comment]
@tsvietOK Do you want to work on this?

**Comment by tsvietOK** [comment]
@yair100 sorry, have no time :(

**Comment by nvi9** [comment]
@yair100 @tsvietOK this issue seems to be resolved on `main`, can you check it too?

**Comment by tsvietOK** [comment]
Seems like issue has been resolved.
