### ISSUE TITLE
Files, folders and web shortcuts are not displayed

### ISSUE THREAD

**Issue by skittOS** [files-community/Files#5446]
Bug-Report:
Files, folders and web shortcuts are not displayed in Files-App Version 1.5.0.0 on Windows 10.
Restart, reload or similar does not help.

All types of shortcuts (to files, folders or Web) are not displayed, while in Windows Explorer they are present. (See screenshots)

Windows-Explorer:
![image](https://user-images.githubusercontent.com/63304147/126047211-ef2aa22c-6297-454a-a788-3c8119182d58.png)

Files-App:
![image](https://user-images.githubusercontent.com/63304147/126047246-c4b66a7a-0b80-4530-aa40-980b781844ec.png)
thanks.

**Comment by gave92** [comment]
Hello, thanks for this report. Please upload the two debug log files.

**Comment by XPoppyX** [comment]
In my case, this is what is in the log (nothing in debug_fulltrust.log)

```
2021-07-17 23:00:59.2574|INFO|OnLaunched|App launched
2021-07-17 23:00:59.7642|WARN|BuildConnection|Could not initialize FTP connection!
	System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=4.1.0.0, Culture=neutral, 
PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. 
(Exception from HRESULT: 0x80131040)
File name: 'System.Memory, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.IO.Pipes.PipeStream.ReadFileNative(SafePipeHandle handle, Span`1 buffer, NativeOverlapped* overlapped, Int32& errorCode)
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at Files.Helpers.NamedPipeAsAppServiceConnection.BeginRead(ValueTuple`2 info)
   at Files.Helpers.NamedPipeAsAppServiceConnection.Connect(String pipeName, TimeSpan timeout)
   at Files.Helpers.AppServiceConnectionHelper.BuildConnection(Boolean launchFullTrust)


2021-07-17 23:01:00.9186|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-07-17 23:01:00.9562|INFO|GetDrivesAsync|Drive added: D:\, Network
2021-07-17 23:01:00.9848|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2021-07-17 23:01:01.0149|INFO|GetDrivesAsync|Drive added: F:\, Fixed
2021-07-17 23:01:01.0493|INFO|GetDrivesAsync|Drive added: G:\, Fixed
2021-07-17 23:01:03.2283|INFO|IsRunningOnArm|Running on ARM: False
```

**Comment by gave92** [comment]
@XPoppyX you've built the app yourself right? That's a known issue when building the app with VS 16.10

**Comment by gave92** [comment]
@XPoppyX could you try adding the following to the uwp project file ("Files.csproj") and see if the issue is solved?
```xml
<PropertyGroup>
    <UseAppLocalCoreFramework>true</UseAppLocalCoreFramework>
</PropertyGroup>
```

**Comment by XPoppyX** [comment]
@gave92 it works now 👍
