### ISSUE TITLE
Feature: Auto refresh drive widget & tags widget when changes are detected

### ISSUE THREAD

**Issue by m1karii** [files-community/Files#6182]
1, Enable reload button on The Home page as a way to update displayed capacity and used space of drives (so i don't have to close and reopen whole Files app or go to drive properties every time i want it updated)
2. displayed capacity and used space of drives should be automatically updated when The Home page is entered (on new tab for e.g.)

**Comment by yaichenbaum** [comment]
@gave92 shouldn't we use the file watcher to automatically update the home page without requiring a refresh?

**Comment by gave92** [comment]
@yaichenbaum sounds good, we can try.

**Comment by mon-jai** [comment]
Coming from #14334.

Closing all windows and reopening files doesn't fix the problem.

![image](https://github.com/files-community/Files/assets/91261297/12757109-ed32-43f4-9a7f-e4a159e3e20e)

### Log

```
2024-01-06 00:13:22.1463|Information|Drive added: C:\, Fixed
2024-01-06 00:13:22.1467|Information|Drive added: C:\, Fixed
2024-01-06 00:13:22.2894|Information|Drive added: D:\, Fixed
2024-01-06 00:13:22.3175|Information|Drive added: D:\, Fixed
2024-01-06 00:13:28.2555|Information|SIDELOAD: Checking for updates...
2024-01-06 00:13:28.2596|Information|SIDELOAD: Checking for updates...
2024-01-06 00:13:28.2760|Error|System.Net.Http.HttpRequestException: No such host is known. (cdn.files.community:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Files.App.Services.SideloadUpdateService.CheckForUpdatesAsync()
2024-01-06 00:13:28.2811|Error|System.Net.Http.HttpRequestException: No such host is known. (cdn.files.community:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Files.App.Services.SideloadUpdateService.CheckForUpdatesAsync()
2024-01-06 00:13:28.5215|Information|SIDELOAD: Checking for updates...
2024-01-06 00:13:28.5300|Error|System.Net.Http.HttpRequestException: No such host is known. (cdn.files.community:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Files.App.Services.SideloadUpdateService.CheckForUpdatesAsync()
2024-01-06 00:13:28.5343|Information|SIDELOAD: Checking for updates...
2024-01-06 00:13:28.5450|Error|System.Net.Http.HttpRequestException: No such host is known. (cdn.files.community:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Files.App.Services.SideloadUpdateService.CheckForUpdatesAsync()
2024-01-06 00:16:03.7494|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-01-06 00:16:04.2057|Information|Adding cloud provider "OneDrive" mapped to C:\Users\mon\OneDrive
2024-01-06 00:16:06.2258|Information|Drive added: C:\, Fixed
2024-01-06 00:16:06.4930|Information|Drive added: D:\, Fixed
2024-01-06 00:16:07.7443|Information|SIDELOAD: Checking for updates...
2024-01-06 00:16:07.7567|Error|System.Net.Http.HttpRequestException: No such host is known. (cdn.files.community:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Files.App.Services.SideloadUpdateService.CheckForUpdatesAsync()
2024-01-06 00:28:02.6576|Information|Running on ARM: False
2024-01-07 02:16:22.6951|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-01-07 02:17:35.3136|Information|App launched. Launch args type: LaunchActivatedEventArgs
2024-01-07 02:17:36.9996|Information|Adding cloud provider "OneDrive" mapped to C:\Users\mon\OneDrive
2024-01-07 02:17:37.0558|Information|Drive added: C:\, Fixed
2024-01-07 02:17:37.6635|Information|Drive added: D:\, Fixed
2024-01-07 02:17:38.0031|Information|Drive added: \\?\Pixel 6a\
2024-01-07 02:17:39.2709|Information|SIDELOAD: Checking for updates...
2024-01-07 02:17:39.5947|Error|System.Net.Http.HttpRequestException: No such host is known. (cdn.files.community:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Files.App.Services.SideloadUpdateService.CheckForUpdatesAsync()
2024-01-07 02:17:43.7409|Information|Drive removed: \\?\USB#VID_18D1&PID_4EE1#24271JEGR12835#{6ac27878-a6fa-4155-ba85-f98f491d4f33}
2024-01-07 02:32:25.4598|Information|SIDELOAD: Checking for updates...
2024-01-07 02:32:25.5451|Information|App activated. Activated args type: LaunchActivatedEventArgs
2024-01-07 02:32:26.6635|Information|SIDELOAD: Current Package Name: FilesPreview
2024-01-07 02:32:26.6639|Information|SIDELOAD: Remote Package Name: FilesPreview
2024-01-07 02:32:26.6641|Information|SIDELOAD: Current Version: 3.0.12.0
2024-01-07 02:32:26.6642|Information|SIDELOAD: Remote Version: 3.1.0.0
2024-01-07 02:32:26.6644|Information|SIDELOAD: Update found.
2024-01-07 02:32:26.6646|Information|SIDELOAD: Starting background download.
2024-01-07 02:33:12.8453|Information|SIDELOAD: Checking for updates...
2024-01-07 02:33:12.9133|Information|App activated. Activated args type: LaunchActivatedEventArgs
2024-01-07 02:33:13.9595|Information|SIDELOAD: Current Package Name: FilesPreview
2024-01-07 02:33:13.9598|Information|SIDELOAD: Remote Package Name: FilesPreview
2024-01-07 02:33:13.9600|Information|SIDELOAD: Current Version: 3.0.12.0
2024-01-07 02:33:13.9601|Information|SIDELOAD: Remote Version: 3.1.0.0
2024-01-07 02:33:13.9603|Information|SIDELOAD: Update found.
2024-01-07 02:33:13.9604|Information|SIDELOAD: Starting background download.
2024-01-07 02:33:14.0285|Error|System.IO.IOException: The process cannot access the file 'C:\Users\Mon\AppData\Local\Packages\FilesPreview_1y0xx7n9077q4\LocalState\UpdatePackage.msix' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at Files.App.Services.SideloadUpdateService.StartBackgroundDownloadAsync()
   at Files.App.Services.SideloadUpdateService.StartBackgroundDownloadAsync()
2024-01-07 02:33:56.2833|Information|SIDELOAD: Checking for updates...
2024-01-07 02:33:56.3525|Information|App activated. Activated args type: LaunchActivatedEventArgs
2024-01-07 02:33:57.1779|Information|SIDELOAD: Current Package Name: FilesPreview
2024-01-07 02:33:57.1782|Information|SIDELOAD: Remote Package Name: FilesPreview
2024-01-07 02:33:57.1784|Information|SIDELOAD: Current Version: 3.0.12.0
2024-01-07 02:33:57.1785|Information|SIDELOAD: Remote Version: 3.1.0.0
2024-01-07 02:33:57.1786|Information|SIDELOAD: Update found.
2024-01-07 02:33:57.1788|Information|SIDELOAD: Starting background download.
2024-01-07 02:33:57.3053|Error|System.IO.IOException: The process cannot access the file 'C:\Users\Mon\AppData\Local\Packages\FilesPreview_1y0xx7n9077q4\LocalState\UpdatePackage.msix' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at Files.App.Services.SideloadUpdateService.StartBackgroundDownloadAsync()
   at Files.App.Services.SideloadUpdateService.StartBackgroundDownloadAsync()
2024-01-07 02:36:53.5691|Information|SIDELOAD: Checking for updates...
2024-01-07 02:36:53.6451|Information|App activated. Activated args type: LaunchActivatedEventArgs
2024-01-07 02:36:54.4583|Information|SIDELOAD: Current Package Name: FilesPreview
2024-01-07 02:36:54.4586|Information|SIDELOAD: Remote Package Name: FilesPreview
2024-01-07 02:36:54.4588|Information|SIDELOAD: Current Version: 3.0.12.0
2024-01-07 02:36:54.4589|Information|SIDELOAD: Remote Version: 3.1.0.0
2024-01-07 02:36:54.4591|Information|SIDELOAD: Update found.
2024-01-07 02:36:54.4592|Information|SIDELOAD: Starting background download.
2024-01-07 02:36:54.5351|Error|System.IO.IOException: The process cannot access the file 'C:\Users\Mon\AppData\Local\Packages\FilesPreview_1y0xx7n9077q4\LocalState\UpdatePackage.msix' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at Files.App.Services.SideloadUpdateService.StartBackgroundDownloadAsync()
   at Files.App.Services.SideloadUpdateService.StartBackgroundDownloadAsync()
2024-01-07 02:36:55.6769|Information|Download time taken: 00:04:29
2024-01-07 02:38:05.5343|Information|SIDELOAD: Checking for updates...
2024-01-07 02:38:05.6028|Information|App activated. Activated args type: LaunchActivatedEventArgs
2024-01-07 02:38:06.4381|Information|SIDELOAD: Current Package Name: FilesPreview
2024-01-07 02:38:06.4384|Information|SIDELOAD: Remote Package Name: FilesPreview
2024-01-07 02:38:06.4385|Information|SIDELOAD: Current Version: 3.0.12.0
2024-01-07 02:38:06.4386|Information|SIDELOAD: Remote Version: 3.1.0.0
2024-01-07 02:38:06.4387|Information|SIDELOAD: Update found.
2024-01-07 02:38:06.4389|Information|SIDELOAD: Starting background download.
2024-01-07 02:38:10.4322|Information|SIDELOAD: Checking for updates...
2024-01-07 02:38:10.5015|Information|App activated. Activated args type: LaunchActivatedEventArgs
2024-01-07 02:38:11.7285|Information|SIDELOAD: Current Package Name: FilesPreview
2024-01-07 02:38:11.7287|Information|SIDELOAD: Remote Package Name: FilesPreview
2024-01-07 02:38:11.7289|Information|SIDELOAD: Current Version: 3.0.12.0
2024-01-07 02:38:11.7290|Information|SIDELOAD: Remote Version: 3.1.0.0
2024-01-07 02:38:11.7291|Information|SIDELOAD: Update found.
2024-01-07 02:38:11.7293|Information|SIDELOAD: Starting background download.
2024-01-07 02:38:11.7983|Error|System.IO.IOException: The process cannot access the file 'C:\Users\Mon\AppData\Local\Packages\FilesPreview_1y0xx7n9077q4\LocalState\UpdatePackage.msix' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at Files.App.Services.SideloadUpdateService.StartBackgroundDownloadAsync()
   at Files.App.Services.SideloadUpdateService.StartBackgroundDownloadAsync()
2024-01-07 02:38:31.8030|Information|SIDELOAD: Checking for updates...
2024-01-07 02:38:31.8721|Information|App activated. Activated args type: LaunchActivatedEventArgs
2024-01-07 02:38:33.0679|Information|SIDELOAD: Current Package Name: FilesPreview
2024-01-07 02:38:33.0682|Information|SIDELOAD: Remote Package Name: FilesPreview
2024-01-07 02:38:33.0684|Information|SIDELOAD: Current Version: 3.0.12.0
2024-01-07 02:38:33.0685|Information|SIDELOAD: Remote Version: 3.1.0.0
2024-01-07 02:38:33.0687|Information|SIDELOAD: Update found.
2024-01-07 02:38:33.0688|Information|SIDELOAD: Starting background download.
2024-01-07 02:38:33.1435|Error|System.IO.IOException: The process cannot access the file 'C:\Users\Mon\AppData\Local\Packages\FilesPreview_1y0xx7n9077q4\LocalState\UpdatePackage.msix' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at Files.App.Services.SideloadUpdateService.StartBackgroundDownloadAsync()
   at Files.App.Services.SideloadUpdateService.StartBackgroundDownloadAsync()
2024-01-07 02:38:38.9958|Information|App activated. Activated args type: ProtocolActivatedEventArgs
2024-01-07 02:38:39.3195|Information|Running on ARM: False
2024-01-07 02:39:16.5609|Information|App activated. Activated args type: ProtocolActivatedEventArgs
```

**Comment by Josh65-2201** [comment]
Please don't copy and paste the log file contents. It makes issue hard to read and navigate.

**Comment by yaira2** [comment]
> Closing all windows and reopening files doesn't fix the problem.

What if you close Files via Task Manager?

**Comment by mon-jai** [comment]
> Please don't copy and paste the log file contents. It makes issue hard to read and navigate.

Sorry for that.

> What if you close Files via Task Manager? Just to clarify, this isn't the expected behavior but it'll confirm if it's the same issue.

@yaira2 Surprisingly, it does fix the problem (for a moment), but the stats still doesn't update until next time I do the same.

**Comment by yaira2** [comment]
The issue is due to the lack of a "watcher" to update the UI when the storage capacity changes.

**Comment by 0x5bfa** [comment]
Making this line work would fix this issue.

https://github.com/files-community/Files/blob/af07aa37b62c8f4bc0ceda362b092921f3456cb9/src/Files.App/Views/HomePage.xaml.cs#L89

Also this would work as a workaround for #15410 instead of turning off the option to run the app on the background.

I'll leave this for a few days, if no one is interested in I'll look into 👍

**Comment by yaira2** [comment]
Thank you

**Comment by yaira2** [comment]
A fix will be available in our next release
