### ISSUE TITLE
Files 2.0 doesn't open

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#6482]
### Description

The app crashes immediately after opening it.

### Steps To Reproduce

1. Install Files 2.0
2. Launch it

### Expected behavior

Files should launch correctly.

### Files Version

v2.0.13

### Windows Version

Windows 10 Pro build 21354.1

### Relevant Assets

```
Application: FilesFullTrust.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Vanara.PInvoke.Shell32+IContextMenu.QueryContextMenu(Vanara.PInvoke.HMENU, UInt32, UInt32, UInt32, CMF)
   at FilesFullTrust.ContextMenu.GetContextMenuForFiles(Vanara.Windows.Shell.ShellItem[], CMF, System.Func`2<System.String,Boolean>)
   at FilesFullTrust.ContextMenu.GetContextMenuForFiles(System.String[], CMF, System.Func`2<System.String,Boolean>)
   at FilesFullTrust.MessageHandlers.ContextMenuHandler.Initialize(System.IO.Pipes.NamedPipeServerStream)
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForEach(System.Action`1<System.__Canon>)
   at FilesFullTrust.Program+<Main>d__5.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>)
   at FilesFullTrust.LogWriter+<InitializeAsync>d__2.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Threading.Tasks.TaskCompletionSource`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Threading.Tasks.AsyncInfoToTaskBridge`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.VoidValueTypeParameter, System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Complete(Windows.Foundation.IAsyncInfo, System.Func`2<Windows.Foundation.IAsyncInfo,System.__Canon>, Windows.Foundation.AsyncStatus)
```

**Comment by gave92** [comment]
Could you post the other log file as well? Thanks! Looks like it's not liking something in you context menu.

**Comment by gave92** [comment]
Which version of Visual Studio di you have? You can check here for a fix to build Files from source on newer versions -> https://files.community/docs/contributing/building-from-source

**Comment by jaigak** [comment]
@yair100 I reinstalled Files from the Store and it seems to work now.
