### ISSUE TITLE
Files crashes immediately on launch (Error loading theme: Default)

### ISSUE THREAD

**Issue by lediur** [files-community/Files#6955]
### Description

Noticed today (2021-11-16) - when trying to launch Files, the splash screen shows for a few seconds and then crashes. Logs suggest a theme loading issue. I haven't tried to restart my computer yet, but I'll try that shortly.

### Steps To Reproduce

1. Launch Files

### Expected behavior

Files does not crash

### Files Version

2.0.34.0

### Windows Version

Windows 11 Pro Insider Preview 22494.1000

### Relevant Assets

`debug.log`
```
2021-11-16 12:00:04.0245|WARN|TryLoadThemeAsync|Error loading theme: Default
	System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Files.Helpers.ExternalResourcesHelper.<TryLoadResourceDictionary>d__17.MoveNext() + 0x16f
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Files.Helpers.ExternalResourcesHelper.<TryLoadThemeAsync>d__16.MoveNext() + 0x9c

2021-11-16 12:00:10.7122|INFO|OnActivated|App activated by CommandLineLaunch
2021-11-16 12:00:10.8487|WARN|TryLoadThemeAsync|Error loading theme: Default
	System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Files.Helpers.ExternalResourcesHelper.<TryLoadResourceDictionary>d__17.MoveNext() + 0x16f
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Files.Helpers.ExternalResourcesHelper.<TryLoadThemeAsync>d__16.MoveNext() + 0x9c

2021-11-16 12:00:14.4606|INFO|OnLaunched|App launched. Prelaunch: False
2021-11-16 12:00:19.2073|INFO|OnActivated|App activated by CommandLineLaunch
2021-11-16 12:01:11.9764|INFO|OnActivated|App activated by CommandLineLaunch
2021-11-16 12:01:12.1184|WARN|TryLoadThemeAsync|Error loading theme: Default
	System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Files.Helpers.ExternalResourcesHelper.<TryLoadResourceDictionary>d__17.MoveNext() + 0x16f
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Files.Helpers.ExternalResourcesHelper.<TryLoadThemeAsync>d__16.MoveNext() + 0x9c
```

`debug-fulltrust.log`
```
2021-11-16 12:00:29.6969|WARN|InitializeAppServiceConnection|Could not initialize pipe!
	System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FilesFullTrust.Program.<InitializeAppServiceConnection>d__11.MoveNext()
2021-11-16 12:00:34.4370|WARN|InitializeAppServiceConnection|Could not initialize pipe!
	System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FilesFullTrust.Program.<InitializeAppServiceConnection>d__11.MoveNext()
2021-11-16 12:02:54.5303|WARN|InitializeAppServiceConnection|Could not initialize pipe!
	System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FilesFullTrust.Program.<InitializeAppServiceConnection>d__11.MoveNext()
```

**Comment by madlifer** [comment]
Same problem.

The worst part is I set Files as my default explorer through the "experimental feature", so currently my computer can't open the folder at all.

Maybe Files should write in readme.md how to restore default explorer

**Comment by yaichenbaum** [comment]
@lediur does resetting the app fix this issue?

@madlifer you can revert the changes with this script https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip.

**Comment by lediur** [comment]
Just tried - resetting the app did fix the issue and let Files start normally.
