### ISSUE TITLE
Slow loading of zip file content when opening via browser download manager

### ISSUE THREAD

**Issue by starkgate** [files-community/Files#7593]
### Description

I just experienced a 2MB zip file taking a minute or so to open. I can reproduce this consistently when the zip file is downloaded and opened through Firefox or Edge's download manager. If I open it from Files itself there is no problem. I do not know if this also happens with Chrome.

### Steps To Reproduce

1. Download the zip file linked below with Firefox (I use version 96)'or Edge
2. Try to open it through the browser's download manager
![firefox_e7aGJR6SmR](https://user-images.githubusercontent.com/12874678/149307636-0abf8b3c-65b2-465c-9721-f306e0bc5e74.png)

### Expected behavior

Same performance when opening through browser's download manager.

### Files Version

Version: 2.1.0.0 OS Version: 10.0.19044.1415

### Windows Version

W10 21H2 19044.1415

### Relevant Assets/Logs

Zip file for reproduction: https://www.dropbox.com/s/zwt96yu699jphl5/MusicBee_Setup_3_4_8033.zip?dl=1

```
2022-01-13 10:46:03.6828|INFO|OnFileActivated|App activated by file
2022-01-13 10:46:19.1147|WARN|BuildConnection|Could not initialize FTP connection!
	System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xad
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
   at Files.Helpers.NamedPipeAsAppServiceConnection.<Connect>d__10.MoveNext() + 0x148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x89
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() + 0xf
   at Files.Helpers.AppServiceConnectionHelper.<BuildConnection>d__8.MoveNext() + 0x11b

2022-01-13 10:47:14.3713|INFO|OnActivated|App activated by CommandLineLaunch
```

```
2022-01-13 10:43:41.9655|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-01-13 10:43:41.9658|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-01-13 10:43:42.1245|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-01-13 10:43:42.1711|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-01-13 10:43:42.4380|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-01-13 10:43:42.4397|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-01-13 10:43:42.4419|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-01-13 10:43:42.4735|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-01-13 10:43:42.4762|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-01-13 10:44:38.8348|INFO|OnConnectionRequestReceived|Argument: Terminate
2022-01-13 10:46:04.2940|ERROR|UnhandledExceptionTrapper|Process with an Id of 14684 is not running.
	System.ArgumentException: Process with an Id of 14684 is not running.
   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   at System.Diagnostics.Process.GetProcessById(Int32 processId)
   at FilesFullTrust.Program.TerminateProcess(Int32 processId)
   at FilesFullTrust.Program.HandleCommandLineArgs()
   at FilesFullTrust.Program.Main(String[] args)
   at FilesFullTrust.Program.<Main>(String[] args)
2022-01-13 10:46:26.4589|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-01-13 10:46:26.4809|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-01-13 10:46:26.6140|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-01-13 10:46:26.9806|INFO|CheckQuickLookAvailability|QuickLook detected: False
2022-01-13 10:46:27.6734|INFO|OnConnectionRequestReceived|Argument: GetFileAssociation
2022-01-13 10:46:27.7768|INFO|OnConnectionRequestReceived|Argument: LaunchApp
2022-01-13 10:47:14.4341|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-01-13 10:47:14.4429|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-01-13 10:47:14.4450|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-01-13 10:47:15.8487|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-01-13 10:47:15.8522|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-01-13 10:47:15.8686|WARN|StartSTATask|The system cannot find the file specified. (0x80070002)
	System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__1()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-01-13 10:47:16.1197|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-01-13 10:47:16.2185|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-01-13 10:47:16.2364|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-01-13 10:47:16.2387|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
```

**Comment by gave92** [comment]
Thanks for the report. "I just experienced a 2MB zip file taking a minute or so to open." -> where is all this time lost? Before Files window open? Before dsplaying zip contents?

**Comment by starkgate** [comment]
Before displaying the contents. The Files tab opens, then it loads for 30s-1mn before displaying the contents.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
