### ISSUE TITLE
Desktop not appearing in Favorites sidebar

### ISSUE THREAD

**Issue by MikeFarrington** [files-community/Files#8114]
### Description

"Desktop" is not appearing for me in my sidebar, I think this is likely caused by my changing my default desktop location.  It does however appear and work properly in the "Home" view.

![image](https://user-images.githubusercontent.com/40607634/152145996-1635d95f-aa61-4910-b1d7-60ba99981964.png)

### Steps To Reproduce

1. Change location of your Desktop folder via Windows Explorer by right-clicking on it and using the "Location" tab

### Expected behavior

I expect Desktop to appear as a target in the sidebar under Favorites, as shown in the Microsoft Store photographs

![image](https://user-images.githubusercontent.com/40607634/152146449-57d54376-80c1-4a89-ba64-1ba658e56450.png)

### Files Version

Version: 2.1.5.0 OS Version: 10.0.22000.469

### Windows Version

Edition	Windows 11 Pro for Workstations Version	21H2 Installed on	‎1/‎16/‎2022 OS build	22000.469 Experience	Windows Feature Experience Pack 1000.22000.469.0

### Relevant Assets/Logs

```
2022-02-02 06:41:02.5428|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-02-02 06:41:02.5526|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-02-02 06:41:02.5529|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-02-02 06:41:02.5532|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-02-02 06:41:02.6122|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-02-02 06:41:02.6265|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-02-02 06:41:02.6374|WARN|StartSTATask|The system cannot find the file specified. (0x80070002)
	System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__1()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-02-02 06:41:03.0998|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-02-02 06:41:03.1367|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-02-02 06:41:03.1429|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-02-02 06:41:03.1516|INFO|OnConnectionRequestReceived|Argument: GetNewContextMenuEntries
2022-02-02 06:41:03.6318|INFO|CheckQuickLookAvailability|QuickLook detected: False
```

**Comment by yaichenbaum** [comment]
@MikeFarrington you can pin desktop to the sidebar by navigating to the directory, right clicking in a blank space, and clicking pin to favorites.

**Comment by MikeFarrington** [comment]
Yes, that worked.  Sorry, I assumed Desktop was supposed to be a default under Favorites and that my less-than-usual moving of my desktop was the cause.

**Comment by yaichenbaum** [comment]
@MikeFarrington unfortunately not, the sidebar items are decided by the user and are automatically removed if the location is invalid.
