### ISSUE TITLE
Opening Control Panel opens a Not Folder

### ISSUE THREAD

**Issue by makisukurisu** [files-community/Files#8275]
### Description

If you enable "Set Files as the default file manager" and use "Uninstall" button to remove not a modern app (Tizen studio in my example) Files will try to open some path: ::{26EE0668-A00A-44D7-9371-BEB064C98683}\8\::{7B81BE6A-CE2B-4676-A29E-EB907A5126C5} in my example and show an error message.

Example:
![Example](https://user-images.githubusercontent.com/49622129/153426859-f2a2c23f-07a5-4521-8dc5-598bafa3fa6e.png)

### Steps To Reproduce

1. Enable "Set Files as the default file manager"
2. Try to uninstall "legacy" app (like Google Chrome, Visual Studio, Steam, Discord, etc)
3. See an error

### Expected behavior

Show Programs and Features page (either in Files or in explorer.exe), preferably - also select needed app (unlike explorer.exe)

Expected window:
![Expected window](https://user-images.githubusercontent.com/49622129/153426979-e2c71b58-9a31-4ece-8814-7670b3d9eb06.png)

### Files Version

Version: 2.1.5.0

### Windows Version

Windows 11 10.0.22000.434

### Relevant Assets/Logs

```
2022-02-10 16:21:57.8937|WARN|NormalizePath|::{26EE0668-A00A-44D7-9371-BEB064C98683}\8\::{7B81BE6A-CE2B-4676-A29E-EB907A5126C5}\
	System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at SharedLibrary!<BaseAddress>+0xafcde0
   at System.Uri..ctor(String) + 0x17
   at Files.Helpers.PathNormalization.NormalizePath(String) + 0xef
```
From debug.log

```
2022-02-10 16:21:57.2471|WARN|StartSTATask|The system cannot find the file specified. (0x80070002)
	System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__1()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
```

From debug_fulltrust.log

Let me know if full files are needed.

P.S. Excuse me if this was reported before, could not find it in Opened issues with search tag for Experimental/Default

**Comment by yaichenbaum** [comment]
@makisukurisu is this still an issue in the preview version? https://files.community/download/preview

**Comment by makisukurisu** [comment]
@yair100 , just installed Files from link you provided, now it opens old control panel just fine with no error messages.

Thanks for your reply 😄

![image](https://user-images.githubusercontent.com/49622129/168055363-dc95c883-eff8-429b-bf20-53c40e4c2bed.png)

Also I had some updates on my system, just in case this may affect this issue:
Version: 2.2.5.0
OS Version: 10.0.22000.613
