### ISSUE TITLE
Cant copy/move files.

### ISSUE THREAD

**Issue by TommyV6** [files-community/Files#8332]
### Description

I cant move or copy any files with "Files" there is no difference local, network, same disk... Windows Explorer works fine.
Sometime it works, sometime not. Ctrl+C Ctrl+V works fine.

https://www.youtube.com/watch?v=cByk87qeMUg

### Steps To Reproduce

1. Copy any file with right click
2. Paste any file with right click
3. Any directory any file.

### Expected behavior

Copy or move files.

### Files Version

Wersja: 2.1.13.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 Pro 21H2 Zainstalowano dnia	‎05.‎01.‎2022 Kompilacja systemu operacyjnego	22000.493 Możliwości	Pakiet funkcji Windows 1000.22000.493.0

### Relevant Assets/Logs

2022-02-13 14:10:59.2705|INFO|OnLaunched|App launched. Prelaunch: False
2022-02-13 14:10:59.5615|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-02-13 14:10:59.5845|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2022-02-13 14:10:59.6235|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2022-02-13 14:10:59.6535|INFO|GetDrivesAsync|Drive added: F:\, Fixed
2022-02-13 14:10:59.6695|WARN|GetDrivesAsync|Unauthorized: Attempting to add the device, G:\, failed at the StorageFolder initialization step. This device will be ignored.
2022-02-13 14:10:59.6835|WARN|GetDrivesAsync|Unauthorized: Attempting to add the device, H:\, failed at the StorageFolder initialization step. This device will be ignored.
2022-02-13 14:10:59.7005|WARN|GetDrivesAsync|Unauthorized: Attempting to add the device, I:\, failed at the StorageFolder initialization step. This device will be ignored.
2022-02-13 14:10:59.7155|WARN|GetDrivesAsync|Unauthorized: Attempting to add the device, J:\, failed at the StorageFolder initialization step. This device will be ignored.
2022-02-13 14:10:59.7455|INFO|GetDrivesAsync|Drive added: K:\, Removable
2022-02-13 14:10:59.7655|INFO|GetDrivesAsync|Drive added: L:\, Fixed
2022-02-13 14:10:59.7965|INFO|DeviceAdded|Drive added: H:\, Removable
2022-02-13 14:10:59.8355|INFO|DeviceAdded|Drive added: I:\, Removable
2022-02-13 14:10:59.8665|INFO|EnumerateDrivesAsync|Adding cloud provider "Google Drive (Google_Drive)" mapped to D:\SSD\Google_Drive
2022-02-13 14:10:59.8805|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\User\OneDrive
2022-02-13 14:11:00.8002|INFO|DeviceAdded|Drive added: J:\, Removable
2022-02-13 14:11:00.8062|INFO|DeviceAdded|Drive added: G:\, Removable
2022-02-13 14:11:02.9038|INFO|IsRunningOnArm|Running on ARM: False
2022-02-13 14:11:10.4530|WARN|SendMessageForResponseAsync|Error sending request on pipe.
	System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xad
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Files.Helpers.NamedPipeAsAppServiceConnection.<SendMessageForResponseAsync>d__11.MoveNext() + 0x24d

2022-02-13 14:11:10.4660|WARN|SendMessageForResponseAsync|Error sending request on pipe.
	System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xad
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Files.Helpers.NamedPipeAsAppServiceConnection.<SendMessageForResponseAsync>d__11.MoveNext() + 0x24d

2022-02-13 14:10:15.4503|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-02-13 14:10:16.3444|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-02-13 14:10:16.3447|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-02-13 14:10:17.0879|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-02-13 14:10:17.9282|INFO|OnConnectionRequestReceived|Argument: LoadContextMenu
2022-02-13 14:10:59.4882|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-02-13 14:10:59.4977|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-02-13 14:10:59.4979|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-02-13 14:10:59.5592|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-02-13 14:10:59.5837|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-02-13 14:10:59.5910|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-02-13 14:10:59.6001|WARN|StartSTATask|Nie można odnaleźć określonego pliku. (0x80070002)
	System.IO.FileNotFoundException: Nie można odnaleźć określonego pliku. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__1()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-02-13 14:10:59.8677|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-02-13 14:10:59.8807|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-02-13 14:10:59.8880|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-02-13 14:10:59.8937|INFO|OnConnectionRequestReceived|Argument: GetNewContextMenuEntries
2022-02-13 14:11:00.3958|INFO|CheckQuickLookAvailability|QuickLook detected: False
2022-02-13 14:11:02.9570|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-02-13 14:11:04.3484|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-02-13 14:11:04.3487|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-02-13 14:11:05.2333|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-02-13 14:11:06.1265|INFO|OnConnectionRequestReceived|Argument: LoadContextMenu

**Comment by gave92** [comment]
Thanks for the report. Could you upload both the debug files (as attachments)? There should be a second one called "debug_fulltrust.log".

**Comment by TommyV6** [comment]
> Thanks for the report. Could you upload both the debug files (as attachments)? There should be a second one called "debug_fulltrust.log".

This is output of both files.

**Comment by gave92** [comment]
Is restarting the app enough to make copy paste work? Or are you never to copy paste with right click?
I think part of the app is crashing when you right click, could you post a screenshot of the context menu in windows explorer for that file?

**Comment by TommyV6** [comment]
I can restart whole PC, nothing helps. But sometimes it just works.
![image](https://user-images.githubusercontent.com/97856804/153762971-52690e6c-c477-464e-9d3c-2cadd331e765.png)
