### ISSUE TITLE
Crash after deleting SMB File

### ISSUE THREAD

**Issue by foxhoundv** [files-community/Files#8370]
### Description

After deleting a file located on an SMB folder that is linked to my computer as Z: drive, it crashes. Every time I make a file change in the SMB folder I have to refresh. If I change the name, I have to refresh... delete I have to refresh.

### Steps To Reproduce

Navigate to an SMB mounted folder... rename it, then refresh, then delete it. Upon trying to refresh, it crashes.

### Expected behavior

I expect any name change or deletion in an SMB folder that is mounted to automatically refresh the files listed.

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.493

### Windows Version

Windows 11 Pro 21H2 22000.493

### Relevant Assets/Logs

2022-02-15 14:22:26.8731|INFO|OnConnectionRequestReceived|Argument: FileOperation
2022-02-15 14:22:28.8796|INFO|OnConnectionRequestReceived|Argument: FileOperation
2022-02-15 14:22:34.6220|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-02-15 14:22:34.6332|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-02-15 14:22:34.6335|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-02-15 14:22:34.6627|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-02-15 14:22:34.7233|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-02-15 14:22:34.7809|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-02-15 14:22:34.7956|WARN|StartSTATask|The system cannot find the file specified. (0x80070002)
	System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__1()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-02-15 14:22:35.0748|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-02-15 14:22:35.1009|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-02-15 14:22:35.1107|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-02-15 14:22:35.1215|INFO|OnConnectionRequestReceived|Argument: GetNewContextMenuEntries
2022-02-15 14:22:35.6193|INFO|CheckQuickLookAvailability|QuickLook detected: False

**Comment by gave92** [comment]
Could you upload the second debug file as well? (debug..og)

**Comment by foxhoundv** [comment]
2022-02-15 14:22:28.9264|ERROR|AppUnhandledException|Sequence contains more than one matching element
	System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1, Func`2) + 0xe8
   at Files.Filesystem.ShellFilesystemOperations.<>c__DisplayClass13_0.<DeleteItemsAsync>b__12(ShellOperationItemResult) + 0x6c
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.CreateValueCallback.Invoke(TKey) + 0x2b
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext() + 0xa5
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() + 0x68
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1) + 0x77
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1) + 0x122
   at Files.Extensions.EnumerableExtensions.<>c__DisplayClass5_0`1.<ToListAsync>b__0() + 0x34
   at System.Func`1.Invoke() + 0x28
   at System.Threading.Tasks.Task`1.InnerInvoke() + 0x47
   at System.Threading.Tasks.Task.Execute() + 0x1c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Files.Extensions.EnumerableExtensions.<ToListAsync>d__5`1.MoveNext() + 0x120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Files.Filesystem.ShellFilesystemOperations.<DeleteItemsAsync>d__13.MoveNext() + 0x1b8e
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Files.Filesystem.FilesystemHelpers.<DeleteItemsAsync>d__17.MoveNext() + 0xe81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() + 0x10
   at Files.Views.ModernShellPage.<KeyboardAccelerator_Invoked>d__111.MoveNext() + 0xf64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Action`1.Invoke(T) + 0x28
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8
   at __Interop.ForwardComStubs.Stub_10[TThis](__ComObject, Int32) + 0x24
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x3d
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x75
   at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__23[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at Files!<BaseAddress>+0x143a750

2022-02-15 14:22:34.1170|INFO|OnActivated|App activated by ToastNotification
2022-02-15 14:22:34.2650|WARN|MergeSettings|Merging settings failed
	System.ArgumentException: The parameter is incorrect.

Error trying to write application data container value
   at System.Runtime.InteropServices.WindowsRuntime.IMapSharedReferenceTypesStubClass.Insert[TKey, TValue](IDictionary`2, TKey, TValue) + 0xd1
   at Windows.ApplicationModel.DataTransfer.DataPackagePropertySet.global::System.Collections.Generic.IDictionary<System.String,System.Object>.set_Item(String, Object) + 0x21
   at Files.ViewModels.SettingsViewModel.Get[TValue](TValue, String) + 0x22d
   at Files.Helpers.RegistryToJsonSettingsMerger.MergeSettings() + 0xaf

2022-02-15 14:22:34.7190|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-02-15 14:22:34.7800|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2022-02-15 14:22:34.8110|WARN|GetDrivesAsync|Unauthorized: Attempting to add the device, E:\, failed at the StorageFolder initialization step. This device will be ignored.
2022-02-15 14:22:34.8570|INFO|GetDrivesAsync|Drive added: Z:\, Network
2022-02-15 14:22:34.9050|INFO|DeviceAdded|Drive added: E:\, Removable
2022-02-15 14:22:35.0740|INFO|EnumerateDrivesAsync|Adding cloud provider "Nextcloud" mapped to C:\Users\foxho\Nextcloud
2022-02-15 14:22:35.1000|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\foxho\OneDrive

**Comment by gave92** [comment]
Thanks if this the full file? In not could you upload the full file _as attachment_? It's hard to read it like this, thanks

**Comment by foxhoundv** [comment]
No it isn't the full file. Only what pertains to that timeframe. Other Log information was like 10 or 15 minutes prior or after the event.

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview
