### ISSUE TITLE
Unable to open Properties window

### ISSUE THREAD

**Issue by chrs-it** [files-community/Files#8430]
### Description

File Explorer is not affected by this issue. Note that this appears to have been introduced by the latest Windows update, and it happens regardless of object – both files and folders are affected alike.

Exception:
```
2022-02-20 09:27:10.5179|WARN|StartSTATask|The system cannot find the file specified. (0x80070002)
	System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__0()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
```

### Expected behavior

Properties window can be opened normally. 

### Files Version

2.1.13.0

### Windows Version

Windows 11 Dev 22557.1

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8103638/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8103639/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Thank you for your feedback, this is an issue with the latest insider build and not connected to Files. Can you report the issue on the feedback hub?
