### ISSUE TITLE
Bug: Search feature isn't working on a LAN ADSL box

### ISSUE THREAD

**Issue by lyonelf** [files-community/Files#8549]
### Description

When i put on the search bar \\192.168.0.254   to navigate in hard drives of my ADSL Freebox, Files stay in a research and never show me the 2 share folders.

### Expected behavior

want to show and naviguate under the share folders

### Files Version

2..1.15

### Windows Version

Windows 11

### Relevant Assets/Logs

2022-03-02 08:20:14.6773|INFO|OnLaunched|App launched. Prelaunch: False
2022-03-02 08:20:16.1780|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-03-02 08:20:16.4680|INFO|GetDrivesAsync|Drive added: M:\, Network
2022-03-02 08:20:16.6446|INFO|GetDrivesAsync|Drive added: P:\, Network
2022-03-02 08:20:17.3306|INFO|GetDrivesAsync|Drive added: X:\, Network
2022-03-02 08:20:17.4582|INFO|GetDrivesAsync|Drive added: Z:\, Ram
2022-03-02 08:20:45.5992|INFO|IsRunningOnArm|Running on ARM: False

2022-03-02 08:25:33.4209|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-03-02 08:25:33.4509|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-03-02 08:25:33.6908|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-03-02 08:25:33.9773|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-02 08:25:34.6618|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-02 08:25:51.4517|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-02 08:25:51.6448|INFO|OnConnectionRequestReceived|Argument: GetIconOverlayi

**Comment by gave92** [comment]
Could you post a screenshot of windows explorer for that folder?

**Comment by lyonelf** [comment]
[https://ibb.co/r5Zv82V](url)

here is what i see and it never stop

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?. Also your screenshot link doesnt work. you can upload the image directly to github if it is an issue.

**Comment by lyonelf** [comment]
Yes it's the same.

i need to put all the path to have the access to the shared folder in my adsl box.

**Comment by Josh-65** [comment]
@yaichenbaum

**Comment by yaichenbaum** [comment]
@lyonelf can you upload the latest log files?

**Comment by lyonelf** [comment]
2022-07-11 09:57:15.8550|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-07-11 09:57:15.9244|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-07-11 09:57:15.9352|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-07-11 09:57:15.9397|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-07-11 09:57:16.0740|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-07-11 09:57:16.0885|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-07-11 09:57:16.1646|WARN|StartSTATask|Le fichier spécifié est introuvable. (0x80070002)
	System.IO.FileNotFoundException: Le fichier spécifié est introuvable. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem.Open(String path)
   at Files.FullTrust.Helpers.ShellFolderExtensions.GetShellItemFromPathOrPidl(String pathOrPidl)
   at Files.FullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at Files.FullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass8_0.<ParseArgumentsAsync>b__1()
   at Files.FullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-07-11 09:57:16.3348|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-07-11 09:57:16.4862|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-07-11 09:57:16.9150|INFO|OnConnectionRequestReceived|Argument: GetNewContextMenuEntries
2022-07-11 09:57:16.9871|INFO|CheckQuickLookAvailability|QuickLook detected: False
2022-07-11 09:57:21.0450|INFO|OnConnectionRequestReceived|Argument: Terminate
2022-07-17 14:02:32.8039|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-07-17 14:02:32.8672|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-07-17 14:02:32.8754|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-07-17 14:02:32.9146|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-07-17 14:02:33.1877|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-07-17 14:02:33.2969|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-07-17 14:02:33.3905|WARN|StartSTATask|Le fichier spécifié est introuvable. (0x80070002)
	System.IO.FileNotFoundException: Le fichier spécifié est introuvable. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem.Open(String path)
   at Files.FullTrust.Helpers.ShellFolderExtensions.GetShellItemFromPathOrPidl(String pathOrPidl)
   at Files.FullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at Files.FullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass8_0.<ParseArgumentsAsync>b__1()
   at Files.FullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-07-17 14:02:33.6299|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-07-17 14:02:33.8722|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-07-17 14:02:33.9368|INFO|OnConnectionRequestReceived|Argument: GetNewContextMenuEntries
2022-07-17 14:02:34.3675|INFO|CheckQuickLookAvailability|QuickLook detected: False
2022-07-17 14:02:43.9818|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-07-17 14:05:06.4172|INFO|OnConnectionRequestReceived|Argument: Terminate


And


2022-07-11 09:57:14.2874|INFO|OnLaunched|App launched. Prelaunch: False
2022-07-11 09:57:15.1158|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-07-11 09:57:15.2328|INFO|GetDrivesAsync|Drive added: D:\, Removable
2022-07-11 09:57:15.3340|INFO|GetDrivesAsync|Drive added: M:\, Network
2022-07-11 09:57:16.0720|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\lionel.fesselier\OneDrive
2022-07-11 09:57:16.3339|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive - Gedeon - SIPAOF" mapped to C:\Users\lionel.fesselier\OneDrive - Gedeon - SIPAOF
2022-07-11 09:57:18.2201|INFO|CheckForUpdates|SIDELOAD: Checking for updates...https://cdn.files.community/files/stable/Files.Package.appinstaller
2022-07-11 09:57:18.8839|INFO|CheckForRemoteUpdate|SIDELOAD: Current Package Name: Files
2022-07-11 09:57:18.8864|INFO|CheckForRemoteUpdate|SIDELOAD: Remote Package Name: Files
2022-07-11 09:57:18.8884|INFO|CheckForRemoteUpdate|SIDELOAD: Current Version: 2.3.0.0
2022-07-11 09:57:18.8903|INFO|CheckForRemoteUpdate|SIDELOAD: Remote Version: 2.3.3.0
2022-07-11 09:57:18.8923|INFO|CheckForRemoteUpdate|SIDELOAD: Update found.
2022-07-17 14:02:30.2886|INFO|OnLaunched|App launched. Prelaunch: False
2022-07-17 14:02:31.4758|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-07-17 14:02:31.7291|INFO|GetDrivesAsync|Drive added: D:\, Removable
2022-07-17 14:02:32.4306|INFO|GetDrivesAsync|Drive added: M:\, Network
2022-07-17 14:02:33.1840|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\lionel.fesselier\OneDrive
2022-07-17 14:02:33.6290|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive - Gedeon - SIPAOF" mapped to C:\Users\lionel.fesselier\OneDrive - Gedeon - SIPAOF
2022-07-17 14:02:36.2683|INFO|CheckForUpdates|SIDELOAD: Checking for updates...https://cdn.files.community/files/stable/Files.Package.appinstaller
2022-07-17 14:02:36.9903|INFO|CheckForRemoteUpdate|SIDELOAD: Current Package Name: Files
2022-07-17 14:02:37.0623|INFO|CheckForRemoteUpdate|SIDELOAD: Remote Package Name: Files
2022-07-17 14:02:37.0904|INFO|CheckForRemoteUpdate|SIDELOAD: Current Version: 2.3.0.0
2022-07-17 14:02:37.0939|INFO|CheckForRemoteUpdate|SIDELOAD: Remote Version: 2.3.3.0
2022-07-17 14:02:37.0939|INFO|CheckForRemoteUpdate|SIDELOAD: Update found.

**Comment by Josh65-2201** [comment]
@lyonelf Can you see if this is still an issue in the current preview version. https://files.community/download

**Comment by lyonelf** [comment]
this is an old one. No issue since many versions already
