### ISSUE TITLE
Folder icon change wont update in Files

### ISSUE THREAD

**Issue by dhbtfs** [files-community/Files#8672]
### Description

Hi,

If I used Files app to change the icon of a folder, it will be shown correctly in windows default explorer, while in Files it will still show the yellow default folder before changing icon. Even if you refresh, close and open again, still nothing.

### Steps To Reproduce

Change icon of a folder
Refresh Files
Check Windows File Explorer

### Expected behavior

Show correct icon after changing it through Files.

### Files Version

Version: 2.1.18.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 Pro Version	21H2 OS build	22000.556 Experience	Windows Feature Experience Pack 1000.22000.556.0

### Relevant Assets/Logs

NA

**Comment by Josh-65** [comment]
You will need to upload the logs files directly to github. You can get them in files settings > about > open log folder.

**Comment by dhbtfs** [comment]
```
2022-03-21 00:06:34.1375|ERROR|UnhandledExceptionTrapper|Process with an Id of 14468 is not running.
	System.ArgumentException: Process with an Id of 14468 is not running.
   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   at System.Diagnostics.Process.GetProcessById(Int32 processId)
   at FilesFullTrust.Program.TerminateProcess(Int32 processId)
   at FilesFullTrust.Program.HandleCommandLineArgs()
   at FilesFullTrust.Program.Main()
   at FilesFullTrust.Program.<Main>()
2022-03-21 00:43:07.9851|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-03-21 00:43:08.0050|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-03-21 00:43:08.0058|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-03-21 00:43:08.0097|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-03-21 00:43:08.1770|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-03-21 00:43:08.2406|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-21 00:43:08.2924|WARN|StartSTATask|The system cannot find the file specified. (0x80070002)
	System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__1()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-03-21 00:43:09.2139|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-21 00:43:09.2483|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-21 00:43:09.2625|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-03-21 00:43:09.2763|INFO|OnConnectionRequestReceived|Argument: GetNewContextMenuEntries
2022-03-21 00:43:09.6158|INFO|IgnoreExceptions|Attempted to perform an unauthorized operation.
	System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalSubKeyCountCore()
   at Microsoft.Win32.RegistryKey.GetSubKeyNames()
   at FilesFullTrust.Helpers.ShellNewMenuHelper.GetShellNewRegistryEntries(RegistryKey current, RegistryKey root)
   at FilesFullTrust.Helpers.ShellNewMenuHelper.GetShellNewRegistryEntries(RegistryKey current, RegistryKey root)
   at FilesFullTrust.Helpers.ShellNewMenuHelper.GetNewContextMenuEntries()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, Logger logger)
2022-03-21 00:43:09.7675|INFO|CheckQuickLookAvailability|QuickLook detected: False
2022-03-21 00:43:12.5063|INFO|OnConnectionRequestReceived|Argument: FileOperation
2022-03-21 00:43:12.7516|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:12.9534|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:12.9641|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:12.9649|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:12.9706|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:12.9901|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:12.9927|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:12.9968|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:12.9973|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:12.9979|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:14.5115|INFO|OnConnectionRequestReceived|Argument: LoadContextMenu
2022-03-21 00:43:18.5998|INFO|OnConnectionRequestReceived|Argument: FileOperation
2022-03-21 00:43:23.9465|INFO|OnConnectionRequestReceived|Argument: GetFolderIconsFromDLL
2022-03-21 00:43:31.3737|INFO|OnConnectionRequestReceived|Argument: GetFolderIconsFromDLL
2022-03-21 00:43:34.4295|INFO|OnConnectionRequestReceived|Argument: LoadContextMenu
2022-03-21 00:43:35.8037|INFO|OnConnectionRequestReceived|Argument: FileOperation
2022-03-21 00:43:35.8630|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:35.9566|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:35.9575|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:35.9802|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:35.9816|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:35.9845|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:36.0197|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:36.0203|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:36.0375|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:36.0508|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:37.6588|INFO|OnConnectionRequestReceived|Argument: LoadContextMenu
2022-03-21 00:43:38.7256|INFO|OnConnectionRequestReceived|Argument: FileOperation
2022-03-21 00:43:38.7820|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:38.9894|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:38.9979|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:39.0074|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:39.0220|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:39.0306|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:39.0403|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:39.0517|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:39.0628|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-21 00:43:39.0737|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay```

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.0.0?

**Comment by dhbtfs** [comment]
Its fixed.
