### ISSUE TITLE
Missing experimental option——Replacing File Explorer with Files

### ISSUE THREAD

**Issue by Taivasjumala** [files-community/Files#8696]
### Description

![图片](https://user-images.githubusercontent.com/72904966/158936323-4f101c5a-2ed8-46a2-b494-eb7bcef1f4e2.png)

I have been enabling the option 'Replacing File Explorer with Files'. After a cup of updates, this option disappeared. However, as Microsoft provide multi-tabs feature for File Explorer in Windows Insider preview 22572, I want to recover the default setting.

I think in the registry modification batch script, which used to be provided in the document site, may be helpful.

I would be grateful if anyone can help me.

### Steps To Reproduce

I once added theme for files uwp. May be relational

### Expected behavior

(Left empty for necessary)

### Files Version

版本: 2.1.15.0 OS Version: 10.0.22572.201

### Windows Version

版本	Windows 11 家庭中文版 版本	22H2 安装日期	‎2022/‎3/‎18 操作系统版本	22572.201 体验	Windows Feature Experience Pack 1000.22572.201.0

### Relevant Assets/Logs

debug.log
```

2022-03-18 12:11:08.7578|INFO|OnLaunched|App launched. Prelaunch: False
2022-03-18 12:11:08.9848|WARN|MergeSettings|Merging settings failed
	System.ArgumentException: 参数错误。

Error trying to write application data container value
   at System.Runtime.InteropServices.WindowsRuntime.IMapSharedReferenceTypesStubClass.Insert[TKey, TValue](IDictionary`2, TKey, TValue) + 0xd1
   at Windows.ApplicationModel.DataTransfer.DataPackagePropertySet.global::System.Collections.Generic.IDictionary<System.String,System.Object>.set_Item(String, Object) + 0x21
   at Files.ViewModels.SettingsViewModel.Get[TValue](TValue, String) + 0x22d
   at Files.Helpers.RegistryToJsonSettingsMerger.MergeSettings() + 0xaf

2022-03-18 12:11:09.3525|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-03-18 12:11:09.4256|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2022-03-18 12:11:10.0292|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to D:\Download\OneDrive
2022-03-18 12:11:10.0494|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive - mail.dhu.edu.cn" mapped to D:\Download\OneDrive - mail.dhu.edu.cn
2022-03-18 12:26:42.1240|INFO|OnActivated|App activated by CommandLineLaunch
2022-03-18 12:26:42.2433|WARN|MergeSettings|Merging settings failed
	System.ArgumentException: 参数错误。

Error trying to write application data container value
   at System.Runtime.InteropServices.WindowsRuntime.IMapSharedReferenceTypesStubClass.Insert[TKey, TValue](IDictionary`2, TKey, TValue) + 0xd1
   at Windows.ApplicationModel.DataTransfer.DataPackagePropertySet.global::System.Collections.Generic.IDictionary<System.String,System.Object>.set_Item(String, Object) + 0x21
   at Files.ViewModels.SettingsViewModel.Get[TValue](TValue, String) + 0x22d
   at Files.Helpers.RegistryToJsonSettingsMerger.MergeSettings() + 0xaf

2022-03-18 12:26:42.9393|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to D:\Download\OneDrive
2022-03-18 12:26:42.9595|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive - mail.dhu.edu.cn" mapped to D:\Download\OneDrive - mail.dhu.edu.cn
2022-03-18 12:27:01.1322|INFO|OnActivated|App activated by CommandLineLaunch
2022-03-18 12:27:01.1393|WARN|MergeSettings|Merging settings failed
	System.ArgumentException: 参数错误。

Error trying to write application data container value
   at System.Runtime.InteropServices.WindowsRuntime.IMapSharedReferenceTypesStubClass.Insert[TKey, TValue](IDictionary`2, TKey, TValue) + 0xd1
   at Windows.ApplicationModel.DataTransfer.DataPackagePropertySet.global::System.Collections.Generic.IDictionary<System.String,System.Object>.set_Item(String, Object) + 0x21
   at Files.ViewModels.SettingsViewModel.Get[TValue](TValue, String) + 0x22d
   at Files.Helpers.RegistryToJsonSettingsMerger.MergeSettings() + 0xaf

2022-03-18 12:27:02.1289|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to D:\Download\OneDrive
2022-03-18 12:27:02.1627|INFO|IsRunningOnArm|Running on ARM: False
2022-03-18 12:27:02.1642|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive - mail.dhu.edu.cn" mapped to D:\Download\OneDrive - mail.dhu.edu.cn
```
debug_fulltrust.log
```

2022-03-18 12:11:09.3573|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-03-18 12:11:09.3717|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-03-18 12:11:09.3721|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-03-18 12:11:09.3737|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-03-18 12:11:09.4767|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-03-18 12:11:09.7284|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-18 12:11:09.7423|WARN|StartSTATask|系统找不到指定的文件。 (0x80070002)
	System.IO.FileNotFoundException: 系统找不到指定的文件。 (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__1()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-03-18 12:11:10.0300|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-18 12:11:10.0498|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-18 12:11:10.0557|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-03-18 12:11:10.0571|INFO|CheckQuickLookAvailability|QuickLook detected: True
2022-03-18 12:11:10.0687|INFO|OnConnectionRequestReceived|Argument: GetNewContextMenuEntries
2022-03-18 12:14:30.6087|INFO|OnConnectionRequestReceived|Argument: Terminate
2022-03-18 12:26:42.2759|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-03-18 12:26:42.2940|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-03-18 12:26:42.2944|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-03-18 12:26:42.5048|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-18 12:26:42.5215|WARN|StartSTATask|系统找不到指定的文件。 (0x80070002)
	System.IO.FileNotFoundException: 系统找不到指定的文件。 (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__1()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-03-18 12:26:42.9400|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-18 12:26:42.9600|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-18 12:26:42.9654|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-03-18 12:26:42.9667|INFO|CheckQuickLookAvailability|QuickLook detected: True
2022-03-18 12:27:01.1798|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-03-18 12:27:01.3754|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-03-18 12:27:02.0884|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-03-18 12:27:02.1292|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-18 12:27:02.1642|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-18 12:27:02.2848|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-18 12:27:02.2860|WARN|StartSTATask|系统找不到指定的文件。 (0x80070002)
	System.IO.FileNotFoundException: 系统找不到指定的文件。 (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__1()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-03-18 12:27:02.3355|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-18 12:27:02.3401|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-18 12:27:02.3644|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-18 12:27:02.3701|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-18 12:27:02.3703|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-18 12:27:02.3707|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-18 12:27:02.3715|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-03-18 12:27:02.3717|INFO|CheckQuickLookAvailability|QuickLook detected: True
2022-03-18 12:27:02.3928|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-18 12:27:02.3934|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-18 12:27:02.5825|INFO|OnConnectionRequestReceived|Argument: ToggleQuickLook
2022-03-18 12:27:02.5829|INFO|ToggleQuickLook|Toggle QuickLook
2022-03-18 12:27:02.5945|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-18 12:27:02.7650|INFO|OnConnectionRequestReceived|Argument: ToggleQuickLook
2022-03-18 12:27:02.7654|INFO|ToggleQuickLook|Toggle QuickLook
2022-03-18 12:27:02.7998|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-18 12:27:02.8019|WARN|StartSTATask|系统找不到指定的文件。 (0x80070002)
	System.IO.FileNotFoundException: 系统找不到指定的文件。 (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__0()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-03-18 12:27:03.2486|INFO|OnConnectionRequestReceived|Argument: ToggleQuickLook
2022-03-18 12:27:03.2492|INFO|ToggleQuickLook|Toggle QuickLook
2022-03-18 12:27:03.2776|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-18 12:27:03.2801|WARN|StartSTATask|系统找不到指定的文件。 (0x80070002)
	System.IO.FileNotFoundException: 系统找不到指定的文件。 (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__0()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-03-18 12:27:05.5854|INFO|OnConnectionRequestReceived|Argument: ToggleQuickLook
2022-03-18 12:27:05.5857|INFO|ToggleQuickLook|Toggle QuickLook
2022-03-18 12:27:05.5887|INFO|OnConnectionRequestReceived|Argument: ToggleQuickLook
2022-03-18 12:27:05.5890|INFO|ToggleQuickLook|Toggle QuickLook
2022-03-18 12:27:05.7543|INFO|OnConnectionRequestReceived|Argument: ToggleQuickLook
2022-03-18 12:27:05.7546|INFO|ToggleQuickLook|Toggle QuickLook
2022-03-18 12:27:38.6975|INFO|OnConnectionRequestReceived|Argument: ToggleQuickLook
2022-03-18 12:27:38.6982|INFO|ToggleQuickLook|Toggle QuickLook
2022-03-18 12:27:38.6997|INFO|OnConnectionRequestReceived|Argument: ToggleQuickLook
2022-03-18 12:27:38.6999|INFO|ToggleQuickLook|Toggle QuickLook
2022-03-18 12:27:38.8627|INFO|OnConnectionRequestReceived|Argument: ToggleQuickLook
2022-03-18 12:27:38.8629|INFO|ToggleQuickLook|Toggle QuickLook

**Comment by gave92** [comment]
Only available for the sideload version (https://files.community/stable)

**Comment by Taivasjumala** [comment]
Thanks for your patience.
