### ISSUE TITLE
Crash on SMB Network folder

### ISSUE THREAD

**Issue by dhbtfs** [files-community/Files#8742]
### Description

The app is extremely unstable when navigating network folder. Crashes for no reason when trying to open random folder.

### Steps To Reproduce

Open folders on SMB Network folder to see the crash

### Expected behavior

Not crash for starters

### Files Version

Version: 2.1.18.0 OS Version: 10.0.22000.556

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎28/‎01/‎2022 OS build	22000.556 Experience	Windows Feature Experience Pack 1000.22000.556.0
```
### Relevant Assets/Logs

2022-03-22 11:44:50.6152|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-22 11:44:50.6228|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-22 11:44:52.3539|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-22 11:44:52.3647|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-22 11:44:57.6680|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-03-22 11:44:57.6864|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-03-22 11:44:57.6873|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-03-22 11:44:57.6932|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-03-22 11:44:57.8375|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-03-22 11:44:57.8796|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-22 11:44:57.9071|WARN|StartSTATask|The system cannot find the file specified. (0x80070002)
	System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__1()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-03-22 11:44:58.9583|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-22 11:44:58.9939|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-22 11:44:59.0100|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-03-22 11:44:59.0257|INFO|OnConnectionRequestReceived|Argument: GetNewContextMenuEntries
2022-03-22 11:44:59.3837|INFO|IgnoreExceptions|Attempted to perform an unauthorized operation.
	System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalSubKeyCountCore()
   at Microsoft.Win32.RegistryKey.GetSubKeyNames()
   at FilesFullTrust.Helpers.ShellNewMenuHelper.GetShellNewRegistryEntries(RegistryKey current, RegistryKey root)
   at FilesFullTrust.Helpers.ShellNewMenuHelper.GetShellNewRegistryEntries(RegistryKey current, RegistryKey root)
   at FilesFullTrust.Helpers.ShellNewMenuHelper.GetNewContextMenuEntries()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, Logger logger)
2022-03-22 11:44:59.5177|INFO|CheckQuickLookAvailability|QuickLook detected: False```

**Comment by dhbtfs** [comment]
```
2022-03-22 12:01:54.2395|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-22 12:01:54.2399|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-22 12:01:54.2494|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-22 12:01:54.2567|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-03-22 12:02:03.2537|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-03-22 12:02:03.2805|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-03-22 12:02:03.2816|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-03-22 12:02:03.3350|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-03-22 12:02:03.4586|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-03-22 12:02:03.5806|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-22 12:02:03.6127|WARN|StartSTATask|The system cannot find the file specified. (0x80070002)
	System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__1()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-03-22 12:02:04.5645|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-22 12:02:04.6059|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-03-22 12:02:04.6168|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-03-22 12:02:04.6320|INFO|OnConnectionRequestReceived|Argument: GetNewContextMenuEntries
2022-03-22 12:02:05.0335|INFO|IgnoreExceptions|Attempted to perform an unauthorized operation.
	System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalSubKeyCountCore()
   at Microsoft.Win32.RegistryKey.GetSubKeyNames()
   at FilesFullTrust.Helpers.ShellNewMenuHelper.GetShellNewRegistryEntries(RegistryKey current, RegistryKey root)
   at FilesFullTrust.Helpers.ShellNewMenuHelper.GetShellNewRegistryEntries(RegistryKey current, RegistryKey root)
   at FilesFullTrust.Helpers.ShellNewMenuHelper.GetNewContextMenuEntries()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, Logger logger)
2022-03-22 12:02:05.1111|INFO|CheckQuickLookAvailability|QuickLook detected: False

**Comment by gave92** [comment]
Could you upload the full log files (as attachment)? There are two of them: debug.log + debug_fulltrust.log

**Comment by dhbtfs** [comment]
```
2022-03-22 11:39:53.5123|INFO|OnLaunched|App launched. Prelaunch: False
2022-03-22 11:39:54.0131|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-03-22 11:39:54.0531|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2022-03-22 11:39:54.0951|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2022-03-22 11:39:54.1391|INFO|GetDrivesAsync|Drive added: F:\, Fixed
2022-03-22 11:39:54.1851|INFO|GetDrivesAsync|Drive added: G:\, Fixed
2022-03-22 11:39:55.6438|INFO|EnumerateDrivesAsync|Adding cloud provider "Nextcloud" mapped to C:\Users\Arash\Nextcloud
2022-03-22 11:39:55.6717|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\Arash\OneDrive
2022-03-22 11:40:02.8580|INFO|IsRunningOnArm|Running on ARM: False
2022-03-22 11:40:51.5685|ERROR|AppUnhandledException|The parameter is incorrect.

The parameter is incorrect.

	System.ArgumentException: The parameter is incorrect.

The parameter is incorrect.

2022-03-22 11:40:55.4476|INFO|OnLaunched|App launched. Prelaunch: False
2022-03-22 11:40:55.9954|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-03-22 11:40:56.0294|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2022-03-22 11:40:56.0634|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2022-03-22 11:40:56.1044|INFO|GetDrivesAsync|Drive added: F:\, Fixed
2022-03-22 11:40:56.1344|INFO|GetDrivesAsync|Drive added: G:\, Fixed
2022-03-22 11:40:56.8722|INFO|EnumerateDrivesAsync|Adding cloud provider "Nextcloud" mapped to C:\Users\Arash\Nextcloud
2022-03-22 11:40:56.9222|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\Arash\OneDrive
2022-03-22 11:40:59.7856|INFO|IsRunningOnArm|Running on ARM: False
2022-03-22 11:41:05.9661|ERROR|AppUnhandledException|The parameter is incorrect.

The parameter is incorrect.

	System.ArgumentException: The parameter is incorrect.

The parameter is incorrect.

2022-03-22 11:44:24.0317|INFO|OnLaunched|App launched. Prelaunch: False
2022-03-22 11:44:24.8535|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-03-22 11:44:24.9224|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2022-03-22 11:44:24.9904|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2022-03-22 11:44:25.0654|INFO|GetDrivesAsync|Drive added: F:\, Fixed
2022-03-22 11:44:25.1114|INFO|GetDrivesAsync|Drive added: G:\, Fixed
2022-03-22 11:44:26.0342|INFO|EnumerateDrivesAsync|Adding cloud provider "Nextcloud" mapped to C:\Users\Arash\Nextcloud
2022-03-22 11:44:26.0662|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\Arash\OneDrive
2022-03-22 11:44:30.5881|INFO|IsRunningOnArm|Running on ARM: False
2022-03-22 11:44:53.4677|ERROR|AppUnhandledException|The parameter is incorrect.

The parameter is incorrect.

	System.ArgumentException: The parameter is incorrect.

The parameter is incorrect.

2022-03-22 11:44:57.0468|INFO|OnLaunched|App launched. Prelaunch: False
2022-03-22 11:44:57.7727|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-03-22 11:44:57.8406|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2022-03-22 11:44:57.9126|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2022-03-22 11:44:57.9736|INFO|GetDrivesAsync|Drive added: F:\, Fixed
2022-03-22 11:44:58.0536|INFO|GetDrivesAsync|Drive added: G:\, Fixed
2022-03-22 11:44:58.9574|INFO|EnumerateDrivesAsync|Adding cloud provider "Nextcloud" mapped to C:\Users\Arash\Nextcloud
2022-03-22 11:44:58.9934|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\Arash\OneDrive
2022-03-22 11:50:42.4260|INFO|IsRunningOnArm|Running on ARM: False
2022-03-22 12:01:56.7642|ERROR|AppUnhandledException|The parameter is incorrect.

The parameter is incorrect.

	System.ArgumentException: The parameter is incorrect.

The parameter is incorrect.

2022-03-22 12:02:02.6198|INFO|OnLaunched|App launched. Prelaunch: False
2022-03-22 12:02:03.4157|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-03-22 12:02:03.4786|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2022-03-22 12:02:03.5806|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2022-03-22 12:02:03.6876|INFO|GetDrivesAsync|Drive added: F:\, Fixed
2022-03-22 12:02:03.7646|INFO|GetDrivesAsync|Drive added: G:\, Fixed
2022-03-22 12:02:04.5634|INFO|EnumerateDrivesAsync|Adding cloud provider "Nextcloud" mapped to C:\Users\Arash\Nextcloud
2022-03-22 12:02:04.6054|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\Arash\OneDrive
2022-03-22 12:03:07.6724|INFO|IsRunningOnArm|Running on ARM: False
2022-03-22 12:40:49.6504|INFO|OnLaunched|App launched. Prelaunch: False
2022-03-22 12:40:50.8691|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2022-03-22 12:40:51.0496|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2022-03-22 12:40:51.1656|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2022-03-22 12:40:51.3501|INFO|GetDrivesAsync|Drive added: F:\, Fixed
2022-03-22 12:40:51.4886|INFO|GetDrivesAsync|Drive added: G:\, Fixed
2022-03-22 12:40:53.2481|INFO|EnumerateDrivesAsync|Adding cloud provider "Nextcloud" mapped to C:\Users\Arash\Nextcloud
2022-03-22 12:40:53.3146|INFO|EnumerateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\Arash\OneDrive

**Comment by dhbtfs** [comment]
good god its even worse with latest preview build, it was alright with Version: 2.1.34.0   
But now in Version: 2.1.35.0 keep crashing every time I open a folder on my server/network. 

[debug.log](https://github.com/files-community/Files/files/8397422/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8397423/debug_fulltrust.log)

**Comment by gave92** [comment]
Not just SMB (sigh) -> merging with #8759
