### ISSUE TITLE
Error searching on homepage

### ISSUE THREAD

**Issue by Esamrizvie** [files-community/Files#8748]
### Description

ran in to an error when trying to search in home page 

### Steps To Reproduce

Home 
search
type item to search 
error

### Expected behavior

to search for the file that was typed 

### Files Version

2.1.15.0

### Windows Version

Windows Feature Experience Pack 120.2212.4170.0

### Relevant Assets/Logs

2022-03-02 03:01:58.0558|WARN|StartSTATask|The system cannot find the file specified. (0x80070002)
	System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass3_0.<ParseArgumentsAsync>b__1()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()

**Comment by gave92** [comment]
Could you upload the full debug logs as attachments? There are two of them: debug.log + debug_fulltrust.log.

**Comment by gave92** [comment]
Also what do you mean by error? Does the app crash? If not, could you post a screenshot of the error?
