### ISSUE TITLE
Move operation failed

### ISSUE THREAD

**Issue by Arno989** [files-community/Files#8972]
### Description

I attempted to move 9 files from Downloads folder to a subfolder of Program Files (x86)
First attempted to drag between 2 window instances, after failure, attempted ctrl+x -> ctrl+v, attempt failed as well

### Steps To Reproduce

A copy/paste, cut/paste or drag operation between 2 separate Files windows, of which any folder that writes operations needs administrator rights

### Expected behavior

It asks for administrator rights to be able to move the files

### Files Version

2.1.41.0

### Windows Version

Windows 11 22H2 22598.100

### Relevant Assets/Logs

2022-04-21 10:26:53.3136|WARN|InitializeAppServiceConnection|Could not initialize pipe!
	System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.Pipes.NamedPipeClientStream.TryConnect(Int32 timeout, CancellationToken cancellationToken)
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FilesFullTrust.Program.InitializeAppServiceConnection()
2022-04-21 10:27:07.4729|WARN|InitializeAppServiceConnection|Could not initialize pipe!
	System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.Pipes.NamedPipeClientStream.TryConnect(Int32 timeout, CancellationToken cancellationToken)
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FilesFullTrust.Program.InitializeAppServiceConnection()
2022-04-21 10:29:07.9461|WARN|InitializeAppServiceConnection|Could not initialize pipe!
	System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.Pipes.NamedPipeClientStream.TryConnect(Int32 timeout, CancellationToken cancellationToken)
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FilesFullTrust.Program.InitializeAppServiceConnection()
2022-04-21 10:29:08.1008|WARN|InitializeAppServiceConnection|Could not initialize pipe!
	System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.Pipes.NamedPipeClientStream.TryConnect(Int32 timeout, CancellationToken cancellationToken)
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FilesFullTrust.Program.InitializeAppServiceConnection()
2022-04-21 10:29:58.7416|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-04-21 10:29:58.7513|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-04-21 10:29:59.2579|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-04-21 10:29:59.4890|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:29:59.4896|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:29:59.4901|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:29:59.4904|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:29:59.4906|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:29:59.4908|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:29:59.4910|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:29:59.4912|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:29:59.4914|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:29:59.5926|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-04-21 10:29:59.6835|INFO|OnConnectionRequestReceived|Argument: GetNewContextMenuEntries
2022-04-21 10:30:00.0898|INFO|CheckQuickLookAvailability|QuickLook detected: False
2022-04-21 10:30:01.5638|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:30:01.7634|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:30:02.6294|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:30:02.6378|WARN|StartSTATask|The system cannot find the file specified. (0x80070002)
	System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass5_0.<ParseArgumentsAsync>b__0()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-04-21 10:30:04.5280|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:30:04.5297|WARN|StartSTATask|The system cannot find the file specified. (0x80070002)
	System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass5_0.<ParseArgumentsAsync>b__0()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-04-21 10:30:08.8131|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-04-21 10:30:08.8150|WARN|StartSTATask|The system cannot find the file specified. (0x80070002)
	System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at FilesFullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at FilesFullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass5_0.<ParseArgumentsAsync>b__0()
   at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
   
   
  
![image](https://user-images.githubusercontent.com/32594687/164417598-0bf5b9a7-57ae-4c4b-8591-3520eeef8552.png)

**Comment by gave92** [comment]
Could you upload the second debug file (debug_fulltrust.log)?

**Comment by gave92** [comment]
For us, the relevant error is:
> 2022-04-21 10:29:08.1008|WARN|InitializeAppServiceConnection|Could not initialize pipe!
System.UnauthorizedAccessException: Access to the path is denied.
at System.IO.Pipes.NamedPipeClientStream.TryConnect(Int32 timeout, CancellationToken cancellationToken

**Comment by Arno989** [comment]
> Does this persist after app restart or PC restart?

I just tried it again and it did indeed ask for administrator rights as would be expected, which unfortunately makes this bug a lot harder to find.

**Comment by Josh-65** [comment]
@Arno989 have you had this issue happen again?
