### ISSUE TITLE
SetAsDefaultExplorer not working due to FilesOpenDialog directory not existing

### ISSUE THREAD

**Issue by AaronKatzin** [files-community/Files#9110]
### Description

I'm attempting to set Files as default but when toggling the option nothing happens.
In the log I see that the path to the .reg files can't be found:
_2022-05-07 11:35:03.4941|INFO|OnConnectionRequestReceived|Argument: SetAsDefaultExplorer
2022-05-07 11:35:03.5724|INFO|IgnoreExceptions|Could not find a part of the path 'C:\Program Files\WindowsApps\Files_2.2.1.0_x64__1y0xx7n9077q4\Files.Launcher\Assets\FilesOpenDialog'._

While manually searching for the SetFilesAsDefault.reg and UnsetFilesAsDefault.reg files I see that they do exist, but under the Files.FullTrust directory instead of under Files.Launcher.
Meaning they exist at C:\Program Files\WindowsApps\Files_2.2.1.0_x64__1y0xx7n9077q4\Files.FullTrust\Assets\FilesOpenDialog

I've attempted to re-install files to fix the issue but the issue still occurs

### Steps To Reproduce

1. Open Settings -> experimental
2. Toggle "Set Files as the Default File manager"

### Expected behavior

Pop up requesting admin rights, and then Files is default.

### Files Version

2.2.1.0

### Windows Version

Windows 11 10.0.22616.1

### Relevant Assets/Logs

2022-05-07 11:35:03.4941|INFO|OnConnectionRequestReceived|Argument: SetAsDefaultExplorer
2022-05-07 11:35:03.5724|INFO|IgnoreExceptions|Could not find a part of the path 'C:\Program Files\WindowsApps\Files_2.2.1.0_x64__1y0xx7n9077q4\Files.Launcher\Assets\FilesOpenDialog'.
	System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\WindowsApps\Files_2.2.1.0_x64__1y0xx7n9077q4\Files.Launcher\Assets\FilesOpenDialog'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path)
   at Files.FullTrust.MessageHandlers.Win32MessageHandler.ParseArgumentsAsync(PipeStream connection, Dictionary`2 message, String arguments)
   at Files.FullTrust.Program.ParseArgumentsAsync(Dictionary`2 message, String arguments)
   at Files.FullTrust.Program.<>c__DisplayClass13_0.<<OnConnectionRequestReceived>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions(Func`1 action, ILogger logger)

**Comment by AaronKatzin** [comment]
Logs:
[debug_fulltrust.log](https://github.com/files-community/Files/files/8644770/debug_fulltrust.log)

**Comment by AaronKatzin** [comment]
I've installed version 2.2.4.0 and the issue appears to have been fixed
