### ISSUE TITLE
Some icons don't show up on sidebar

### ISSUE THREAD

**Issue by Evgeen** [files-community/Files#9306]
### Description

Icons for Recycle Bin, Libraries, Drives, Network Drives, Network aren't showing on sidebar. 

Buttons itself work and open assigned folders correctly, but only icons are missing. Icons however show up next to tab name when I open either Recycle Bin or Network.

I think it could be related with a fact that I have system installed on drive S: and not C: but other icons show up there and for tabs as I said above. I checked and for other Windows 10 users these icons are showing up, but it's not on my system.

### Steps To Reproduce

1. Open app
2. Look to sidebar
3. Find out icons missing

### Expected behavior

Mentioned icons should be displayed

### Files Version

Version: 2.3.0.0 OS Version: 10.0.19044.1739

### Windows Version

Windows 10 21H2 19044.1739

### Relevant Assets/Logs

**Sceenshots**
https://i.imgur.com/maSlgER.jpeg https://i.imgur.com/inAwjeJ.jpeg

**debug_fulltrust.log**
```
2022-05-31 22:51:08.9494|INFO|OnConnectionRequestReceived|Argument: GetSelectedIconsFromDLL
2022-05-31 22:51:08.9744|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-05-31 22:51:08.9760|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-05-31 22:51:08.9766|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-05-31 22:51:09.1592|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-05-31 22:51:09.1946|WARN|StartSTATask|The system cannot find the file specified. (0x80070002)
	System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem.Open(String path)
   at Files.FullTrust.Helpers.ShellFolderExtensions.GetShellItemFromPathOrPidl(String pathOrPidl)
   at Files.FullTrust.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean getOverlay, Boolean onlyGetOverlay)
   at Files.FullTrust.MessageHandlers.Win32MessageHandler.<>c__DisplayClass8_0.<ParseArgumentsAsync>b__1()
   at Files.FullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2022-05-31 22:51:09.2869|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-05-31 22:51:09.2897|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-05-31 22:51:09.4226|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-05-31 22:51:09.4754|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-05-31 22:51:09.5475|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-05-31 22:51:09.6999|INFO|OnConnectionRequestReceived|Argument: GetNewContextMenuEntries
2022-05-31 22:51:09.7915|INFO|CheckQuickLookAvailability|QuickLook detected: False
```

**debug.log**
```
2022-05-31 22:51:07.7908|INFO|OnLaunched|App launched. Prelaunch: False
2022-05-31 22:51:08.4018|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2022-05-31 22:51:08.5078|INFO|GetDrivesAsync|Drive added: E:\, Fixed
2022-05-31 22:51:08.5768|INFO|GetDrivesAsync|Drive added: S:\, Fixed
2022-05-31 22:51:10.5008|INFO|CheckForUpdates|STORE: Checking for updates...
```

**Comment by gave92** [comment]
Thanks for the report. Merging with #9307. And yes it's because we assume windows is installed on C:.
