### ISSUE TITLE
Featuer: Add a "library in use" dialog when trying to delete

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Files#9444]
### What's the Problem?

From the [discord conversation](https://discord.com/channels/725513575971684472/725514946112127057/988573291218370640) a user tried to delete a library but it didnt work with no in app reason why.

Relevent error
```
2022-06-20 18:24:25.3125|WARN|HandleShellLibraryMessage|
	System.IO.FileLoadException: The process cannot access the file because it is being used by another process. (0x80070020)
   at Vanara.PInvoke.Shell32.IShellLibrary.LoadLibraryFromItem(IShellItem library, STGM grfMode)
   at Files.FullTrust.MessageHandlers.LibrariesHandler.<>c__DisplayClass6_0.<HandleShellLibraryMessage>b__2()
```

### Solution/Idea

Add "This libary is in use by <procces name>" dialog. If its able to get the process using it.

### Alternatives

*

### Files Version

2.3.11.0

### Windows Version

10.0.19043.1889

**Comment by Josh-65** [comment]
Asking @yaichenbaum for approval.

**Comment by yair100** [comment]
Thank you for your feedback. We have a similar dialog when deleting open files, so we should be able to reuse it for this.

**Comment by yair100** [comment]
@Josh65-2201 a potential fix is included in #17830, can you confirm if this resolves the issue?

**Comment by yair100** [comment]
I'm not able to reproduce this issue when deleting libraries, but I can reproduce it when deleting the parent folder of a location containing open files. The linked PR resolves this issue.
