### ISSUE TITLE
Won't copy files to SMB share that has the alternative data stream attribute (ADS)

### ISSUE THREAD

**Issue by xairoo** [files-community/Files#9772]
### Description

First of all: Great work, I am impressed, really, I haven't used Files for a while but now it's just amazing, thanks for this great replacement!

I am trying to copy files with the alternative data stream attribute (ADS) to an SMB share.

Windows Explorer will show me this:
`The file has properties that can't be copied to this location` - I can ignore this and the file will be copied.

Files doesn't show anything, only in the tasks list that the transfer has failed.

It's ADS releated. Can copy all other files or the same file without the ADS thing.

### Steps To Reproduce

Sample ADS file creation with `cmd`:
```
echo good > good.txt
echo bad > bad.txt
good.txt>ads-file.txt:bad.txt
```

Try to copy `ads-file,txt` an SMB share that doesn't support this (ubuntu with an ext4 share for example).

### Expected behavior

File should be copied.

I don't have this problem with my Synology NAS servers, only with my custom SMB share that I run on Ubuntu, but the warning/question should appear on Files or the copy process should just work.

### Files Version

Version: 2.3.7.0 OS Version: 10.0.22622.575

### Windows Version

Windows 11 22H2 10.0.22622 / 22622.575

### Relevant Assets/Logs

Both debug logs didn't contain anything related about that issue.

**Comment by Josh-65** [comment]
Can you see if this is an issue in the preview version? https://files.community/download/preview

**Comment by xairoo** [comment]
> Can you see if this is an issue in the preview version? https://files.community/download/preview

Doesn't work. But I got a message that it has failed. debug.log has no entry because of that.

Anyway, different topic, but I don't want to create a new issue...
Trying to list network drives results always in a crash:

```
2022-11-27 15:22:20.3742|INFO|CheckForUpdates|SIDELOAD: Current Version: 2.3.62.0
2022-11-27 15:22:20.3776|INFO|CheckForUpdates|SIDELOAD: Remote Version: 2.3.62.0
2022-11-27 15:22:20.3810|WARN|CheckForUpdates|SIDELOAD: Update not found.
2022-11-27 15:22:24.9096|ERROR|AppUnhandledException|Value cannot be null. (Parameter 'idList')
	System.ArgumentNullException: Value cannot be null. (Parameter 'idList')
   at Vanara.Windows.Shell.ShellItem.Open(PIDL idList)
   at Files.App.Shell.ShellFolderExtensions.GetShellItemFromPathOrPidl(String pathOrPidl)
   at Files.App.Filesystem.StorageItems.ShellStorageFile.GetFile(String path)
   at Files.App.Filesystem.StorageItems.ShellStorageFile.GetBasicProperties()
   at Files.App.Filesystem.StorageItems.ShellStorageFile.GetBasicPropertiesAsync()
   at Files.App.Filesystem.StorageEnumerators.UniversalStorageEnumerator.AddFileAsync(BaseStorageFile file, StorageFolderWithPath currentStorageFolder, CancellationToken cancellationToken)
   at Files.App.Filesystem.StorageEnumerators.UniversalStorageEnumerator.ListEntries(BaseStorageFolder rootFolder, StorageFolderWithPath currentStorageFolder, CancellationToken cancellationToken, Int32 countLimit, Func`2 intermediateAction, Dictionary`2 defaultIconPairs)
   at Files.App.ViewModels.ItemViewModel.<>c__DisplayClass150_0.<<EnumFromStorageFolderAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Files.App.ViewModels.ItemViewModel.EnumFromStorageFolderAsync(String path, ListedItem currentFolder, BaseStorageFolder rootFolder, StorageFolderWithPath currentStorageFolder, CancellationToken cancellationToken)
   at Files.App.ViewModels.ItemViewModel.EnumerateItemsFromStandardFolderAsync(String path, CancellationToken cancellationToken, LibraryItem library)
   at Files.App.ViewModels.ItemViewModel.RapidAddItemsToCollection(String path, LibraryItem library)
   at Files.App.ViewModels.ItemViewModel.RapidAddItemsToCollectionAsync(String path, String previousDir, Action postLoadCallback)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
```

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaira2** [comment]
What are the steps to reproduce and the required changes to fix?

**Comment by Josh-65** [comment]
That would be a different issue tracked here #9423

**Comment by yaira2** [comment]
@xairoo a fix has been implemented and will be included in one of the next feature releases.
