### ISSUE TITLE
Bug: Right click on dir making Files shutdown

### ISSUE THREAD

**Issue by Relleis** [files-community/Files#9889]
### Description

When I Right Click on a directory within Files interface. Files shutdown nearly instantly. 

### Steps To Reproduce

Open Files. 
Go to any directory (not in the home interface). 
right click on any directory. 
The bug happens at this moment. 

### Expected behavior

It should just open the right-click menu. 

### Files Version

Version : 2.3.11.0 OS Version: 10.0.22000.856

### Windows Version

Windows 11 Professionnel Version	21H2

### Relevant Assets/Logs

2022-09-04 09:55:45.1860|WARN|HandleShellRecentItemsMessage|
	System.ComponentModel.Win32Exception (15): Le lecteur spécifié est introuvable.
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellItem..ctor(String path)
   at Vanara.Windows.Shell.ShellLink.get_Target()
   at Files.FullTrust.MessageHandlers.RecentItemsHandler.<>c__DisplayClass11_0.<HandleShellRecentItemsMessage>b__0()
[debug_fulltrust.log](https://github.com/files-community/Files/files/948
[debug.log](https://github.com/files-community/Files/files/9484289/debug.log)
4288/debug_fulltrust.log)

**Comment by Josh-65** [comment]
Could you reupload you fulltrust log as it didnt work correctly.
