### ISSUE TITLE
When I fit an app on the start-page，it can fit but in a folder former. 

### ISSUE THREAD

**Issue by DF-XYGH** [files-community/Files#9904]
### Description

When I fit an app on the start-page，it can fit but in a folder former. （我固定应用程序在开始页时，打开后时以文件夹形式打开）

### Expected behavior

When I open the app that I fitted, it can be opened directly. （当我打开我固定的应用程序时，它能直接打开。）

### Files Version

版本: 2.3.11.0 OS Version: 10.0.22000.918

### Windows Version

Windows11 21H2 22000.918

### Relevant Assets/Logs

2022-09-06 12:34:10.6888|INFO|OnConnectionRequestReceived|Argument: DetectCloudDrives
2022-09-06 12:34:10.6914|INFO|IgnoreExceptions|Object reference not set to an instance of an object.
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.FullTrust.Helpers.CloudDrivesDetector.DetectGenericCloudDrive()
   at Files.Shared.Extensions.SafetyExtensions.IgnoreExceptions[T](Func`1 action, ILogger logger)
2022-09-06 12:34:10.7045|INFO|OnConnectionRequestReceived|Argument: ShellLibrary
2022-09-06 12:34:10.7059|INFO|OnConnectionRequestReceived|Argument: NetworkDriveOperation
2022-09-06 12:34:11.3786|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-09-06 12:34:11.5765|INFO|OnConnectionRequestReceived|Argument: ShellFolder
2022-09-06 12:34:11.6201|INFO|OnConnectionRequestReceived|Argument: GetIconWithoutOverlay
2022-09-06 12:34:11.9205|INFO|OnConnectionRequestReceived|Argument: DetectQuickLook
2022-09-06 12:34:12.4186|INFO|CheckQuickLookAvailability|QuickLook detected: False
2022-09-06 12:34:19.9446|INFO|OnConnectionRequestReceived|Argument: GetIconOverlay
2022-09-06 12:34:25.8318|INFO|OnConnectionRequestReceived|Argument: ShellRecentItems
2022-09-06 12:35:02.7917|INFO|OnConnectionRequestReceived|Argument: ShellRecentItems

**Comment by gave92** [comment]
Merging with #9740
